### ISSUE TITLE
Firebase warning

### ISSUE THREAD

**Issue by RichardZandi** [AnthonyNahas/ngx-auth-firebaseui#112]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
macOS High Sierra

### Versions
Angular CLI: 6.0.3
Node: 10.1.0
OS: darwin x64
Angular: 6.0.2

### Repro steps
1. include: NgxAuthFirebaseUIModule.forRoot(environment.firebaseTitleIXConfig) in app.module.ts imports section. 
2. ng serve

### The log given by the failure
It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the module builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

CommonJS Modules:
const firebase = require('firebase/app');
require('firebase/<PACKAGE>');

ES Modules:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

### Desired functionality
no warning.

**Comment by AnthonyNahas** [comment]
Thanks for reporting! I've just released v1.2.0
