### ISSUE TITLE
Phone number is not supported - Help required?

### ISSUE THREAD

**Issue by roldengarm** [AnthonyNahas/ngx-auth-firebaseui#127]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### OS and Version?
Windows 10

### Desired functionality
Signing up with phone number is not supported, according to the table on the home page.

### Mention any other details that might be useful
Official demo of firebase UI can be found here: https://fir-ui-demo-84a6c.firebaseapp.com/

I'm happy to help out, but would be good to know some background information from current developers if possible.

**Comment by AnthonyNahas** [comment]
signing in with phone number will be supported soon and 100% configurable 💯 so that can be turned on and off in runtime (depends on your project's needs)

**Comment by AnthonyNahas** [comment]
@roldengarm just for info, this feature is under construction! Sorry for the late feedback

**Comment by AmineAbdessemed** [comment]
Hello @roldengarm, any news about the feature ?

**Comment by AnthonyNahas** [comment]
In dev 📦

**Comment by srathan1** [comment]
eagerly waiting for this :) thanks

**Comment by chunterb** [comment]
Is there any update on this? 

Is a big drawback for me on installing this package over another I found.

I am glad to help, if help is needed.

Just let me know.

Thanks!

**Comment by cedvdb** [comment]
The functionality isn't there yet right ?

**Comment by sachi097** [comment]
Hello @AnthonyNahas, thank you for awesome work and for maintaining this repo. It would really be helpful if you could provide us with **Signing up with phone number**. Please let us know updates for the same.

**Comment by AnthonyNahas** [comment]
I need some dev gurus to make a PR for that.... my time is burning and I can't predict when I would do that...

**Comment by davidyoung77** [comment]
@AnthonyNahas I may be able to work on this issue for a project I am working on.

I have already used the firebase api phone integration.

What advice can you give me? Are there any pitfalls that I should expect?
Any details you would want me to make sure and hit?

I don't expect this to be a huge amount of effort from my perspective

**Comment by AnthonyNahas** [comment]
documenation and unit test would be awesome! 

If you have time for a PR this could be great. I can test ist as well

**Comment by davidyoung77** [comment]
@AnthonyNahas sorry to get your hopes up, but I won't be using this app for my project, and won't be building out the phone feature at this time.

After further exploration my auth requirements are different than what is provided in this library
