### ISSUE TITLE
Feature: Configurable Snackbar messages

### ISSUE THREAD

**Issue by ThyToast** [AnthonyNahas/ngx-auth-firebaseui#129]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### OS and Version?
Windows 10

### Desired functionality
Ability to modify or disable snackbar messages from appropriate configs

**Comment by AnthonyNahas** [comment]
I will add this feature to the next minor release 👍

**Comment by AnthonyNahas** [comment]
@ThyToast 

To enable/disable the snackbar messages - take a look [here](https://github.com/AnthonyNahas/ngx-auth-firebaseui#configuration)

for modifying the messages in runtime, please take a look at the demo app [here](https://ngx-auth-firebaseui.firebaseapp.com/examples/messages)
