### ISSUE TITLE
Angular 7

### ISSUE THREAD

**Issue by jakblak** [AnthonyNahas/ngx-auth-firebaseui#132]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions
Is there a timeline for updating this repo for compatibility with Angular 7?  thanks

**Comment by AnthonyNahas** [comment]
the current version of ngx-auth-firebaseui is fully compatible with angular v7. However, I will release a minor update for the library this week by adding a minor feature and adjusting the peer dependencies

**Comment by rdsingh65** [comment]
I love your work. Please update your dependencies. Here is the problem(s).

Package "ngx-auth-firebaseui" has an incompatible peer dependency to "@angular/flex-layout" (requires "^6.0.0-beta.18", would install "7.0.0-beta.19").
                  Package "ngx-auth-firebaseui" has an incompatible peer dependency to "@angular/cdk" (requires "^6.4.7", would install "7.0.2").
                  Package "ngx-auth-firebaseui" has an incompatible peer dependency to "@angular/material" (requires "^6.4.7", would install "7.0.2").

**Comment by smtapp-smtio-cloud** [comment]
> I love your work. Please update your dependencies. Here is the problem(s).
> 
> Package "ngx-auth-firebaseui" has an incompatible peer dependency to "@angular/flex-layout" (requires "^6.0.0-beta.18", would install "7.0.0-beta.19").
> Package "ngx-auth-firebaseui" has an incompatible peer dependency to "@angular/cdk" (requires "^6.4.7", would install "7.0.2").
> Package "ngx-auth-firebaseui" has an incompatible peer dependency to "@angular/material" (requires "^6.4.7", would install "7.0.2").

To be specific,
$npm i ngx-auth-firebaseui 
your npm package still has old dependencies.

**Comment by AnthonyNahas** [comment]
the release 2.1.0 is on the way

**Comment by smtapp-smtio-cloud** [comment]
Tried 2.10. With ng build --prod --aot and deployed to a webserver, fails to show Oauth logins on Chrome and Safari. However, seems to work fine in Firefox. Anything I am missing here?

**Comment by AnthonyNahas** [comment]
@smtapp-smtio-cloud I uploaded yesterday the latest version of the library to firebase hosting and is working fine on each browser incl. chrome, firefox and safari... 

If you're still facing this kind of issue please consider to open a new separated issue

**Comment by smtapp-smtio-cloud** [comment]
> @smtapp-smtio-cloud I uploaded yesterday the latest version of the library to firebase hosting and is working fine on each browser incl. chrome, firefox and safari...
> 
> If you're still facing this kind of issue please consider to open a new separated issue

I am using the latest version. OAuth login buttons show way at the bottom and they are only visible if scrolled. This is only in Chrome and Safari. Firefox seems to work normally. Any suggestions?
