### ISSUE TITLE
Progress bar doesn't stop and onSuccess doesn't work

### ISSUE THREAD

**Issue by jchavarria1983** [AnthonyNahas/ngx-auth-firebaseui#138]
<ngx-auth-firebaseui (onSuccess)="printUser($event)" (onError)="printError($event)"></ngx-auth-firebaseui>

printError works perfectly but printUser doesnt work and I've noticed progress bar after I type user and pass never stop, it seems like some process is never stop to run or something like that. 

Im using this theme: https://github.com/akveo/ngx-admin

### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version
 Windows 7

### Versions
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.10.5
@angular-devkit/core              7.0.5
@angular-devkit/schematics        0.6.0
@angular/cdk                      7.0.3
@angular/fire                     5.1.0
@angular/flex-layout              7.0.0-beta.19
@angular/material                 6.4.7
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3

### Repro steps
go to login page, type user and pass and click on log in

### The log given by the failure
no error shown in console

### Desired functionality
printUser should show data

**Comment by AnthonyNahas** [comment]
Is that working with any other authentication provider like google, fb, twitter... ?  or is only occurring with the username and password scenario.. ?

**Comment by AnthonyNahas** [comment]
Perhaps you habe problem with your firestore db.
Did you enable firestore in the firebase console ?

**Comment by jchavarria1983** [comment]
Do you think it could be the issue ? I haven't created a database, Do I need to create a real database or cloud firestore ?

**Comment by jchavarria1983** [comment]
Hi @AnthonyNahas I was able to fix the issue, you're right I needed to set firestorage in my console but now I have a question the default settings are:
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
  }
}

but I didn´t work until I changed "if false" to "if true". Could you tell me what's the correct settings please ?

**Comment by AnthonyNahas** [comment]
In the future work, I will make the synchronization with firestore fully optional and configurable while injecting the main module.

Concerning the rules: I will provide some rules example to match ngx-auth-firebaseui's requirements.

you can start now with the basic firestore rules. An advanced one will published later:

```c
// Allow read/write access on all documents to any user signed in to the application
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}
```

feel free to open again the issue if you find any bug or similar cheers 🍺
