### ISSUE TITLE
Provide basic auth guard 

### ISSUE THREAD

**Issue by beeman** [AnthonyNahas/ngx-auth-firebaseui#154]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality

I think it would be great to ship a default auth guard that allows that protecting routes for non-logged in users.

  
### Mention any other details that might be useful

Currently using this:
```typescript
import { Injectable } from '@angular/core'
import { CanActivate, Router } from '@angular/router'
import { AuthProcessService } from 'ngx-auth-firebaseui'
import { map } from 'rxjs/operators'
import { Observable } from 'rxjs'

@Injectable({
  providedIn: 'root',
})
export class IsLoggedInGuard implements CanActivate {

  constructor(private router: Router, private auth: AuthProcessService) {}

  canActivate(): Observable<boolean>  {
   return this.auth.afa.user
      .pipe(map(res => {
        if (res) {
          return true
        }
        this.router.navigate(['/login'])
        return false
      }))
  }
}
```

I'm happy to send in a PR if you like to see this implemented 👍

**Comment by AnthonyNahas** [comment]
I love the idea to provide a default auth guard for angular apps !!! 

We need to provide a new property in the `NgxAuthFirebaseUIConfig` like `authGuardFallbackURL` like below... ->

```bash
src/module/interfaces/config.interface.ts
```
```json 
export interface NgxAuthFirebaseUIConfig {
  authGuardFallbackURL?: string,
  enableFirestoreSync?: boolean,
  onlyEmailPasswordAuth?: boolean,
  toastMessageOnAuthSuccess?: boolean,
  toastMessageOnAuthError?: boolean
}
```

then we have to inject the `NgxAuthFirebaseUIConfigToken` token to get access overt the `NgxAuthFirebaseUIConfig` object -->


```ts
export class IsLoggedInGuard implements CanActivate {

  constructor(@Inject(NgxAuthFirebaseUIConfigToken)
                       private config: NgxAuthFirebaseUIConfig,
                       private router: Router,
                       private auth: AuthProcessService) {}


// your code

// this.router.navigate([`/${this.config.authGuardFallbackURL}`])
```

As I said again, I really like this feature and I would love to see more contributions from angular and firebase pro devs ;)


cheers 🍻

**Comment by AnthonyNahas** [comment]
@beeman thank you again! The guard is now part of [ngx-auth-firebaseui v2.3.0 ](https://www.npmjs.com/package/ngx-auth-firebaseui)! Cheers 🍻
