### ISSUE TITLE
Feat: ability to signin with auth providers via redirection instead of popup

### ISSUE THREAD

**Issue by AnthonyNahas** [AnthonyNahas/ngx-auth-firebaseui#162]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions
`Angular` v7.1.4
`"@angular/fire": "^5.1.1",`
`"firebase": "^5.7.0"`

### Desired functionality

The developers should be able to choose between redirection and popup sign in

### Mention any other details that might be useful
examples:
- [google-signin](https://firebase.google.com/docs/auth/web/google-signin)
- [facebook-signin](https://firebase.google.com/docs/auth/web/facebook-login)

related to #156 - thanks for @Avrohom

**Comment by Avrohom** [comment]
👍

**Comment by sjbr** [comment]
still can't be done?
