### ISSUE TITLE
feat: add support for google yolo (one tap)

### ISSUE THREAD

**Issue by FabienDehopre** [AnthonyNahas/ngx-auth-firebaseui#167]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
It could be a good idea to add support for Google Yolo (One Tap Login) when the Google authentication provider is activated.
You can find the documentation here: https://developers.google.com/identity/one-tap/web/overview
Also a video from the Google I/O 18: https://www.youtube.com/watch?v=kGGMgEfSzMw

### Mention any other details that might be useful
This feature is included in the (firebaseui-web)[https://github.com/firebase/firebaseui-web] repo and in the (firebaseui-angular)[https://github.com/RaphaelJenni/FirebaseUI-Angular] repo which is a wrapper around the first one.

**Comment by AnthonyNahas** [comment]
I am gonna take a look ;) that would be a good idea. Do you have interest to implement that ? PR are welcome <3

**Comment by FabienDehopre** [comment]
I can try to implement this but I have just started a new mission and my weekends are rather busy.
So it might take a long time.

**Comment by milottit** [comment]
Some news about the development? Maybe I can help?

**Comment by AnthonyNahas** [comment]
@milottit you are welcome to contribute! A PR would be a good start <3

**Comment by AnthonyNahas** [comment]
@milottit I will close for the moment this ticket! Please feel free to contribute again whenever you have time


cheers 🍻
