### ISSUE TITLE
Argument of type '"your_app_name_factory"' is not assignable to parameter of type '() => string'

### ISSUE THREAD

**Issue by LiveLikeCounter** [AnthonyNahas/ngx-auth-firebaseui#169]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
> Windows 10

### Versions
Angular CLI: 7.0.7
Node: 10.13.0
OS: win32 x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cdk                      7.2.1
@angular/cli                      7.0.7
@angular/fire                     5.1.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.2.1
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

### Repro steps
Follow all the steps at https://ngx-auth-firebaseui.firebaseapp.com/getting-started + the extra configuration: https://github.com/AnthonyNahas/ngx-auth-firebaseui#2-configuration

### The log given by the failure
```
ERROR in src/app/app.module.ts(22,5): error TS2345: Argument of type '"your_app_name_factory"' is not assignable to parameter of type '() => string'.
```
![image](https://user-images.githubusercontent.com/24720382/51180953-208bbd00-18ca-11e9-8665-f6a68dcb97d5.png)

### Desired functionality
Why this error?
and
How to config there is are no oauth providers?

**Comment by Bielik20** [comment]
I think it is here: https://github.com/AnthonyNahas/ngx-auth-firebaseui/pull/173

**Comment by AnthonyNahas** [comment]
@LiveLikeCounter the docs has been updated! 
you can app name factory could be added like below -> e.g:

```ts
NgxAuthFirebaseUIModule.forRoot(firebaseKey,
 () => 'your_app_name_factory',
      {
        enableFirestoreSync: true,
        toastMessageOnAuthSuccess: true,
        toastMessageOnAuthError: true
      }),
```

thanks for reporting 👍
