### ISSUE TITLE
Login redirect & login control with if statement

### ISSUE THREAD

**Issue by cschoeni** [AnthonyNahas/ngx-auth-firebaseui#171]
Hello Guys

How is it possible to make a redrect as long as the user has not logged in?
How can I check if someone is logged in and if not?

Best regards and thanks for your Help
Christoph

**Comment by AnthonyNahas** [comment]
Hello @cschoeni,

concerning the first question: 

> How is it possible to make a redrect as long as the user has not logged in?

you have multiple ways to achieve that e.g:
- auth guard (see this [PR](https://github.com/AnthonyNahas/ngx-auth-firebaseui/pull/158))

> How can I check if someone is logged in and if not?

please inject `public auth: AngularFireAuth` and use the `user` observable to track the user status --> `this.auth.user.subscribe(...)`


--> 

```ts
import { Injectable } from '@angular/core';

import { AngularFireAuth } from 'angularfire2/auth';
import * as firebase from 'firebase/app';

import { Observable } from 'rxjs/Observable';

@Injectable()
export class AuthService {
  user: Observable<firebase.User>;

  constructor(private firebaseAuth: AngularFireAuth) {
    this.user = firebaseAuth.authState;
  }
`
``

if you have further questions or troubles, please visit us here on [gitter](https://gitter.im/ngx-auth-firebaseui/Lobby) and we will help you!
