### ISSUE TITLE
Not Challenged to Accept Terms of Service or Privacy Policy on Registration

### ISSUE THREAD

**Issue by bailejl** [AnthonyNahas/ngx-auth-firebaseui#172]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Mac Sierra 10.12.6

### Versions
Angular CLI: 7.1.4
Node: 11.0.0
OS: darwin x64
Angular: 7.2.1
... cdk, compiler, core, forms, http

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.11.3
@angular-devkit/build-angular       0.11.3
@angular-devkit/build-optimizer     0.11.3
@angular-devkit/build-webpack       0.11.3
@angular-devkit/core                7.1.3
@angular-devkit/schematics          7.1.4
@angular/animations                 7.1.4
@angular/cli                        7.1.4
@angular/common                     7.1.4
@angular/compiler-cli               7.1.4
@angular/fire                       5.1.1
@angular/flex-layout                7.0.0-beta.22
@angular/language-service           7.1.4
@angular/material                   7.1.1
@angular/platform-browser           7.1.4
@angular/platform-browser-dynamic   7.1.4
@angular/router                     7.1.4
@ngtools/webpack                    7.1.3
@schematics/angular                 7.1.4
@schematics/update                  0.11.4
rxjs                                6.3.3
typescript                          3.1.6
webpack                             4.23.1

### Repro steps

1. Add tosUr and/or privacyPolicyUrl to <ngx-auth-firebaseui>
1. Register a user
1. Not asked to check and accepts tos and pp

### The log given by the failure

None

### Desired functionality

I am challenged to accept terms of service and/or privacy policy before creating an account.

### Mention any other details that might be useful

I am basing my understanding of the software based on this entry in the readme.

`PS: if either tosUrl or privacyPolicyUrl are provided, the user will be asked to check and accepts tos and pp before registering a new account or sign in in anonymously.
`

Also, looked at #80 and its related commit 67683517e0fba4168f97b29c71912e82902c4df7.    It looks like the legality dialog only open for guest only and not registration. It would be nice to have this or a simple set of checkboxes by a disabled register button.

**Comment by AnthonyNahas** [comment]
Thanks for reporting @bailejl 
I will inspect that bug bei writing some unit tests ... hopping to find the issue quickly!!!

**Comment by DannyHalm** [comment]
Hello again Anthony, the text-hint for phone number is misleading. I tried the Mobile regular number from your program into an online reg-editor and the only number matching is +476500000 and other variation will be denied. I suggest you add an option where the user choose his countries suffix in terms of +49 and add any regular Phone number omitting the initial 0( as you know can be Done by regular expression). Best Regards ...Danny

**Comment by AnthonyNahas** [comment]
@DannyHalm I will really appreciate a PR for that

**Comment by AnthonyNahas** [comment]
@bailejl what do you think about two checkboxes in the register card for both tosUrl and privacy policy url ? ... instead of the dialog ?

**Comment by bailejl** [comment]
@AnthonyNahas Yes, with links to tosUrl and privacy policy url.  I think that would be perfect.

**Comment by DannyHalm** [comment]
Yes those would be great to add but the register button should be disabled unless they have clicked on them and accepted the conditions and terms. Cheers ...

**Comment by AnthonyNahas** [comment]
@bailejl I've just fixed this issue! You had 100% right! the signup middle to check privacy policy.. and so on.. was only linked with the guest button! Thanks for reporting again!

@bailejl @DannyHalm what do you think about the process and design related to this topic ?
Should I keep the checkboxes nested in a Material Dialog and the sign up buttons always enabled ? Or do you think that the checkboxes could be in a better place? below the material input ? the sign up and guest buttons disabled until the checkboxes are checked ?

**Comment by DannyHalm** [comment]
I believe an overlay modal would be best choice as it emphasis the acceptance of terms and conditions. Cheers..

**Comment by AnthonyNahas** [comment]
@bailejl @DannyHalm this has been fixed in [v2.3.0](https://www.npmjs.com/package/ngx-auth-firebaseui)! I would appreciate your feedback ❤️  Thank you

**Comment by semla** [comment]
I am only getting asked to approve if I choose guest on the [demo](https://ngx-auth-firebaseui.firebaseapp.com/examples/tos) 
Not if I choose Google or Twitter?

**Comment by jackie-d** [comment]
It seems to still be a problem for a regular signup, with parameters set, no overlay shows or mandatory check required.

`tosUrl="/legal/tos" privacyPolicyUrl="/legal/privacy"`

Please investigate.

**Comment by jackie-d** [comment]
Just look at the code of `ngx-auth-firebaseui-register` component, and the functionality is totally missing.

I think a solution may be to adapt the `ngx-auth-firebaseui` component to act as a register component.
