### ISSUE TITLE
Feat: flat auth design

### ISSUE THREAD

**Issue by Bielik20** [AnthonyNahas/ngx-auth-firebaseui#174]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
Developers should be able to use auth forms without cards.

### Rationale
In some cases such as using dialog for authentication it may look weird to display auth forms in cards as it is already inside a dialog.

### Mention any other details that might be useful
I have tried to make simple MVP of that but it proved to be more complex.
It seams to me that it would be beneficial to actually split `auth.component` to smart and dumb sections to make it easier to modify/swap the dumb parts.
As it seams to me like a more major change I decided to create this issue to discuss it. Moreover, I don't have that much time on my hands these days so I don't know if and when I would be able to work on that. So if anyone feels like doing it then please by all means do.

**Comment by Bielik20** [comment]
While working on my project I have stumbled upon an easy but dirty solution.

```scss
ngx-auth-firebaseui .mat-card {
  margin: 0 !important;
  box-shadow: none !important;
}
```

This seems to work quite well for my purpose and I think could be very easily incorporated into this library. The only thing that needs fixing is those awful `!important`.

**Comment by AnthonyNahas** [comment]
@Bielik20 I've just create a PR related to this issue here #192 

The idea behind that is to make the card css properties optional. So I've added a new input property to `ngx-auth-firebaseui` called `adMatCard` - default set of true |  in order to set those css properties or not...

I'm not so happy with the solution but at least it works! 

what do you think about that ? 

Or should the end developer override `ngx-auth-firebaseui` css properties from outside (e.g: with ::ng-deep)... ?

**Comment by Bielik20** [comment]
Yeah, I also don't think it is a good solution. I think it is a decent workaround but not a solution. I am a little torn in here. On the one hand it is just a workaround, on the other it creates very few problems and is relatively easy to maintain. I will leave it to your best judgment... after all it would be very easy to revert this change should something unexpected happen.

**Comment by AnthonyNahas** [comment]
@Bielik20 some new components will be released very soon and the have a flat design (without `mat-card`) incl. smooth animation! You will like them 👍 

- `ngx-auth-firebaseui-login`
- `ngx-auth-firebaseui-register`

**Comment by cedvdb** [comment]
@AnthonyNahas Great to hear, when is this going to be released ?

Btw a few point if you don't mind:

 - @Bielik20 point is important when making public library like that. Not every one is going to use cards so it's better to leave it to the user whether he wants to put it in his own `mat-card`.
 - In other words it's too hard to make a component that pleases to every uses cases, it's better to give the user the tools to build there own thing. You kinda do this by exporting the `providers` component but I think it should be a bit more granular everywhere


I like the idea of:

```
<mat-card>
   <ngx-firebase-ui-login-form></ngx-firebase-ui-login-form>
   <ngx-firebase-ui-providers></ngx-firebase-ui-providers>
</mat-card>
```

 - would be nice if it was more straight forward to style this thing. The fact that you used important in some places makes it harder.

**Comment by AnthonyNahas** [comment]
I am closing the issue now since the new components are already released! 

Soon I will release a major update supporting angular v9 and smaller bundle size!
