### ISSUE TITLE
The mobile number update does not update correctly. I tried with several versions and it keep indicating that mobile number format incorrect though i followed +497687667 or 004796727382 or 0835367373.

### ISSUE THREAD

**Issue by DannyHalm** [AnthonyNahas/ngx-auth-firebaseui#175]
The mobile number update, once the auttenication is complete and the user-interface is open, it does not update correctly. I have tried it with several versions of mobile numbers as indicated in the placeholder-field(+497687667 or 004796727382 or 0835367373), but with mo luck as i kept receiving an error message stating it is incorrect format.

**Comment by AnthonyNahas** [comment]
I can confirm that! I will take a look on the user component! Thanks for reporting👍
