### ISSUE TITLE
Icons don't resize properly

### ISSUE THREAD

**Issue by liron-navon** [AnthonyNahas/ngx-auth-firebaseui#176]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
OSX High Sierra

### Versions
```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.13.0
@angular-devkit/build-optimizer   0.13.0
@angular-devkit/build-webpack     0.13.0
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cdk                      7.3.0
@angular/fire                     5.1.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.0
@ngtools/webpack                  7.3.0
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.0

```

### Repro steps

1. start a new cli project
2. follow the instructions
3. wrap the ui with a card like so:
```
  <mat-card>
   <mat-card-title>
       Please sign in
   </mat-card-title>
   <mat-card-content>
     <ngx-auth-firebaseui (onSuccess)="onSuccess($event)"
                          (onError)="onError($event)">
     </ngx-auth-firebaseui>
   </mat-card-content>
  </mat-card>
```
4. Resize the window, the Icons are squished togather.

### The log given by the failure
No log, see the image:
<img width="561" alt="screen shot 2019-02-04 at 11 09 50" src="https://user-images.githubusercontent.com/18119833/52202000-81753800-286d-11e9-990c-4524c0902ee1.png">

### Desired functionality
The Icons are not supposed to go on top one another.

**Comment by liron-navon** [comment]
Chrome - Version 71.0.3578.98 (Official Build) (64-bit)
And I also tried this in Firefox

**Comment by AnthonyNahas** [comment]
@liron-navon any update related to that? are you still facing this issue ?

**Comment by AnthonyNahas** [comment]
this should be with the latest version fixed !

If you are still facing the issue please consider reopening the issue!

thank you
