### ISSUE TITLE
Sign out and Delete User buttons do not appear.

### ISSUE THREAD

**Issue by ronyef** [AnthonyNahas/ngx-auth-firebaseui#180]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

> Windows 10

### Versions

OS: win32 x64
Angular: 7.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cdk                      7.3.1
@angular/cli                      7.2.4
@angular/fire                     5.1.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.1
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.28.4

### Repro steps

Added package: ionic 4.

command run: ionic serve

### Desired functionality

 Logout and Delete account appear on **ngx-auth-firebaseui-user** component/page.

### Mention any other details that might be useful

<img width="328" alt="usercapture" src="https://user-images.githubusercontent.com/8429335/52458520-746c8780-2b92-11e9-97b2-377677fe3bee.PNG">

app.module.ts
<code>
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';

import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import { NgxAuthFirebaseUIModule } from 'ngx-auth-firebaseui';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    AppRoutingModule,
    BrowserAnimationsModule,
    NgxAuthFirebaseUIModule.forRoot({
      apiKey: "xxxxxxxxxxx",
      authDomain: "xxxx.firebaseapp.com",
      databaseURL: "https://xxxx.firebaseio.com",
      projectId: "xxxxxxxx",
      storageBucket: "xxxxxx.appspot.com",
      messagingSenderId: "xxxxxxxx"
    }, 
    () => 'app',
    {
      authGuardFallbackURL: '/',
      enableFirestoreSync: true,
      toastMessageOnAuthSuccess: true,
      toastMessageOnAuthError: true
    })
  ],
  providers: [
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}

</code>

**Comment by AnthonyNahas** [comment]
@ronyef thanks for reporting! the `ngx-auth-firebaseui-user` can receive the following input
- `editMode`// default `false'
- `canLogout`// default `true` -> that was set to `false`
- `canDeleteAccount`// default `true` -> that was set to `false`
- `appearance`

I've just patched the library here [ v.2.3.1](https://www.npmjs.com/package/ngx-auth-firebaseui)

[docs](https://github.com/AnthonyNahas/ngx-auth-firebaseui#ngx-auth-firebaseui-userngx-auth-firebaseui-user-1)

cheers 🍻

**Comment by ronyef** [comment]
Hi Anthony,

Thank you! I really appreciate your help. 

Cheers 🍻
