### ISSUE TITLE
updatePhoneNumber failed: First argument "phoneCredential" must be a valid phone credential.

### ISSUE THREAD

**Issue by kuncevic** [AnthonyNahas/ngx-auth-firebaseui#181]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Windows 10

### Versions
```
Angular CLI: 7.3.1
Node: 10.14.2
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cdk                      7.3.1
@angular/cli                      7.3.1
@angular/fire                     5.1.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.1
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
```

### Repro steps
Edit the login profile, add valid phone number [e.g: +49-12345678 or 0041-1234567890](https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/master/src/module/components/user/user.component.html#L88) 

![2019-02-12_10-05-44](https://user-images.githubusercontent.com/1283734/52599963-4054d780-2eae-11e9-997b-c3b130776731.gif)

### The log given by the failure
updatePhoneNumber failed: First argument "phoneCredential" must be a valid phone credential.

### Desired functionality
Should not give an error

### Mention any other details that might be useful
Also I am wondering is there a way to disable/hide the phone number on edit form as really I do not need that in my use case.  However I was looking through the source code and didn't find that possible.

**Comment by alecfullofmer** [comment]
Any timeframe on when this will be fixed?

**Comment by AnthonyNahas** [comment]
This feature (phone number credentials) is a bit complicated. Since other issues have a higher priority, I think this ticket will take a little bit time to bi fixed or adjusted.

Please feel free to open a pull request. I appreciate your help and time thank you
