### ISSUE TITLE
onAccountDeleted doesn't get called on the ngx-auth-firebaseui-user component.

### ISSUE THREAD

**Issue by Avrohom** [AnthonyNahas/ngx-auth-firebaseui#186]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Windows 10.

### Versions

Angular CLI: 7.3.1
Node: 10.15.1
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cdk                      7.3.2
@angular/cli                      7.3.1
@angular/fire                     5.1.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.2
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

### Repro steps
`<ngx-auth-firebaseui-user (onAccountDeleted)="accountDeleted()" *ngIf="thisUser"></ngx-auth-firebaseui-user>
`

### Desired functionality
``` 
accountDeleted() {
    console.info('««« ======================== »»»');
    console.info('««« Account has been deleted »»»');
    console.info('««« ++++++++++++++++++++++++ »»»');
    console.info();
    alert('Account Deleted');
  }
``` 
that the `accountDeleted()` should get called when account is deleted.

**Comment by AnthonyNahas** [comment]
Hi @Avrohom thanks for open the issue. I'm gonna take a look at it in the next days 👍

**Comment by AnthonyNahas** [comment]
I found actually the bug.. this is actually related to firestore while deleting a user entry! This will take few days to be patched
