### ISSUE TITLE
404 error when signing out

### ISSUE THREAD

**Issue by Avrohom** [AnthonyNahas/ngx-auth-firebaseui#187]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```
### OS and Version?
Windows 10.

### Versions
Angular CLI: 7.3.1
Node: 10.15.1
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

## Package Version
@angular-devkit/architect 0.13.1
@angular-devkit/build-angular 0.13.1
@angular-devkit/build-optimizer 0.13.1
@angular-devkit/build-webpack 0.13.1
@angular-devkit/core 7.3.1
@angular-devkit/schematics 7.3.1
@angular/cdk 7.3.2
@angular/cli 7.3.1
@angular/fire 5.1.1
@angular/flex-layout 7.0.0-beta.23
@angular/material 7.3.2
@ngtools/webpack 7.3.1
@schematics/angular 7.3.1
@schematics/update 0.13.1
rxjs 6.3.3
typescript 3.2.4
webpack 4.29.0

### Repro steps
When signing out in the ngx-auth-firebaseui-user component the console shows the following:
![image](https://user-images.githubusercontent.com/6719297/52645185-2def9380-2ed8-11e9-8745-34be0f1c222b.png)

### The log given by the failure
![image](https://user-images.githubusercontent.com/6719297/52645204-33e57480-2ed8-11e9-99c8-cb4142f7f330.png)

### Desired functionality
Seems like the system is trying to redirect to «null» url. 
We need either to debug this behaviour or specify how and where to provide that redirection url.

**Comment by AnthonyNahas** [comment]
Hi @Avrohom, I don't think that the error log is related to the sign out function, however Im gonna test it during the weekend. Thanks for contributing 🍺

**Comment by AnthonyNahas** [comment]
I can only confirm that the error log occurs with the latest release (incl. latest version of firebase and @angular/fire modules)... 

(compare it with the deployed version on firebase)

**Comment by AnthonyNahas** [comment]
@Avrohom I've just reviewed my code one more time and I can confirm one more time that this log/issue is related to the [@angular/fire](https://github.com/angular/angularfire2) package.

I will close this issue for now and I hope that angular fire will fix that soon

**Comment by dvapelnik** [comment]
Hi!
I have the same error now on `@angular/fire:^6.0.2` after sign in action

**Comment by ajonp** [comment]
I receive this only when using Microsoft provider, but not google.
