### ISSUE TITLE
Configurable Password Length

### ISSUE THREAD

**Issue by bailejl** [AnthonyNahas/ngx-auth-firebaseui#191]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### OS and Version?

All

### Versions

N/A

### Repro steps

1. Go to register
2. Add password ( it is hardcoded to a minimum and maximum length)

### The log given by the failure

N/A

### Desired functionality

Pass in a minimum and maximum password length

**Comment by AnthonyNahas** [comment]
@bailejl thanks for opening this issue.

For the password strength feature I am using my [angular material extension password strength](https://github.com/angular-material-extensions/password-strength) that supports different customization like mix max length and many other ([see more](https://github.com/angular-material-extensions/password-strength))

Do you think for ngx-auth-firebaseui a min max password length inputs would be ok ? Or do u prefer to support all input and options that the password strength library supports ?

**Comment by bailejl** [comment]
@AnthonyNahas From my point of view, password are weak and becoming weaker.  So, the standard for a good password is going to change over time.  Therefore, I recommend allowing implementors as much control as possible.

**Comment by madalinignisca** [comment]
I vote for *prefer to support all input and options that the password strength library supports*

**Comment by AnthonyNahas** [comment]
@madalinignisca I will do that 👍

**Comment by AnthonyNahas** [comment]
I've just published a new [version](https://www.npmjs.com/package/ngx-auth-firebaseui) of the library which supports now this requested feature.

The API of the [@angular-material-extensions/password-strength](https://github.com/angular-material-extensions/password-strength) has been integrated in the[ ngx-auth-firebaseui](https://github.com/AnthonyNahas/ngx-auth-firebaseui)

<img width="526" alt="Bildschirmfoto 2019-07-07 um 22 23 42" src="https://user-images.githubusercontent.com/20149774/60773461-5a65af80-a106-11e9-844c-927ab10c84ed.png">
<img width="707" alt="Bildschirmfoto 2019-07-07 um 22 24 12" src="https://user-images.githubusercontent.com/20149774/60773462-5afe4600-a106-11e9-80db-c2791c88d655.png">

here is the demo link: https://ngx-auth-firebaseui.firebaseapp.com/examples/password-strength

cheers and thank you all for contributing🍻
