### ISSUE TITLE
Elements do not contain IDs

### ISSUE THREAD

**Issue by kevin192291** [AnthonyNahas/ngx-auth-firebaseui#206]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions
All

### Repro steps

After installing and implementing, check for IDs on any element

### Desired functionality

I would like to see IDs on all of the elements so I can query against them
Specifically I would like to use Intro.js to assist my users with logging in and more.

**Comment by kevin192291** [comment]
I can add this, I would just like to chat about how to do this first. I have 2 questions:
#1: what would the IDs looklike for the <ngx-auth-firebaseui-providers> component (i would do that first)
- id="google-auth-provider--btn"
#2: Do we want to allow the user to add their own prefix(or suffix) to the IDs?
And if you are okay with me adding this feature, is there anything else that I have not thought of that would be useful/wanted with this?

**Comment by AnthonyNahas** [comment]
@kevin192291 go for it! I already appreciate your contribution!

PS: prefix `ngx-` would be fine 👍

**Comment by AnthonyNahas** [comment]
@kevin192291 any update concerning the PR ? :p

**Comment by kevin192291** [comment]
Hey, I am sorry I this took so long, I got a bit tied up with work.
I believe I have made the correct changes. Sadly I am getting an error when I try to build and test.
The error i receive on gulp build:demo (i think that is correct) is:

`[1/5] Validating package.json...
[2/5] Resolving packages...
warning @angular/http@7.2.12: Switch to @angular/common/http - see https://angular.io/guide/http
warning ngx-material-pages@1.3.2: ngx-material-pages has been renamed to @angular-material-extensions/pages. Please update
your dependencies
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...`

**Comment by kevin192291** [comment]
> @kevin192291 any update concerning the PR ? :p

Are there any docs on the build process? If I can get past this, I will have the work complete really soon.

**Comment by AnthonyNahas** [comment]
@kevin192291 the above error weird ...

may you open a new PR to check that up ?

**Comment by AnthonyNahas** [comment]
@kevin192291 can I close this issue ?

**Comment by kevin192291** [comment]
Yes, At this point I think that would be a good idea, Sorry about keeping this open so long.
