### ISSUE TITLE
Feature Request: Custom user reference

### ISSUE THREAD

**Issue by Donnerstagnacht** [AnthonyNahas/ngx-auth-firebaseui#208]
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

**Versions**
angular v7+

**Desired functionality**
Software developers can customize the logged in user reference.

**Reasons**
Many apps give their users the opportunity to upload data to firestore (for example a post). During that process it is often required to upload custom user data to firestore. Having a custom user reference makes it very easy to upload this additional custom user data. 

On the other hand, it is difficult for less experienced developers to upload the custom user data without a custom user reference.

**Approach**
The code could proably look similiar to the following snippet (most likely there are better soulutions). 
```
<app-structure>
    <ngx-auth-firebaseui
    [providers]="['google']"
    (onSuccess)="onSuccess($event)"
</app-structure>
```
```
onSuccess(user) {
    const userRef: AngularFirestoreDocument<User> = this.afs.doc(`users/${user.uid}`);

    const data = {
      uid: user.uid,
      email: user.email,
      displayName: user.displayName,
      photoURL: user.photoURL,

      // set custom data
      local: user.local,
    };

    return userRef.set(data, { merge: true });
  }
```

**Help**
Since this feature would help my project a lot, I would also like to support you creating that feature. However, I am probably not experienced enough to do so.

If I can help you, let me know. I also wrote you an email with more details. This is the first time that I open an issue/featureRequest on GitHub and hope I did it well. Feedback about this post is appreciated!

Last: Is it possible to estimate, if this feature can be developed and when I could be finalized?

**Comment by AnthonyNahas** [comment]
what about this code snippet ? ;) 

--> 

```
onSuccess(user) {
    const userRef: AngularFirestoreDocument<User> = this.afs.doc(`users/${user.uid}`);

    const data = {
      // set custom data
      local: user.local,
    };

    return userRef.set(data, { merge: true });
  }
```

since you set merge to `true` and you are providing your own type of `AngularFirestoreDocument`.. the above code should works!

Realizing this feature within `ngx-auth-firebaseui` would be very complex! I prefer to keep it as it is and enhance this feature from outside the library.. 

deal ?

**Comment by Donnerstagnacht** [comment]
if it works, it is a deal for sure. Do I have to add that snippet to the
authentification component or to a service or somewhere else?

Because I think your approach won't work, I am not sure, but I think I
already tested the same approach before:

Authentication Component:
[image: image.png]

HTML Component:
[image: image.png]
Is there a crucial mistake somewhere in my Code?

If not, then it simply overrides all data in my user document with your
standard data and it does not add the custom data in the field (means all
the information in the additional fields is lost), as far as I remember.

Is it possible that you submit a pull request to my project?

Tobi

**Comment by Donnerstagnacht** [comment]
I tried it once again and it is not working in my project.

I get the following error message:

> Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in field local)

When I google this error, I find this stackoverflow topic which looks similiar:
[StackOverFlow Question](https://stackoverflow.com/questions/52618971/documentreference-set-called-with-invalid-data-unsupported-field-value-undef)
This is my code:
[authentification component](https://github.com/Donnerstagnacht/leftlife/blob/master/src/app/authentification/authentification.component.ts)

**Comment by AnthonyNahas** [comment]
@Donnerstagnacht please use a custom private firestore service to fit your need. 
`ngx-auth-firebaseui` can't provide in the moment custom interface for the user documents.
Feel free to reopen the issue if you have further questions or suggestions.

Thank you 🍻
