### ISSUE TITLE
Display name property updating when updating the user profile email/password type users

### ISSUE THREAD

**Issue by handihow** [AnthonyNahas/ngx-auth-firebaseui#217]
Below is true only for email/password type users. It seems to work properly for social login users...

When updating the user's profile, the "Name" field in the form does not get automatically filled with the "displayName" property saved in Firebase. 

Also there is an error and the form does not appear nicely.
The console displays: "ERROR TypeError: Cannot read property 'length' of null" on UserComponent.html: 55.

**Comment by Faisalnwz01** [comment]
Seeing the same issue when I try to edit displayName

**Comment by AnthonyNahas** [comment]
I will inspect the code tonight👍

**Comment by AnthonyNahas** [comment]
@handihow how are you updating the user's profile ?

**Comment by handihow** [comment]
@AnthonyNahas thanks for the clarification and the update of the code! 

Also updated my code and now everything is working like a charm!
