### ISSUE TITLE
Issues with password field

### ISSUE THREAD

**Issue by kuncevic** [AnthonyNahas/ngx-auth-firebaseui#219]
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```
Hi @AnthonyNahas thanks for a great library. There is some issues related to password field and password strength indicator that affects the overall experience of registering a new user. Currently it is really hard for an average user to get through the password field on registration tab.

Here is the detailed list:

a) It is does not allow to configure password strength.
b) The password strength indicator is always red color unless you put all the `magic required characters` which is really hard to figure out for average users. 
c) Password length showed N/25 length so some think they really have to put 25 character password
d) Password field allow to type more than maximum allowed characters
e) Password strength has only two color states - red(accent) and blue(primary) so the default password complexity make it hard for users to get from red to blue indicator which make average users think they doing something wrong.

### Repro steps
Navigate to https://ngx-auth-firebaseui.firebaseapp.com/home 
Type more then 25 letters in the password field

![Apr-10-2019 07-07-23](https://user-images.githubusercontent.com/1283734/55835948-76d26a00-5b60-11e9-87e8-00b918e81ec7.gif)

### Desired functionality
Allow password strength to be configurable. (https://github.com/AnthonyNahas/ngx-auth-firebaseui/issues/191)
Do not allow to type more than maximum allowed characters.
Add intermediate state (e.g yellow) to password indicator.

### Other info:
Currently as work around to make things simpler for new registrants I am disabling the  `mat-password-strength` and  `mat-hint` through css
```
mat-password-strength {
  display: none;
}
mat-hint {
  display: none;
}
```

If you have any questions or want me to provide any more details please let me know.

**Comment by AnthonyNahas** [comment]
I've just published a new [version](https://www.npmjs.com/package/ngx-auth-firebaseui) of the library which supports now this requested feature.

The API of the [@angular-material-extensions/password-strength](https://github.com/angular-material-extensions/password-strength) has been integrated in the[ ngx-auth-firebaseui](https://github.com/AnthonyNahas/ngx-auth-firebaseui)

<img width="526" alt="Bildschirmfoto 2019-07-07 um 22 23 42" src="https://user-images.githubusercontent.com/20149774/60773461-5a65af80-a106-11e9-844c-927ab10c84ed.png">
<img width="707" alt="Bildschirmfoto 2019-07-07 um 22 24 12" src="https://user-images.githubusercontent.com/20149774/60773462-5afe4600-a106-11e9-80db-c2791c88d655.png">

here is the demo link: https://ngx-auth-firebaseui.firebaseapp.com/examples/password-strength

cheers and thank you for contributing🍻

**Comment by crunck78** [comment]
Hi Anthony. Thanks as well for this awsome lib. Is there a way to enable Password Strength for the standalone registration component?

**Comment by AnthonyNahas** [comment]
@crunck78 may you open a github ticket for that?

Thank you <3
