### ISSUE TITLE
Ability to rename tabs, form titles and button text

### ISSUE THREAD

**Issue by kuncevic** [AnthonyNahas/ngx-auth-firebaseui#226]
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Desired functionality
Currently there is no way to rename the tabs, form titles and button text. In some cases instead of `Register`/`Registration` you want to put something else like `Sign Up` and instead of `Sign in` / `Signing in`  just `Login`. Sometime you just might want to leave the form title blank. It would be great to be able to do that. 

![image](https://user-images.githubusercontent.com/1283734/56283279-97985200-6154-11e9-8808-d5b28e140a16.png)

![image](https://user-images.githubusercontent.com/1283734/56283418-0a093200-6155-11e9-8de8-3ccb63b68953.png)

**Comment by AnthonyNahas** [comment]
what do you think about something similar to 

```html
<ngx-auth-firebaseui signInTabLabel="YOUR_OWN_LABEL"
                                    signUpTabLabel="YOUR_OWN_LABEL">
</ngx-auth-firebaseui>
```

**Comment by kuncevic** [comment]
@AnthonyNahas yeah that is sounds good. Is it easy to add `signInFomText`, `signInButtonText`, etc if so then `signInTabText` might be a better name just to keep things consistent.

**Comment by AnthonyNahas** [comment]
@kuncevic just for info: #226 the work is in progress (check the related commits ;) )

**Comment by kuncevic** [comment]
@AnthonyNahas yeah, looking good!

**Comment by AnthonyNahas** [comment]
@kuncevic this feature is already done! 
Starting with v2.7.0 the developers will be able to customize every single component's text!

take a look at this gif, it maybe interesting for your team

![1](https://user-images.githubusercontent.com/20149774/57618197-09f92800-7583-11e9-8f22-a46f39be21d4.gif)

Feedback are welcome 👍

**Comment by AnthonyNahas** [comment]
[v.2.7.0](https://www.npmjs.com/package/ngx-auth-firebaseui) has been released
