### ISSUE TITLE
feat: add microsoft and yahoo as authentication providers

### ISSUE THREAD

**Issue by AnthonyNahas** [AnthonyNahas/ngx-auth-firebaseui#232]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Desired functionality
if yahoo or microsoft auth providers have been enabled via the firebase console 
--> the user should be able to process an authentication via the library

### Mention any other details that might be useful

Microsoft and Yahoo sign in now available for Firebase Auth

[microsoft](https://firebase.google.com/docs/auth/web/microsoft-oauth)
[yahoo](https://firebase.google.com/docs/auth/web/yahoo-oauth)

**Comment by handihow** [comment]
Anthony, this would be awesome.. Microsoft login is a most wanted feature... I am working a lot in education and a lot of schools in the Netherlands/Belgium have either Microsoft accounts or Google accounts

**Comment by AnthonyNahas** [comment]
I will add these two auth providers in the next release

**Comment by AnthonyNahas** [comment]
@handihow #232 is ready for deploy

**Comment by willkramer** [comment]
@AnthonyNahas I've been testing out your commit for the Microsoft login and it works well. However, is there support for specifying the tenant in the setCustomParameters?

I'm using your commit right now in an internal application I've developing and I just modified the microsoftAuthProvider to have a tenant (which was required for login).

**Comment by AnthonyNahas** [comment]
@willkramer can u provide a short example ?

PS: I will appreciate a PR from you ❤️
