### ISSUE TITLE
Currently there is no way to observe index change

### ISSUE THREAD

**Issue by kuncevic** [AnthonyNahas/ngx-auth-firebaseui#234]
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```
### Desired functionality

In my use case I want to be able to switch the url based on selected tab. Currently there is no way to know if the tab was being switched. It would be quite useful to be able to track tabinex changes e.g  observable `onTabIndexChange`

**Comment by AnthonyNahas** [comment]
I will add this to the next release 👍

**Comment by AnthonyNahas** [comment]
the following output event has been added to the library 
`@Output() selectedTabChange: EventEmitter<MatTabChangeEvent> = new EventEmitter();`

and can be used like the below snippet 

```html
<ngx-auth-firebaseui (onSuccess)="printUser($event)"
                                 (onError)="printError($event)"
                                 (selectedTabChange)="onTabChange($event)">
            </ngx-auth-firebaseui>
```

I've just implemented the above requested feature and will be pushed into the next patch [v2.7.1](https://www.npmjs.com/package/ngx-auth-firebaseui)

$event has type of `EventEmitter<MatTabChangeEvent>`

`MatTabChangeEvent` is imported form `@angular/material` package

```
/** Index of the currently-selected tab. */
    index: number;
    /** Reference to the currently-selected tab. */
    tab: MatTab;
```
<img width="485" alt="Bildschirmfoto 2019-05-15 um 22 15 47" src="https://user-images.githubusercontent.com/20149774/57806306-22be3500-775f-11e9-8a92-a008ea54869d.png">


@kuncevic cheers 🍻
