### ISSUE TITLE
NgxAuthFirebaseUIModule.forRoot Function expressions are not supported in decorators in 'ɵ0'

### ISSUE THREAD

**Issue by FlashTime** [AnthonyNahas/ngx-auth-firebaseui#238]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> Function expressions are not supported in decorators in 'ɵ0'
- [ ] feature request
```

### OS and Version?
> Windows 10. 

### Versions
npm --version
6.9.0

ng --version
Angular CLI: 7.1.4
Node: 10.15.3
OS: win32 x64
Angular: 7.2.0

### ERROR

when i run command **ng build --prod**
i get this error
```
ERROR in Error during template compile of 'AppModule'
  Function expressions are not supported in decorators in 'ɵ0'
    'ɵ0' contains the error at src\app\app.module.ts(251,7)
      Consider changing the function expression into an exported function.

```
for this code
```
NgxAuthFirebaseUIModule.forRoot(
      environment.firebase,

      () => 'app name',

      {
        enableFirestoreSync: true,
        toastMessageOnAuthSuccess: false, 
        toastMessageOnAuthError: true
      }
    )
```

**251 line is  () => 'app name',**

but when i run same command with this code
```
NgxAuthFirebaseUIModule.forRoot(
      environment.firebase
   )
```
everything ends well.

there is no error either when i use the command **ng build** for both codes

**Comment by AnthonyNahas** [comment]
what about this ?? `(null) => 'app name',`

**Comment by FlashTime** [comment]
Instead of passing `(null) => 'app name',` I just passed `null,` and it solved the problem. Thanks.

**Comment by kashalkar** [comment]
I have the same issue

**Comment by mattpenner** [comment]
What is the point of the appNameFactory?  What function does this serve?  I don't see anything in the docs other than it is suggested to use an anonymous function, which isn't compatible when building to prod.

**Comment by hepaestus** [comment]
Same Issue Here. 
```
  ERROR in ngx-auth-firebaseui/ngx-auth-firebaseui.ts(141,48): Error during template compile of 'AppModule'
  Function expressions are not supported in decorators
    Consider changing the function expression into an exported function.
 ngx-auth-firebaseui/ngx-auth-firebaseui.ts(141,48): Error during template compile of 'AppModule'
  Function expressions are not supported in decorators
    Consider changing the function expression into an exported function.
```
What's the solution? Edit the source code of ngx-auth-firebaseui.ts and remove that one line mentioned above? Am I correct in this?
