### ISSUE TITLE
Password gets disclosed on enter pressed

### ISSUE THREAD

**Issue by kuncevic** [AnthonyNahas/ngx-auth-firebaseui#239]
```
- [x ] bug report
```

### Repro steps
Type name, 
type wrong email, 
type any complex password 
press enter
see the password field text disclosed 
![May-10-2019 21-34-03](https://user-images.githubusercontent.com/1283734/57524600-a34df180-736b-11e9-9d53-616a5c1af71c.gif)

### Desired functionality
The password should never be disclosed unless you press the eye icon manually

**Comment by AnthonyNahas** [comment]
this is already solved!

check this PR at angular-material-extensions/password-strength 
https://github.com/angular-material-extensions/password-strength/pull/170

the password strength lib will be updated in the next rlease

**Comment by kuncevic** [comment]
@AnthonyNahas when are you planing to release?

**Comment by AnthonyNahas** [comment]
in few days I will release v2.7.0 which will contain bug fixes and the ability to customize all components' text (i18n)

**Comment by AnthonyNahas** [comment]
@kuncevic this is not ready yet! The bug needs further investigation! I am on it!

**Comment by AnthonyNahas** [comment]
@kuncevic this has been fixed by updating the [password strength](https://github.com/angular-material-extensions/password-strength) library!

The v2.7.0 release will be published tonight!

**Comment by AnthonyNahas** [comment]
[v2.7.0 ](https://www.npmjs.com/package/ngx-auth-firebaseui) has been released!

Thanks for reporting 👍
