### ISSUE TITLE
Bundle Size - includes entire @angular/fire

### ISSUE THREAD

**Issue by Bielik20** [AnthonyNahas/ngx-auth-firebaseui#243]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
```
Angular CLI: 7.3.1
Node: 8.15.0
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cdk                      7.3.7
@angular/cli                      7.3.1
@angular/fire                     5.1.3
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0
```

### Repro steps
Just build app with this library using
* `ng build --prod --stats-json` 
* and then `npx webpack-bundle-analyzer <path-to-stats-json-in-dist>`

### The log given by the failure
Build with this library included (Parsed size: 1.73 MB)
![image](https://user-images.githubusercontent.com/13436218/57970266-96d72380-797f-11e9-9747-04a52f52299d.png)

### Desired functionality
Build without this library but still using `firebase/auth` (Parsed size: 1.11 MB)
![image](https://user-images.githubusercontent.com/13436218/57970289-d271ed80-797f-11e9-8171-d5f26adf3e7c.png)

**Comment by itsmeneartou** [comment]
Exactly it increased bundle size by 600-700 Kb

**Comment by AnthonyNahas** [comment]
can someone help e to figure out how to solve that ? 

I guess it's a miss configuration within the rollup library...

**Comment by Bielik20** [comment]
@AnthonyNahas I don't have experience with using rollup with gulp, and your configuration is quite extensive (almost 1000 lines) so I am hesitant to start investigating it. 

I created library for angular once and used [ng-packagr](https://www.npmjs.com/package/ng-packagr) for building it, so configuration was minimal. Perhaps it is a good idea to investigate how they are handling those things.

**Comment by AnthonyNahas** [comment]
@Bielik20 I will check that :!

**Comment by jondavidjohn** [comment]
I built a tool to help you analyze webpack bundles for size regressions, and report them directly to GitHub PRs. It's free for open source, so it might be worth checking out and helpful in this scenario.

[https://packtracker.io](https://packtracker.io/?utm_campaign=links&utm_source=github&utm_medium=issueprcomment)

![image](https://user-images.githubusercontent.com/401520/58719965-8ae35c80-8396-11e9-908d-5c5b1d7b8cbf.png)

**Comment by AnthonyNahas** [comment]
@jeroenouw thanks for sharing! this is really awesome! I will try it now

**Comment by arjunyel** [comment]
@AnthonyNahas Hello thanks for the awesome library :D Instead of using custom gulp scripts I HIGHLY recommend you instead migrate to NRWL NX, makes it really easy to publish libraries from an Angular monorepo https://github.com/nrwl/nx/issues/225#issuecomment-392793903

**Comment by AnthonyNahas** [comment]
@arjunyel thanks for your suggestion... it's very difficult at the moment to change the build process of the library. 

However I am looking forward to do that in the near future

**Comment by AnthonyNahas** [comment]
v4 is now release 

https://github.com/AnthonyNahas/ngx-auth-firebaseui/releases/tag/4.0.0
https://www.npmjs.com/package/ngx-auth-firebaseui

this should fix this issue! Please consider reopening this ticket is you are still facing the same issue
