### ISSUE TITLE
Translation i18n input field 'resetPasswordTabText' does not work

### ISSUE THREAD

**Issue by handihow** [AnthonyNahas/ngx-auth-firebaseui#254]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps
The 'resetPasswordTabText' translation input field does not seem to work. I have tried setting it but it does not change. Also I have checked the example website and if you try to translate it to another language (German or Spanish), this particular tab does not change from English.

### Desired functionality
The rest of translation is working great. It would be nice if this one field could be fixed as well.

**Comment by AnthonyNahas** [comment]
@handihow thanks for reporting! I've found the issue and Ill try to fix it asap
