### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by Blunderchips** [AnthonyNahas/ngx-auth-firebaseui#261]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### OS and Version?
Microsoft Windows [Version 10.0.17134.766]

### Versions
<pre>
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@angular/fire                     5.2.1
@angular/flex-layout              2.0.0-rc.1
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</pre>

### Repro steps
Run
> ng add ngx-auth-firebaseui

On a Angular project.

### The log given by the failure
<pre>
$ ng add ngx-auth-firebaseui
Installing packages for tooling via npm.
npm WARN deprecated angularfire2@5.2.1: AngularFire has moved, we're now @angular/fire
npm WARN @angular/material@5.2.5 requires a peer of @angular/core@>=5.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@5.2.5 requires a peer of @angular/common@>=5.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/animations@5.2.11 requires a peer of @angular/core@5.2.11 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@5.2.11 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@5.2.11 requires a peer of @angular/core@5.2.11 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@5.2.11 requires a peer of @angular/common@5.2.11 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@5.2.11 requires a peer of @angular/platform-browser@5.2.11 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@5.2.5 requires a peer of @angular/core@>=5.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@5.2.5 requires a peer of @angular/common@>=5.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/common@^2.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/core@^2.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of rxjs@^5.0.1 but none is
installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of zone.js@^0.7.2 but none
is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ngx-auth-firebaseui@0.1.2
added 19 packages from 7 contributors and audited 25532 packages in 43.234s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
</pre>

### Desired functionality
Actually installs

### Mention any other details that might be useful
The message below is red.
<pre>
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
</pre>

Imports for ngx-auth-firebaseui are not found in when compiling.

**Comment by AnthonyNahas** [comment]
your npm has installed the wrong version... a very old version

--> see the logs`+ ngx-auth-firebaseui@0.1.2`


I would like to suggest to install first the package like below

either

`npm i ngx-auth-firebaseui` or `npm i ngx-auth-firebaseui@latest`


then try to run the schematics

`ng add ngx-auth-firebaseui`

I will appreciate your feeback

**Comment by iislucas** [comment]
I just had the same issue; this happened when I ran: 

```bash
ng add ngx-auth-firebaseui
```

I then removed the entry in `package.json`, and removed it from my `node_modules`, and then re-ran with: 

```bash
ng add ngx-auth-firebaseui@2.7.2
```

And it did the right thing.

**Comment by AnthonyNahas** [comment]
the patch is online. If you're still having some troubles with that issue.. just reopen the issue for further investigation 👍 

thank you and cheers 🍻
