### ISSUE TITLE
Support i18n for User info component

### ISSUE THREAD

**Issue by gbarrionuevo** [AnthonyNahas/ngx-auth-firebaseui#276]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Desired functionality

User Component is not supporting i18n

**Comment by AnthonyNahas** [comment]
I will try to add it to the next release and even better if you provide a PR ... this would be awesome ❤️

**Comment by NagShukl** [comment]
HI Any one working on this, Or should i take it up and raise PR once in place?
