### ISSUE TITLE
Feat: add new component `ngx-auth-firebaseui-avatar` 

### ISSUE THREAD

**Issue by AnthonyNahas** [AnthonyNahas/ngx-auth-firebaseui#278]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions
ngx-auth-firebaseui v3 beta

**Comment by damsorian** [comment]
@AnthonyNahas nice component!, it's possible to add the input '**hideProfileButton**: boolean' in order to hide the 'Profile' button for this component?

**Comment by AnthonyNahas** [comment]
@damsorian yes! I will add that to the api

**Comment by damsorian** [comment]
very thanks @AnthonyNahas ! another thing is the possibility to change the text of the SignOut and Profile buttons in order to translate them to another language. :). I think whit that the component is completed.
