### ISSUE TITLE
Compatibility with svg sprite for icons?

### ISSUE THREAD

**Issue by jeandat** [AnthonyNahas/ngx-auth-firebaseui#282]
### Question

Is it mandatory to load the font icon from material design icons. Does a custom svg sprite would work with your project?

Thanks.

**Comment by AnthonyNahas** [comment]
For this library I am using material design icons as well as custom svgs...
To improve the user experience it's recommended to add the fonts of material icons

**Comment by jeandat** [comment]
Maybe listing icon names you are using would help people create a custom version of the font with just the icon you need. Personally, I'm using a custom svg sprite and it bother me a bit to add a big font with lots of icons just for one form.
