### ISSUE TITLE
Providers are not showing

### ISSUE THREAD

**Issue by yvanvds** [AnthonyNahas/ngx-auth-firebaseui#284]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Windows 10.

### Versions
Angular CLI: 8.1.0
Node: 12.2.0
OS: win32 x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@angular/fire                     5.2.1
@angular/flex-layout              7.0.0-beta.24
@angular/material                 8.0.2
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

### Repro steps
I am using this in a component:
<ngx-auth-firebaseui></ngx-auth-firebaseui>
The login gui works with email and password, but no providers are showing up.

### The log given by the failure
 The debug console has 18 errors on loading the page:
ERROR TypeError: this._delegate.setNgClass is not a function (displayed 18 times)
All errors point to AuthProvidersComponent.html, line 9

### Desired functionality
I would like to see the providers.

### Mention any other details that might be useful
I installed with ng add. All went OK, lines were added to angular.json, component is present in the module, i did  import and assign the AuthProvider in my component and email/password login works.

**Comment by AnthonyNahas** [comment]
you are still using an old version of angular flex layout.. `@angular/flex-layout 7.0.0-beta.24`

just make sure that you're using the latest release of that package

`"@angular/flex-layout": "^8.0.0-beta.26",`

I will patch the library and update the dependencies in the schematics module

**Comment by AnthonyNahas** [comment]
[v3.2.1](https://www.npmjs.com/package/ngx-auth-firebaseui) is now live

thank you 🍻
