### ISSUE TITLE
FirebaseError: [code=permission-denied]: Missing or insufficient permissions.

### ISSUE THREAD

**Issue by gauravshrestha** [AnthonyNahas/ngx-auth-firebaseui#288]
### Bug Report or Feature Request (mark with an `x`)
```
After authenticating to a firebase account, here is the error I get:

ngx-auth-firebaseui.js:367 Error occurred while updating user data with firestore: FirebaseError: [code=permission-denied]: Missing or insufficient permissions.
```

### OS and Version?

Windows 10

### Versions

Angular CLI: 8.1.1
Node: 11.6.0
OS: win32 x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@angular/cdk                      8.0.2
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.0.2
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

### Repro steps

Log in to a firebase account and then this error will appear in the console.

### The log given by the failure

ngx-auth-firebaseui.js:367 Error occurred while updating user data with firestore: FirebaseError: [code=permission-denied]: Missing or insufficient permissions.

**Comment by AnthonyNahas** [comment]
`Missing or insufficient permissions` this error message is not related directly to the library... 
Since we have the autosync users features with firestore... it seems that you still have the default security rules of firestore... 

try the below rules as an example:

```
service cloud.firestore {
  match /databases/{database}/documents {
    // Make sure the uid of the requesting user matches name of the user
    // document. The wildcard expression {userId} makes the userId variable
    // available in rules.
    match /users/{userId} {
      allow read, update, delete: if request.auth.uid == userId;
      allow create: if request.auth.uid != null;
    }
  }
}
```

thank you 🍻
