### ISSUE TITLE
Feature Request - Sign in Tab - Option to show the password as normal text. [Like in Register tab]

### ISSUE THREAD

**Issue by santoshmondal** [AnthonyNahas/ngx-auth-firebaseui#296]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### OS and Version?

macOs Sierra

### Versions

Angular CLI: 8.0.1
Node: 10.15.3
OS: darwin x64
Angular: 8.0.1

**Comment by AnthonyNahas** [comment]
this is already implemented. You can toggle the visibility of the password via the visibility Floating action button on the right side the the password input field

![mat-pass-toggle-visibility](https://user-images.githubusercontent.com/20149774/61871796-5d281900-aeea-11e9-980f-e6c3d9cbf17e.gif)


thank you

**Comment by santoshmondal** [comment]
The toggle visibility options is available only in REGISTER tab, I can not see the feature in SIGN IN tab. Can you share the snippet?

**Comment by santoshmondal** [comment]
### Please look into the Sign In tab in below image - 

<img width="549" alt="Screen Shot 2019-07-25 at 10 42 06 PM" src="https://user-images.githubusercontent.com/5805525/61894176-7a320b80-af2d-11e9-9379-bdd12e341b01.png">

**Comment by AnthonyNahas** [comment]
I see! I will add that feature 🍻

**Comment by AnthonyNahas** [comment]
this has been added to the v3.3.x


thanks for contributing ❤️

**Comment by ryanismert** [comment]
Seems to still be missing from the standalone login component.
