### ISSUE TITLE
Github auth doesnt appear to be working.

### ISSUE THREAD

**Issue by crh225** [AnthonyNahas/ngx-auth-firebaseui#3]
In Chrome, I click on github and see this: 
![image](https://user-images.githubusercontent.com/19475195/38257713-5cdfc9ee-3726-11e8-88b8-7fe55afe915c.png)

Should this also have a popup or something redirecting me back to github? It may not be an issue, just curious on how the github login works.

**Comment by AnthonyNahas** [comment]
Hi, thanks for opening this issue. The github provider was missed in the last version.

[check it now](https://ngx-auth-firebaseui.firebaseapp.com/).

A new version has been now release [0.5.0](https://www.npmjs.com/package/ngx-auth-firebaseui)
