### ISSUE TITLE
Help building

### ISSUE THREAD

**Issue by digitalhurricane-io** [AnthonyNahas/ngx-auth-firebaseui#315]
I'm trying to build the library because I'd like to contribute, but I'm having some problems.

I ran the following:
npm i
npm run build

I may be doing something incorrectly.

I was hoping you could point me in the right direction.

OS: Ubuntu 18,04

ng --version:

Angular CLI: 8.2.1
Node: 10.16.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.802.1
@angular-devkit/core         8.2.1
@angular-devkit/schematics   8.2.1
@schematics/angular          8.2.1
@schematics/update           0.802.1
rxjs                         6.4.0

WARNING in ./tmp/schematics/ng-add/index.js
Module not found: Error: Can't resolve '../../package.json' in '/home/paul/Dev/ngx-auth-firebaseui/tmp/schematics/ng-add'
 @ ./tmp/schematics/ng-add/index.js
[17:39:43] Finished 'build:schematics' after 2.81 s
[17:39:43] Starting 'npm-package'...
dep ->  @angular-material-extensions/password-strength true
dep ->  @angular/animations false
dep ->  @angular/cdk false
dep ->  @angular/common false
dep ->  @angular/core false
dep ->  @angular/fire false
dep ->  @angular/flex-layout false
dep ->  @angular/forms false
dep ->  @angular/material false
dep ->  @angular/router false
dep ->  firebase false
[17:39:43] Finished 'npm-package' after 33 ms
[17:39:43] Starting 'rollup-bundle'...
node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
The "transformBundle" hook used by plugin uglify is deprecated. The "renderChunk" hook should be used instead.
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
'@angular-material-extensions/password-strength' is imported by tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js, but could not be resolved – treating it as an external dependency
'@angular-material-extensions/password-strength' is imported by tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js, but could not be resolved – treating it as an external dependency
'@angular-material-extensions/password-strength' is imported by tmp/lib-es2015/module/ngx-auth-firebase-u-i.module.js, but could not be resolved – treating it as an external dependency
'@angular-material-extensions/password-strength' is imported by tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js, but could not be resolved – treating it as an external dependency
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
'@angular-material-extensions/password-strength' is imported by tmp/lib-es5/module/components/ngx-auth-firebaseui/auth.component.js, but could not be resolved – treating it as an external dependency
'@angular-material-extensions/password-strength' is imported by tmp/lib-es5/module/components/ngx-auth-firebaseui/auth.component.js, but could not be resolved – treating it as an external dependency
'@angular-material-extensions/password-strength' is imported by tmp/lib-es5/module/components/ngx-auth-firebaseui/auth.component.js, but could not be resolved – treating it as an external dependency
'@angular-material-extensions/password-strength' is imported by tmp/lib-es2015/module/components/ngx-auth-firebaseui/auth.component.js, but could not be resolved – treating it as an external dependency
'@firebase/auth' is imported by tmp/lib-es5/module/services/auth-process.service.js, but could not be resolved – treating it as an external dependency
'@firebase/auth' is imported by tmp/lib-es2015/module/services/auth-process.service.js, but could not be resolved – treating it as an external dependency
'@firebase/auth' is imported by tmp/lib-es5/module/services/auth-process.service.js, but could not be resolved – treating it as an external dependency
'@firebase/auth' is imported by tmp/lib-es5/module/services/auth-process.service.js, but could not be resolved – treating it as an external dependency
Circular dependency: tmp/lib-es2015/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es2015/module/components/ngx-auth-firebaseui/auth.component.js -> tmp/lib-es2015/module/services/auth-process.service.js -> tmp/lib-es2015/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es2015/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es2015/module/components/ngx-auth-firebaseui/auth.component.js -> tmp/lib-es2015/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es2015/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es2015/module/components/ngx-auth-firebaseui-user/user.component.js -> tmp/lib-es2015/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es2015/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es2015/module/guards/logged-in.guard.js -> tmp/lib-es2015/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es2015/index.js -> tmp/lib-es2015/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es2015/module/components/ngx-auth-firebaseui-avatar/ngx-auth-firebaseui-avatar.component.js -> tmp/lib-es2015/index.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui/auth.component.js -> tmp/lib-es5/module/services/auth-process.service.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui/auth.component.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui-user/user.component.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/guards/logged-in.guard.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/index.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui-avatar/ngx-auth-firebaseui-avatar.component.js -> tmp/lib-es5/index.js
No name was provided for external module '@angular-material-extensions/password-strength' in output.globals – guessing 'passwordStrength'
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui/auth.component.js -> tmp/lib-es5/module/services/auth-process.service.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui/auth.component.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui-user/user.component.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/guards/logged-in.guard.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/index.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui-avatar/ngx-auth-firebaseui-avatar.component.js -> tmp/lib-es5/index.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui/auth.component.js -> tmp/lib-es5/module/services/auth-process.service.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui/auth.component.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui-user/user.component.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/guards/logged-in.guard.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js
Circular dependency: tmp/lib-es5/index.js -> tmp/lib-es5/module/ngx-auth-firebase-u-i.module.js -> tmp/lib-es5/module/components/ngx-auth-firebaseui-avatar/ngx-auth-firebaseui-avatar.component.js -> tmp/lib-es5/index.js
No name was provided for external module '@angular-material-extensions/password-strength' in output.globals – guessing 'passwordStrength'
[17:39:44] All bundles generated successfully.
[17:39:44] Finished 'rollup-bundle' after 1.27 s
[17:39:44] Finished 'build' after 18 s

**Comment by AnthonyNahas** [comment]
@digitalhurricane-io you did everything right! 

those warnings have been logged due to some dev modules' deprecation!

In the future, I will replace gulp and rollup with the native angular cli to build the library .. see #243

**Comment by digitalhurricane-io** [comment]
Awesome. Thanks.

How are you using this module locally?

This is what I'm doing, but I'm getting a bunch of module not found errors.

If I install from npm, everything works fine.

After I build, I copy the contents of the dist folder to a folder called ngxFirebaseAuthCustom.

Then add this to dependencies in package.json:
"ngx-auth-firebaseui": "file:../ngxFirebaseAuthCustom"

I then run 'npm i'

When I run 'ng serve', I get a bunch of module not found errors.

Any idea what I'm doing wrong?

Here's the errors:

ERROR in ../ngxFirebaseAuthCustom/node_modules/@angular-material-extensions/password-strength/esm2015/password-strength.js
Module not found: Error: Can't resolve '@angular/animations' in '/home/paul/Dev/ngxFirebaseAuthCustom/node_modules/@angular-material-extensions/password-strength/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/common' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/node_modules/@angular-material-extensions/password-strength/esm2015/password-strength.js
Module not found: Error: Can't resolve '@angular/common' in '/home/paul/Dev/ngxFirebaseAuthCustom/node_modules/@angular-material-extensions/password-strength/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/common/http' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/core' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/node_modules/@angular-material-extensions/password-strength/esm2015/password-strength.js
Module not found: Error: Can't resolve '@angular/core' in '/home/paul/Dev/ngxFirebaseAuthCustom/node_modules/@angular-material-extensions/password-strength/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/fire' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/fire/auth' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/fire/firestore' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/flex-layout' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/forms' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/node_modules/@angular-material-extensions/password-strength/esm2015/password-strength.js
Module not found: Error: Can't resolve '@angular/forms' in '/home/paul/Dev/ngxFirebaseAuthCustom/node_modules/@angular-material-extensions/password-strength/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/node_modules/@angular-material-extensions/password-strength/esm2015/password-strength.js
Module not found: Error: Can't resolve '@angular/material' in '/home/paul/Dev/ngxFirebaseAuthCustom/node_modules/@angular-material-extensions/password-strength/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/button' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/card' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/checkbox' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/chips' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/dialog' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/divider' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/icon' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/input' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/menu' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/progress-bar' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/progress-spinner' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/snack-bar' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/tabs' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/material/tooltip' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/platform-browser' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@angular/router' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@firebase/app' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@firebase/auth' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'
ERROR in ../ngxFirebaseAuthCustom/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve 'rxjs/operators' in '/home/paul/Dev/ngxFirebaseAuthCustom/esm2015'

**Comment by AnthonyNahas** [comment]
no no! 

You should use the `link` feature of npm

1. clone the project
2. npm i
3. run `gulp link`
4. cd demo
5. npm i

after that the library will link `ngx-auth-firebaseui` (if do u have some issue just run `npm link ngx-auth-firebaseui`)

now you can serve the app and run `gulp build:watch-fast`

--> every time you make some changes to the source code.. the demo app will be updated on the fly
