### ISSUE TITLE
Icons in password field are messed up

### ISSUE THREAD

**Issue by theolof** [AnthonyNahas/ngx-auth-firebaseui#320]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report
- [ ] feature request
```

### Repro steps
Go to
https://ngx-auth-firebaseui.firebaseapp.com/examples/appearance
All password fields are messed up because of the icons, except 'legacy'.
The password field becomes too high, and the lock icon is below the "eye" icon.

### Desired functionality
Should look like the 'legacy' appearance

**Comment by AnthonyNahas** [comment]
you have right! Which appearance option are you using?

**Comment by theolof** [comment]
I'm using `outline` as appearance

**Comment by AnthonyNahas** [comment]
@theolof do u have a suggestion to improve that ?

**Comment by theolof** [comment]
Sorry, I ended up implementing my own login UI instead.

**Comment by AnthonyNahas** [comment]
This is actually fixed in `ngx-auth-firebaseui` v4

please consider reopening this ticket if you are still facing the same issue
