### ISSUE TITLE
Using provider to register new user,  user will be NOT asked to check and accepts tos and ppdo. 

### ISSUE THREAD

**Issue by avantgarde0707** [AnthonyNahas/ngx-auth-firebaseui#321]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Windows 10

### Desired functionality

Using provider to register new user,  user will be NOT asked to check and accepts tos and ppdo. 

<ngx-auth-firebaseui tabIndex="1" goBackURL="/"  [guestEnabled]="false" tosUrl="/pages/terms" privacyPolicyUrl="/pages/privacy"
            [providers]="[providers.Google, providers.Facebook, providers.Twitter]">
            </ngx-auth-firebaseui>

**Comment by AnthonyNahas** [comment]
which version are u using ? Did you compare your code with the[ demo app](https://ngx-auth-firebaseui.firebaseapp.com/examples/tos) ?

**Comment by avantgarde0707** [comment]
My version 3.3.2. If you use incognito browser window in demo app and register over google provider, toaster (Hello user x.y) is applying without  tos and ppdo dialog.

**Comment by avantgarde0707** [comment]
Any progress on this?

**Comment by AnthonyNahas** [comment]
@avantgarde0707 Did you update the library ? are u still facing that problem ?

**Comment by avantgarde0707** [comment]
Working now. Tnx

**Comment by JanOschii** [comment]
I think, if a user logging in for the first time, we need the terms and privacy window. But if the user already accepted our terms, than he should not asked again. Is there a possibility to see, if a user is logged in for the first time, other than using firestore?

**Comment by AnthonyNahas** [comment]
@JanOschii  I think firebase providers do not support such a feature...
