### ISSUE TITLE
When user is already exists getting an unknown error with all inputs state goes invalid

### ISSUE THREAD

**Issue by kuncevic** [AnthonyNahas/ngx-auth-firebaseui#333]
# Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
```

### Versions
```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.3.0
@angular-devkit/schematics        8.3.0
@angular/cdk                      8.1.3
@angular/cli                      8.3.0
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.3
@angular/pwa                      0.803.0
@ngtools/webpack                  8.3.0
@nguniversal/express-engine       7.1.1
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2
```

### Repro steps
Put existed user details in to registration tab and hit submit.

### The log given by the failure
All inputs goes red on both tabs. Does not tell the reason of the error which is duplicated user in that case.

![Aug-26-2019 12-17-46](https://user-images.githubusercontent.com/1283734/63660838-8e527c80-c7fb-11e9-8e5d-594033b7f33b.gif)

### Desired functionality
Should just say duplicated user. The form should stay valid all expert email address field keeping all the original user input.

**Comment by AnthonyNahas** [comment]
It's hard to handle every single error from firebase!
I decided to reset all input forms in order to handle the error state in a general way...

**Comment by kuncevic** [comment]
Yeah I understand that but this way user experience is really suck. User just interacting normally with a form getting in a such unclear situation with a form state and error message that does not tell the reason what's wrong and why. User can just drop off easily.

**Comment by Tyranwyn** [comment]
It would be nice if we had an onError(error) method so we can handle the message ourselves. Then we can call a snackbar to display the error ourselves. I need this to show the users what error, and I need to translate the error messages.
