### ISSUE TITLE
feat: Add ability to disable email validation

### ISSUE THREAD

**Issue by kuncevic** [AnthonyNahas/ngx-auth-firebaseui#334]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] feature request
```

### Versions
```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.3.0
@angular-devkit/schematics        8.3.0
@angular/cdk                      8.1.3
@angular/cli                      8.3.0
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.3
@angular/pwa                      0.803.0
@ngtools/webpack                  8.3.0
@nguniversal/express-engine       7.1.1
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2
```

### Repro steps
Currently after you login you the new users getting the email validation form.
![Aug-26-2019 12-25-57](https://user-images.githubusercontent.com/1283734/63661124-b393ba80-c7fc-11e9-8717-c02eee7209cf.gif)

### Desired functionality
Want to be able to disable email validation and also in case if validation is enabled just to be able not to force the email validation screen

**Comment by AnthonyNahas** [comment]
why do you prefer to display instead of the email verification component ?
Is it a good idea to replace that with the user component if wished ?

**Comment by kuncevic** [comment]
Do you mean like redirect to default component/route?

**Comment by ChLah** [comment]
You can by setting the "guardProtectedRoutesUntilEmailIsVerified" flag to true on the config object.
