### ISSUE TITLE
Forgot password panel have bugs

### ISSUE THREAD

**Issue by jdayssol** [AnthonyNahas/ngx-auth-firebaseui#337]
- [X ] bug report 
Forgotten password panel doesn't reinitialize after use: If you type the wrong email and submit, you can't use the component anymore.
When you clic a second time on the link password forgotten, you don't navigate to the Forgotten password panel 

### OS and Version?
Windows 10. 
### Versions
Angular CLI: 8.2.0
Node: 10.16.0
OS: win32 x64
Angular: 9.0.0-next.0

### Repro steps
Use forgot password panel once, then try to use it again

**Comment by AnthonyNahas** [comment]
@jeandat any idea?

**Comment by jeandat** [comment]
It works in my version but I haven't integrated latest v3.3.4 yet.
@jdayssol Which version of the lib are you using?

**Comment by jdayssol** [comment]
"ngx-auth-firebaseui": "^3.3.2". 
I will try to update to the most revent one

**Comment by jdayssol** [comment]
In the latest version, the email field in forgot password panel is now always editable. That's was one of my problem.
The navigation problem is also solved. 

There is just a small issue with the close button on the forgot password panel, if I use it, then I have navigation arrow on the panel tab that appears, but there is no need of it. I read that this is a bug from mat-tab, but there must be a way to hide them using css.

**Comment by jdayssol** [comment]
I just leave here a small tip to hide the navigation arrow: 

Add this on the css:
::ng-deep .mat-tab-header-pagination {
  display: none !important;
}

Thanks for this beautiful login component!

**Comment by jeandat** [comment]
They appear if horizontal space is insufficient notably on small screens. If you never want to show them whatever the context, your solution is fine.
I think we can close this issue now.

**Comment by AnthonyNahas** [comment]
are yout still facing that problem ?

**Comment by Blunderchips** [comment]
Yes @AnthonyNahas, I can still reproduction this bug in the [demo](https://ngx-auth-firebaseui.firebaseapp.com/home) and on my local machine. 

The versions I am using:

```bash
Angular CLI: 11.0.4
Node: 12.18.2
OS: linux x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            10.1.1
@angular-devkit/schematics      11.0.4
@angular/cdk                    11.0.3
@angular/fire                   6.1.4
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.3
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.6.3
typescript                      4.0.5
```
