### ISSUE TITLE
Disable auto sign-up when using sign-in with Google Sign-In provider

### ISSUE THREAD

**Issue by xszaryx** [AnthonyNahas/ngx-auth-firebaseui#338]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### OS and Version?

Windows 10

### Versions

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cdk                      8.1.3
@angular/cli                      8.2.2
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.3
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0

### Repro steps

I'm a corporate app when only users with accounts created by admin can log-in and sign-up is disabled. Although when using Google Sign-In new account is automatically created on Firebase. It would be great to have an option to disable this behaviour. 

### Desired functionality

When user that don't have an account created by admin is trying to sign-in using Google Sign-In he is not able to.

**Comment by AnthonyNahas** [comment]
@xszaryx This is a very special case! 
You cant disable creating an account on firebase when the user signs in via google!

If you have any suggestion, please consider to open an appropriate PR

thank you
