### ISSUE TITLE
How to modify AuthComponent.decorators ?

### ISSUE THREAD

**Issue by maximechofflet** [AnthonyNahas/ngx-auth-firebaseui#341]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

>  Linux (Ubuntu).macOS(Mojave)

### Versions

Angular CLI: 8.3.1
Node: 12.9.1
OS: linux x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.1
@angular-devkit/build-angular     0.803.1
@angular-devkit/build-optimizer   0.803.1
@angular-devkit/build-webpack     0.803.1
@angular-devkit/core              8.3.1
@angular-devkit/schematics        8.3.1 (cli-only)
@angular/cdk                      8.1.4
@angular/cli                      8.3.1
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.4
@ngtools/webpack                  8.3.1
@schematics/angular               8.3.1 (cli-only)
@schematics/update                0.803.1 (cli-only)
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

### Issue

Hello @AnthonyNahas  I have a little problem after signed in, the two "lines" buttons are too small and without text (cf screenshot). What I need is a button with my goBackUrl high enough and with custom text. How can I modify this part ? 
Also is it possible to not show at all this part and directly redirect to my goBackUrl ?
Thanks. 
![ngx](https://user-images.githubusercontent.com/45247673/64058672-e8ae5d00-cbae-11e9-8294-53cc644b1d82.png)

**Comment by AnthonyNahas** [comment]
I will check that

**Comment by maximechofflet** [comment]
Thanks 👍

**Comment by JanOschii** [comment]
I struggle with the same problem. Is there a way to fix this with scss or a simple workaround?
Using "ngx-auth-firebaseui": "^3.4.2"
