### ISSUE TITLE
Problem with build --prod

### ISSUE THREAD

**Issue by Glaycow** [AnthonyNahas/ngx-auth-firebaseui#342]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Windowns 10
### Versions

Angular CLI: 8.3.1
Node: 12.3.1
OS: win32 x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.1
@angular-devkit/build-angular     0.803.1
@angular-devkit/build-optimizer   0.803.1
@angular-devkit/build-webpack     0.803.1
@angular-devkit/core              8.3.1
@angular-devkit/schematics        8.3.1
@angular/cdk                      8.1.4
@angular/cli                      8.3.1
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.4
@ngtools/webpack                  8.3.1
@schematics/angular               8.3.1
@schematics/update                0.803.1
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2

### Repro steps

ng build --prod

### The log given by the failure

chunk {0} runtime-es2015.24b02acc1f369d9b9f37.js (runtime) 2.83 kB [entry] [rendered]
chunk {1} main-es2015.a09b1db0e89192b2357e.js (main) 191 bytes [initial] [rendered]
chunk {2} polyfills-es2015.f3154ef75d61ac0e7b7d.js (polyfills) 193 bytes [initial] [rendered]
chunk {3} polyfills-es5-es2015.50be910ad03ac8c8df56.js (polyfills-es5) 150 kB [initial] [rendered]
chunk {4} styles.26664b1debf03018e9a2.css (styles) 216 kB [initial] [rendered]
Date: 2019-09-02T21:46:38.420Z - Hash: 673296cb408a066f4b89 - Time: 10394ms

ERROR in Error during template compile of 'AppModule'
  Function expressions are not supported in decorators in 'ɵ0'
    'ɵ0' contains the error at src/app/app.module.ts(20,7)
      Consider changing the function expression into an exported function.

### Mention any other details that might be useful

https://dev.azure.com/glaycow106/_git/StarCity

**Comment by Glaycow** [comment]
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { environment } from 'src/environments/environment';
import {NgxAuthFirebaseUIModule} from 'ngx-auth-firebaseui';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    NgxAuthFirebaseUIModule.forRoot(
      environment.firebase,
      appNameFactory,
      {
        enableFirestoreSync: true, // enable/disable autosync users with firestore
        toastMessageOnAuthSuccess: true, // whether to open/show a snackbar message on auth success - default : true
        toastMessageOnAuthError: true, // whether to open/show a snackbar message on auth error - default : true
        authGuardFallbackURL: '/publico/login', // url for unauthenticated users - to use in combination with canActivate feature on a route
        authGuardLoggedInURL: '/admin', // url for authenticated users - to use in combination with canActivate feature on a route
        passwordMaxLength: 60, // `min/max` input parameters in components should be within this range.
        passwordMinLength: 8, // Password length min/max in forms independently of each componenet min/max.
        // Same as password but for the name
        nameMaxLength: 19,
        nameMinLength: 2,
        // If set, sign-in/up form is not available until email has been verified.
        // Plus protected routes are still protected even though user is connected.
        guardProtectedRoutesUntilEmailIsVerified: false
      })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

export function appNameFactory(): string {
  return 'StarCity';
}

**Comment by MNorgren** [comment]
I am encountering a similar issue and cannot seem to get around it. What did you do to fix this?
