### ISSUE TITLE
GET idToken & Phone Number Validation Directive

### ISSUE THREAD

**Issue by somoy99** [AnthonyNahas/ngx-auth-firebaseui#348]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### OS and Version?

Arch Linux (Kernel: 5.2.14-arch2-1-ARCH)
### Versions

Angular CLI: 8.3.1
Node: 12.9.1
OS: linux x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

### Desired functionality

1. In the user component, apply a directive to turn phone number validation on/off, can't add any phone number by editing from the component.

2. After signing in event should return an 'idToken' to send that token another back-end endpoint to verify that token via firebase admin sdk

**Comment by AnthonyNahas** [comment]
@somoy99 I will appreciate your PR
