### ISSUE TITLE
Logout button component

### ISSUE THREAD

**Issue by dev-mansonthomas** [AnthonyNahas/ngx-auth-firebaseui#357]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality
Have a "log out" component button.
I need an easy accessible log out button because my application is on a shared computer with multiple user switching often.
Going to a user profile page to find the "sign out" button is not well fitted for my use case.

I guess it should have some hook available (after successful signoff, call a callback) and be able to provide a redirect URL

**Comment by dev-mansonthomas** [comment]
Is there an API that would allow me to implement my custom button in the mean time?

**Comment by BeSpunky** [comment]
Hi @dev-mansonthomas,

If you want to create your own sign-out button component, you have a few choices:
1. Inject `AuthProcessService` from ngx-auth-firebaseui and call the [`async signOut()`](https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/d9c189029112bdac8e8553eb29a737bf9337e91d/src/module/services/auth-process.service.ts#L194) method.
2. Inject `AngularFireAuth` from [AngularFire](https://github.com/angular/angularfire2/blob/master/docs/auth/getting-started.md) then call the `<authService>.auth.signOut()` method.
3. Import the native firebase module and directly use the `signOut()` method like so:
```typescript
import { auth } from 'firebase/app';

firebase.auth().signOut();
```

**Comment by dev-mansonthomas** [comment]
I've ended up doing this : 

```
import { AngularFireAuth } from '@angular/fire/auth';
....
  signOut() {
    this.auth.auth.signOut()
      .then(() => {
        this.onSignOut.emit(); 
        this.router.navigate['/login'];
      })
      .catch(e => console.error('An error happened while signing out!', e));
  }
```

Not sure it's the right thing to do.

**Comment by AnthonyNahas** [comment]
it seems good ! 👍
