### ISSUE TITLE
url does not change

### ISSUE THREAD

**Issue by misogihagi** [AnthonyNahas/ngx-auth-firebaseui#358]
If I serve this app with "ng serve --base-href /subfolder/", url changes 
"http://localhost:4200/assets/mypicture.svg"
to
"http://localhost:4200/assets/subfolder/mypicture.svg"

But, vendor url does not change and is still
"http://localhost:4200/assets/mdi/facebook.svg"

Is there any way to change url ?

**Comment by AnthonyNahas** [comment]
you can change it by yourself via the `angular.json` file:

```json
"assets": [
              "src/assets",
              "src/favicon.ico",
              {
                "glob": "**/*",
                "input": "node_modules/ngx-auth-firebaseui/assets",
                "output": "/your_subfolder/assets"
              },
```
