### ISSUE TITLE
guardProtectedRoutesUntilEmailIsVerified and anonymous Login don't work together

### ISSUE THREAD

**Issue by ChLah** [AnthonyNahas/ngx-auth-firebaseui#359]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Windows 10

### Versions

Angular CLI: 8.1.3
Node: 10.14.2
OS: win32 x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@angular/cdk                      8.1.4
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.1.4
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

### Repro steps
- Make sure you have enabled the anonymous authentication provider in firebase
- Make sure your configuration of the NgxAuthFirebaseUiModule has the guardProtectedRoutesUntilEmailIsVerified flag set to true
- Protect your routes with the LoggedInGuard
- Click on "continue as guest" on the ngx-auth-firebaseui component
=> You are redirected to the page saying you have to confirm your email address.

### Desired functionality
When using the "continue as guest" functionality we did not provide an email address.
So the LoggedInGuard should check the user for the anonymous flag and not guard the route then.

**Comment by AnthonyNahas** [comment]
@ChLah you have right! 

I will really appreciate a PR from you!
