### ISSUE TITLE
The package that you are trying to add does not support schematics

### ISSUE THREAD

**Issue by responder** [AnthonyNahas/ngx-auth-firebaseui#369]
#353 # Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

> Windows 7

### Versions

Angular CLI: 8.3.8
Node: 10.16.3
OS: win32 x64
Angular: 8.2.9

### Repro steps

ng add ngx-auth-firebaseui says:
The package that you are trying to add does not support schematics. 

### The log given by the failure
no log

**Comment by AnthonyNahas** [comment]
please clear your npm cache !

This feature has been added like 6 months ago and we don't have any issue with that! 

If you're still have problems or questions please do not hesitate to reopen this ticket

thank you 🍺

**Comment by Admiralfeb** [comment]
I'm having this issue after clearing the cache by running `npm cache clean --force` and removing the `%appdata%/npm-cache` directory.

**Comment by alexmick** [comment]
Same issue here, even after a cache clear

**Comment by obermoserkitz** [comment]
I have the same problem, cache cleared, folder removed etc.

**Comment by AnthonyNahas** [comment]
I will check that once again

**Comment by couchfault** [comment]
I was just pulling my hair out over the same issue. Issue is `ng add` installs an out of date version (I forget which one, but something ancient). Clearing caches, deleting `node_modules/`, and reinstalling made no difference.

Workaround: just specify the version you want (eg. `ng add ngx-auth-firebaseui@latest`)
