### ISSUE TITLE
Can't run demo

### ISSUE THREAD

**Issue by mikeover** [AnthonyNahas/ngx-auth-firebaseui#374]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
MacOS catalina

### Versions
Angular CLI: 8.3.3
Node: 10.16.3
OS: darwin x64
Angular: 8.2.9
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.3 (cli-only)
@angular-devkit/core         8.3.8
@angular-devkit/schematics   8.3.8
@angular/cdk                 8.2.3
@angular/compiler-cli        8.0.3
@angular/fire                5.2.1
@angular/flex-layout         8.0.0-beta.27
@angular/material            8.2.3
@schematics/angular          8.3.3 (cli-only)
@schematics/update           0.803.3 (cli-only)
rxjs                         6.5.3
typescript                   3.4.5
webpack                      4.41.0

### Repro steps and log

As per [getting started guide](https://ngx-auth-firebaseui.firebaseapp.com/getting-started):
$ `git clone https://github.com/AnthonyNahas/ngx-auth-firebaseui.git`
$ `cd ngx-auth-firebaseui`
$ `npm -i`
$ `gulp link`
```
[14:39:40] Using gulpfile ~/dev/angular/ngx-auth-firebaseui/gulpfile.js
[14:39:40] Starting 'link'...
[14:39:40] npm command failed. See below for errors.

[14:39:40] ENOENT
```
$ `cd demo`
$ `npm i`
$ `ng serve`
```
...
ERROR in /usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@firebase/app' in '/usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015'
ERROR in /usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve '@firebase/auth' in '/usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015'
ERROR in /usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve 'lodash' in '/usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015'
ERROR in /usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve 'rxjs' in '/usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015'
ERROR in /usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve 'rxjs/internal/operators' in '/usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015'
ERROR in /usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015/ngx-auth-firebaseui.js
Module not found: Error: Can't resolve 'rxjs/operators' in '/usr/local/lib/node_modules/ngx-auth-firebaseui/esm2015'
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
```

**Comment by AnthonyNahas** [comment]
the linking step failed ... 


did you try `sudo gulp link` ?
