### ISSUE TITLE
The library is installed but not recognized by the project

### ISSUE THREAD

**Issue by Niyatsu** [AnthonyNahas/ngx-auth-firebaseui#380]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Lubuntu (based on Ubuntu 18.04.3 LTS)
### Versions

```
Angular CLI: 8.3.13
Node: 12.11.1
OS: linux x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.13
@angular-devkit/build-angular     0.803.13
@angular-devkit/build-optimizer   0.803.13
@angular-devkit/build-webpack     0.803.13
@angular-devkit/core              8.3.13
@angular-devkit/schematics        8.3.13
@angular/cdk                      8.2.3
@angular/cli                      8.3.13
@angular/fire                     5.2.1
@angular/flex-layout              2.0.0-rc.1
@angular/material                 8.2.3
@ngtools/webpack                  8.3.13
@schematics/angular               8.3.13
@schematics/update                0.803.13
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

### Repro steps

> ng add ngx-auth-firebaseui

### The log given by the failure

```
+ ngx-auth-firebaseui@0.1.2
added 17 packages from 6 contributors and audited 19327 packages in 49.487s
found 0 vulnerabilities

Installed packages for tooling via npm.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.

```
### Desired functionality

Everything is in the next section.

### Mention any other details that might be useful

So, I'm fairly new to Angular and I was trying to develop a small project for studies, and I encountered this problem when I tried to install this library. When I run the ng add schematics it actually adds the library to the node_modules folder, but as I try to import the module in my app.module.ts, it just is not recognized and I get this error:
![image](https://user-images.githubusercontent.com/25269503/67483764-8b4aff80-f677-11e9-80d5-70019db4b300.png)
![image](https://user-images.githubusercontent.com/25269503/67483784-9867ee80-f677-11e9-8fba-9ef0de078733.png)

Same happened when I tried to install using npm.

Probably it's just my lack of experience or me just being stupid and not seeing something obvious, but I just couldn't find any information that would help me resolve this issue.

**Comment by AnthonyNahas** [comment]
ngx-auth-firebaseui@0.1.2 is a very deprecated version !! 

It seems you have problems with your npm or you npm cache ... 

Please clear you npm cache and upgrade ngx-auth-firebaseui to the latest version! 

Thank you
