### ISSUE TITLE
NgxAuthFirebaseuiAvatarComponent - Mat Menu behind navbar with fixed-top

### ISSUE THREAD

**Issue by DonnaxNL** [AnthonyNahas/ngx-auth-firebaseui#388]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
> Windows 10

### Versions
Angular CLI: 8.3.17
Node: 10.16.3
OS: win32 x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

### Repro steps
https://imgur.com/a/A7lVQ6L - What it looks like now.
I tried to replicate it in Stackblitz, but it couldn't get ngx-auth-firebaseui too work. But my code of the navbar is there.
https://stackblitz.com/edit/angular-zlwtri

### Desired functionality
Option to have the menu (and tooltip) below the navbar.

**Comment by AnthonyNahas** [comment]
I think this is related to your toolbar css properties... 

Could you provide a snippet of your code ?
