### ISSUE TITLE
Is there a way to link users created by multiple providers?

### ISSUE THREAD

**Issue by GreedyA1** [AnthonyNahas/ngx-auth-firebaseui#389]
Question: Is there a way to link users created by multiple providers?
Found this[ link on firebase](https://firebase.google.com/docs/auth/web/account-linking). Is it possible to do same in ngx-auth-firebaseui?

### Current Behaviour

Currently all accounts from my providers have different UID-s.

![users](https://user-images.githubusercontent.com/18186211/68290102-ca7a4700-00a0-11ea-9493-e834d779d26b.png)

### Requested Behaviour

 is it possible to link them all and have same UID?

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request, Question
```

### OS and Version?
Windows 10

### Versions
version 3.4.2

### Repro steps
Install ngx-auth-firebaseui.
enable multiple provider login in firebase.
Login with one provider.
Logout.
Login with different provider with same email.

### Desired functionality
Functionality to enable linking users created by different providers with the same email. 

### Mention any other details that might be useful
This is a question. From the previous Issues, I haven't found any solution.

**Comment by autodora** [comment]
You can go to:
Firebase -> Develop -> Authentication -> Sign-in method -> Advanced
and change option "_One account per email address_". But this will work only for new accounts. Old ones will not be merged.

Moreover I found the following issue: login with first provider (for example Google), log out, now login with another provider (for example Github). You will get following message in web-browser console:


```
code: "auth/account-exists-with-different-credential"
credential: Ki
a: null
accessToken: "819880f00cf128f58b60e96458d4d33c99e7be0a"
providerId: "github.com"
signInMethod: "github.com"
__proto__: Object
email: "michalowski.l@gmail.com"
message: "An account already exists with the same email address but different 
sign-in credentials. Sign in using a provider associated with this email address."
__proto__: Yr
```

is it Firebase or ngx-auth-firebaseui issue?

**Comment by autodora** [comment]
You can go to:
Firebase -> Develop -> Authentication -> Sign-in method -> Advanced
and change option "_One account per email address_". But this will work only for new accounts. Old ones will not be merged.

Moreover I found the following issue: login with first provider (for example Google), log out, now login with another provider (for example Github). You will get following message in web-browser console:


```
code: "auth/account-exists-with-different-credential"
credential: Ki
a: null
accessToken: "819830f00cf127f58b60e96458d4d33c69e7be0a"
providerId: "github.com"
signInMethod: "github.com"
__proto__: Object
email: "myemail@gmail.com"
message: "An account already exists with the same email address but different 
sign-in credentials. Sign in using a provider associated with this email address."
__proto__: Yr
```

is it Firebase or ngx-auth-firebaseui issue?

**Comment by michalowskil** [comment]
Found this thread:

https://stackoverflow.com/questions/37947944/authentication-using-facebook-at-first-and-then-google-causes-an-error-in-fireba

I will allow my users to open many accounts with one email address and then I will use email address as unique ID in my backend.

**Comment by GreedyA1** [comment]
I did manage to link my accounts. I was looking for if there was any way that ngx-auth-firebase managed that.

**Comment by nistrar** [comment]
So how exactly did you do that?
