### ISSUE TITLE
Translation of instructions after registering. 

### ISSUE THREAD

**Issue by Ondrashisko** [AnthonyNahas/ngx-auth-firebaseui#393]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### OS and Version?

Ubuntu 

### Versions
8

### Repro steps

1. Register
2. I recieve page with  "Confirm your e-mail address!" and "A confirmation e-mail has been sent. Check your inbox and click on the link "Confirm my e-mail" to confirm your e-mail address."
3. Non english speaker don`t know what to do.

### Desired functionality

Translation  like in main component

**Comment by AnthonyNahas** [comment]
I would appreciate a PR from you to implement that! 🍻

**Comment by Ondrashisko** [comment]
Now I see that the translations are prepaired there in email-confirmation.component like 
@Input() verifyEmailTitleText: string;
But don`t find out how to use it. Where to place the input filed?

I`am trying to make a PR but exactly don`t know how.
I`ve made a fork but no changes => no PR
Sorry I`am new to this.

btw: shouldn`t it be easyer to let the new translations leave in the *.json file and new languages just let people pull to repo? I know that then noone can say it by his words but is it necessery?
. . .

**Comment by AnthonyNahas** [comment]
the i18n.json files are actually included in the package...
