### ISSUE TITLE
ngx-auth-firebaseui-avatar doesn't show avatar correctly

### ISSUE THREAD

**Issue by OlgerErmakov** [AnthonyNahas/ngx-auth-firebaseui#395]
As soon I include <ngx-auth-firebaseui-avatar></ngx-auth-firebaseui-avatar> the avatar of my gmail account shows my first letters of the mail address and the first letter of my first name. I'm the latest version of ngx-auth-firebaseui.

![image](https://user-images.githubusercontent.com/30296517/68793148-f8d1c680-064c-11ea-8ecf-cf495fbf5e5d.png)

**Comment by AnthonyNahas** [comment]
I would appreciate a PR from you to fix that☢
If you can't, I will try to take look next week

**Comment by OlgerErmakov** [comment]
I'd like to fix that or at least to try this. But I'm a novice at GitHub and Angular. Basically I'm a Java developer and don't know how to handle this. I've create a own fork of your project, checked the fork out and don't know what steps to do next (how to start demo code in the component). I didn't find a how-to to handle it. Can you give me a link or something else? I like your project and would like contributing.

**Comment by AnthonyNahas** [comment]
I will try to take a look soon!
