### ISSUE TITLE
Feat: add support of firebase auth - sign in with apple ID

### ISSUE THREAD

**Issue by AnthonyNahas** [AnthonyNahas/ngx-auth-firebaseui#397]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```
the users/clients should be able to sign in with an apple ID/account since it's now officially supported by firebase

**Comment by AnthonyNahas** [comment]
<img width="647" alt="Bildschirmfoto 2020-02-16 um 12 24 35" src="https://user-images.githubusercontent.com/20149774/74611384-a0064400-50fb-11ea-9f15-ff6ffad33b83.png">

**Comment by AnthonyNahas** [comment]
v4 is now release 

https://github.com/AnthonyNahas/ngx-auth-firebaseui/releases/tag/4.0.0
https://www.npmjs.com/package/ngx-auth-firebaseui

**Comment by kjetilhp** [comment]
Seems like the provider string is case sensitive, 
[providers]="['google', 'facebook', 'Apple', 'microsoft', 'twitter']" 
and that you have to use uppercase A in apple, but lowercase for all others.

Also no mention of Apple in the current documentation besides that it is a working feature.

**Comment by AnthonyNahas** [comment]
@kjetilhp You have right! I 've set apple provider in lower case form


> Also no mention of Apple in the current documentation besides that it is a working feature.

which documentation do you mean ? The Readme?

**Comment by kjetilhp** [comment]
Great!

Yeah, the main readme and ngx-auth-firebaseui-providers.md

**Comment by AnthonyNahas** [comment]
Ok I will check that
