### ISSUE TITLE
How to change the color of buttons

### ISSUE THREAD

**Issue by Ghayyas** [AnthonyNahas/ngx-auth-firebaseui#400]
Hello, I used this Plugin. I must say its an awesome for the developers to save there work and build apps faster. But I'm getting an issue. I don't understand how can I change the color of buttons or the fields. Like button theme by default is asscent but I want to change it in Primary. 
How can I do this?

**Comment by AnthonyNahas** [comment]
At the moment --> you can't !

Do you want to choose the color of each button ?

**Comment by Ghayyas** [comment]
Yes It must be added. User can choose his own color.

**Comment by AnthonyNahas** [comment]
which buttons' color do you want to change ? all of them ?

**Comment by Blunderchips** [comment]
![20201213_210100](https://user-images.githubusercontent.com/7081037/102022041-dc8ee480-3d8c-11eb-8b21-9472c989fea7.jpg)
