### ISSUE TITLE
Verification e-mail is sent only for email/password

### ISSUE THREAD

**Issue by michalowskil** [AnthonyNahas/ngx-auth-firebaseui#401]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Windows 10

### Versions

<pre>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.8
Node: 10.16.3
OS: win32 x64
Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.8 (cli-only)
@angular-devkit/core         8.3.8 (cli-only)
@angular-devkit/schematics   8.3.8 (cli-only)
@schematics/angular          8.3.8 (cli-only)
@schematics/update           0.803.8 (cli-only)
    
</pre>

### Repro steps

1. Firebase -> Develop -> Authentication -> Sign-in method -> Advance -> select "_Allow creation of multiple accounts with the same email address_"
2. Sign-up using a provider other than email/password (I checked Google and Github)
3. "_Confirm your email address_" module will appear but e-mail is not sent (no console errors)
4. Press "_Send confirmation e-mail_" to see a failure in web browser console.

### The log given by the failure

<pre>
{
  "error": {
    "code": 400,
    "message": "MISSING_EMAIL",
    "errors": [
      {
        "message": "MISSING_EMAIL",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
</pre>

### Desired functionality

Should send conformation e-mail.

### Mention any other details that might be useful

I know there is guardProtectedRoutesUntilEmailIsVerified in config but with that option I will not get user e-mail address which I need as user ID in my backend.

**Comment by GreedyA1** [comment]
have the same problem the verification email is not sent on google login.

**Comment by AnthonyNahas** [comment]
accounts related to authentication providers like google, github, facebook, twitter and so on... are already confirmed! Thats's why you are not getting a confirmation email. 

NOTE: Only new created account via username and password would not be verified! That's why the user will get a validation email...


This ticket is not related to the library! This is related to the firebase auth system!

THank you

**Comment by michalowskil** [comment]
ok, maybe I don't understand something

> NOTE: Only new created account via username and password would not be verified! That's why the user will get a validation email...

above is true for "_One account per email address_". After I log in with Google I can call _this.afAuth.authState_  and then I get object with

```
{
  ...
  "email": "me@gmail.com",
  "emailVerified": true,
  ...
}
```

inside. JWT also looks healthy and can be validated with _admin.auth().verifyIdToken(token)_ on my Node backside.

However, the problem appears by choosing "_Multiple accounts per email address_". Here's the object that I get:

```
  ...
  "email": null,
  "emailVerified": false,
  ...
```

I always deleted all users before the test.

So... what am I doing wrong?
