### ISSUE TITLE
Set <ngx-auth-firebaseui-user> options for <ngx-auth-firebaseui-avatar>

### ISSUE THREAD

**Issue by rubenheymans** [AnthonyNahas/ngx-auth-firebaseui#403]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### OS and Version?
Windows 10

### Versions
Angular CLI: 8.3.4
Node: 10.10.0
OS: win32 x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/.router.DELETE           <error>
@angular/cdk                      8.2.0
@angular/cli                      8.3.4
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.0
@angular/pwa                      0.803.4
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

### Repro steps
Add ngx-auth-firebaseui-avatar component in html

### The log given by the failure
n.a.

### Desired functionality
I can't set the options for the ngx-auth-firebaseui-user that appears in the popup.
E.g. Set the 'canDeleteAccount'.
Providing a custom dialog for ngx-auth-firebaseui-avatar with the ngx-auth-firebaseui-user component inside, could solve it too.

### Mention any other details that might be useful
n.a.

**Comment by AnthonyNahas** [comment]
I didn't understand the problem... may you provide as well some screen shots?

**Comment by rubenheymans** [comment]
![image](https://user-images.githubusercontent.com/2543870/69900774-1787cb00-1378-11ea-8804-24d7b6677224.png)

![image](https://user-images.githubusercontent.com/2543870/69900783-3a19e400-1378-11ea-9297-e598b00390f1.png)

![image](https://user-images.githubusercontent.com/2543870/69900786-4605a600-1378-11ea-9499-cd1516451dde.png)

I don't want the user to be able to delete his account in the last step, but I don't know where to provicde this option 'canDeleteAccount', since I'm using a ngx-auth-firebaseui-avatar component.
