### ISSUE TITLE
Google Login not possible on firefox cause CORS

### ISSUE THREAD

**Issue by 0xNyCode** [AnthonyNahas/ngx-auth-firebaseui#406]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### OS and Version?

Windows 10 Pro Build: 18362.476

Firefox 71.0 (64-Bit)

### Versions

Angular CLI: 8.3.20
Node: 12.13.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cdk                      8.2.3
@angular/cli                      8.3.20
@angular/fire                     5.2.3
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

### Repro steps

Make a simple component with a ngx-auth-firebaseui tag and try to Login with Google.

### The log given by the failure

**German:** 
Speicherzugriff automatisch erlaubt für Element zur Aktivitätenverfolgung (Tracker) "https://myapp.firebaseapp.com" auf "http://localhost:4200".
uellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=###CENSORED###. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' stimmt nicht mit 'https://localhost:4200' überein).
"https://myapp.firebaseapp.com" auf "http://localhost:4200".
uellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=###CENSORED###. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' stimmt nicht mit 'https://localhost:4200' überein).
Object { code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred.", stack: "" }
**English (via Google Translate):** 
Memory access allowed automatically for tracking element (tracker) "https://myapp.firebaseapp.com" to "http: // localhost: 4200".
Cross-Origin Request Blocked: The same-source rule prohibits reading the external resource at https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=###CENSORED###. (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'https://localhost: 4200').
Cross-Origin Request Blocked: The same-source rule prohibits reading the external resource at https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=###CENSORED###. (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'https://localhost: 4200').
Object { code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred.", stack: "" }
### Desired functionality

I want to make a simple login page.

### Mention any other details that might be useful

Also tried in Edge and it worked.
Seems like Firefox is blocking cause CORS.

**Comment by AnthonyNahas** [comment]
I believe that the error has nothing to do with ngx-auth-firebaseui or firebase by itself. It's pure browser thing ...


Liebe Grüße aus Göttingen 🍻

**Comment by 0xNyCode** [comment]
I also tried on chrome. It is firefox' fault. I think mozilla will fix this in a future update. 

Liebe Grüße zurück aus Köln :blush:
