### ISSUE TITLE
Module not found when imported despite package being found in node_modules

### ISSUE THREAD

**Issue by Wurby** [AnthonyNahas/ngx-auth-firebaseui#412]
Not sure what I am doing wrong. The ng add method wasn't working for me, so I attempted installing via npm I --save and when I imported it in the app module as per instructions, the error cannot find module ngx-auth-firebaseui appeared.

**Comment by gilmourguru** [comment]
Change your import statement to this:

`import { NgxAuthFirebaseUIModule } from 'ngx-auth-firebaseui/dist';`

**Comment by Wurby** [comment]
Went back to it after a few days and it is now working great. Not sure what changed. Thangs for the response @gilmourguru
