### ISSUE TITLE
compilation error after moving to angular 9

### ISSUE THREAD

**Issue by zackarychapple** [AnthonyNahas/ngx-auth-firebaseui#425]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] feature request
```

### OS and Version?

Mac OS Mojave
### Versions

```@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@angular/cdk                      9.0.0-rc.7
@angular/fire                     5.3.0
@angular/flex-layout              7.0.0-beta.19
@angular/material                 9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.8
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.0-rc.8
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
```

### Repro steps

Upgraded to angular 9 and tried to do a `ng serve`

### The log given by the failure

```ERROR in Failed to compile entry-point @angular-material-extensions/password-strength (module as esm5) due to compilation errors:
node_modules/@angular-material-extensions/password-strength/esm5/password-strength.es5.js:646:30 - error NG1010: Value at position 1 in the NgModule.imports of MatPasswordStrengthModule is not a reference: [object Object]

646                     imports: [
                                 ~
647                         CommonModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
651                         MatRippleModule
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
652                     ],
    ~~~~~~~~~~~~~~~~~~~~~

```

### Desired functionality

I'm not opening this as a bug since ng9 is not explicitly supported but we are trying to update our conference website and admin panel for ngAtlanta before the conf next month and cannot update due to this error. 

### Mention any other details that might be useful

An issue was opened on the dependency 2 months ago, might need help knocking it out. https://github.com/angular-material-extensions/password-strength/issues/240

**Comment by AnthonyNahas** [comment]
[@angular-material-extensions/password-strength](https://github.com/angular-material-extensions/password-strength) v6.0.0 is now supporting angular v9 and this ticket is now safe! 

I've just updated both libraries password strength as well as this library!

The new release of ngx-auth-firebase v4 is soon (feat: support of angular v9 + new animations and more)

cheers! 🍻 

and thank you
