### ISSUE TITLE
Custom login provider (firebase signInWithCustomToken)

### ISSUE THREAD

**Issue by kjetilhp** [AnthonyNahas/ngx-auth-firebaseui#429]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X ] feature request
```
### Desired functionality

Extend the login-provider section to be able to add a custom provider with an icon to be able to have a backend / third-party login with firebase signInWithCustomToken() - can be integrated with for example national login providers. Not sure if this have to be more than including content inside the provider tag and align it together with the other providers...

**Comment by AnthonyNahas** [comment]
@kjetilhp this is really a great feature for the library! However, I have like more than 20 projects in parallel and I will come into this in like 2021 ... I would love to get a PR for this ticket from you 🍻
