### ISSUE TITLE
Angular 9 compatibility

### ISSUE THREAD

**Issue by jeandat** [AnthonyNahas/ngx-auth-firebaseui#438]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality

Angular 9 was supposed to go out in november. We are in february and there are already 13 release candidates. It will probably goes out soon.

I think it would be good to be compatible with angular 9 as soon it is released notably because this library is popular.

I tried to upgrade dependencies to angular 9 but I'm facing a wall. 
It seems to me the build is not standard and using private api in order to compile angular code (ngc) as mentionned [here](https://github.com/angular/angular/issues/32352).

I don't have the background on this project to understand choices that have been made or even fully understand the current gulp build which seems complex.

I think it should be you Anthony that works on this. Do you think you could tackle this? As the person who made the actual build you might migrate easily.

Right now I had to add another private api in order to make ngc works but then it fails later on (modules are not found). I don't know much about all this and I don't think I will get anywhere. 

Here is a [fresh PR](https://github.com/AnthonyNahas/ngx-auth-firebaseui/pull/437) that initiates things. Anthony, could you take over please?

**Comment by andi-di** [comment]
+1 
I agree. I would be great if you update your Angular Version to 9, so we can make use of your compontent in updated projects.

**Comment by AnthonyNahas** [comment]
A new major version is gonna be soon released with support of angular 9 and my other bug fixes 🍻

**Comment by AnthonyNahas** [comment]
v9 compatibility is ready for release with apple as auth provider as feature ;)

**Comment by AnthonyNahas** [comment]
v4 is now release 

https://github.com/AnthonyNahas/ngx-auth-firebaseui/releases/tag/4.0.0
https://www.npmjs.com/package/ngx-auth-firebaseui

congrats all <3
