### ISSUE TITLE
Is it possible to to disable automatic logging in/authentication when a new user is registered with ngx-auth-firbaseui-register?

### ISSUE THREAD

**Issue by cunundrummer** [AnthonyNahas/ngx-auth-firebaseui#440]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
```

### OS and Version?

> macOs High Sierra 10.13.6

### Versions

Angular CLI: 8.3.20
Node: 10.16.3
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cdk                      8.2.3
@angular/cli                      8.3.20
@angular/fire                     5.3.0
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

### Repro steps

Simple steps to reproduce this bug.
Please include: commands run, packages added, related code changes.
A link to a sample repo would help too.

-Register a new user using the <ngx-auth-firebaseui-register> component.
```
<ngx-auth-firebaseui-register 
  (onError)="showError($event)"
  (onSuccess)="createUser($event)" 
  (onLoginRequested)="navToLogin()">
</ngx-auth-firebaseui-register>

```

```
createUser(user) {
    console.log('checking for event(user)s existence : ', user); // good - created.
    // create user Doc
   // !!! STOP AUTHENTICATION HERE !!!  <- what I hope is possible without having to call a 
   // signout() method
}

```

### Desired functionality

What would like to see implemented?

Using the <ngx-auth-firebaseui-register> component, when I finish registering a user, it auto-matically signs the user in.  I prefer the _option_ to  have the user go to the login component after successful registration.

What is the usecase?
Ensuring the user knows his/her password and (_later_) create the user document if the user is signed out (because doc doesn't/should not exist yet) -> firestore rules security.

**Comment by AnthonyNahas** [comment]
this is actually impossible! for this purpose, you should use stand alone firebase https call cloud functions to create a user!

Thank you
