### ISSUE TITLE
Need example to show authentication successful message

### ISSUE THREAD

**Issue by skdurvasula** [AnthonyNahas/ngx-auth-firebaseui#45]
Need an example to show authentication success message to user.

### OS and Version?

> Windows 7, 8 or 10. Linux (which distribution).macOS(Yosemite ? El Capitan? Sierra ?)

### Desired functionality
Need message to inform user about successful login to using firebase into my app.

**Comment by AnthonyNahas** [comment]
@skdurvasula this feature is already implemented... take a look at the example below:

![demo_v7 0_signin](https://user-images.githubusercontent.com/20149774/40323203-f8e0ef92-5d34-11e8-9855-f042fc53eca9.gif)

https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/master/src/module/services/auth-process.service.ts#L93
