### ISSUE TITLE
Version 4.0.0 not working on NodeJS 12

### ISSUE THREAD

**Issue by shady77** [AnthonyNahas/ngx-auth-firebaseui#453]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Arch Linux 
NodeJS 12.11.1

### Repro steps
1. yarn init
2. yarn add ngx-auth-firebaseui

### The log given by the failure
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error ngx-auth-firebaseui@4.0.0: The engine "node" is incompatible with this module. Expected version ">=10.13 <12". Got "12.11.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### Desired functionality
Package will install

**Comment by AnthonyNahas** [comment]
I will publish the patch in a few minutes

**Comment by AnthonyNahas** [comment]
can u please check [v4.0.1](https://www.npmjs.com/package/ngx-auth-firebaseui) ?

**Comment by shady77** [comment]
It is work. Thanks.

**Comment by AnthonyNahas** [comment]
awesome 🍻
