### ISSUE TITLE
Prevent specific fields from being updated when login via provider

### ISSUE THREAD

**Issue by asithade** [AnthonyNahas/ngx-auth-firebaseui#464]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
### Desired functionality
I can't seem to find any documentation on this, but is it possible to stop ngx-auth-firebaseui from updating certain fields on login via provider? 

I.e; we don't utilize the phone field and we're constantly getting console errors for permission denied as it is not a field we allow to be added/edited in our firestore rules. 

Also with photoURL, we allow the user to update their photoURL, but whenever the user logs in via a provider, it overwrites that field again with the providers photo. The image is also quite small in terms of resolution, so when we try to use a larger image, it is quite pixelated. 

I know there is the option of `enableFirestoreSync`, however this would stop the users other details from being synced like email, name etc...

**Comment by flyingcodelabs** [comment]
Hi
I disabled the enableFireStoreSync and created my own 'user' objects with fields I want using the $event emitted by onSucces()

**Comment by jorisgu** [comment]
Hi,
you can also create another database entry, let's say /profiles/{uid} and use it as a reference for your app. This way, /users/{uid} is only "managed" by ngx-auth-firebaseui and you can bind /users/{uid} to /profiles/{uid} with a cloud function, filtering the info you want to keep. 
Inspired from https://stackoverflow.com/questions/38648669/firebase-how-to-structure-public-private-user-data
