### ISSUE TITLE
Plans to support Angularfire v6

### ISSUE THREAD

**Issue by Benny739** [AnthonyNahas/ngx-auth-firebaseui#466]
Currently Angularfire v6 ist not supported, an error gets thrown right away. Are there any plans to support v6 in the near future? Looks like just the token imports have to be renamed.

**Comment by maikelnight1234** [comment]
Same here. This is the error (AngularFire v6.0.0-RC):
ERROR in ./node_modules/ngx-auth-firebaseui/__ivy_ngcc__/fesm2015/ngx-auth-firebaseui.js 3691:29-54
"export 'FirebaseNameOrConfigToken' was not found in '@angular/fire'
ERROR in ./node_modules/ngx-auth-firebaseui/__ivy_ngcc__/fesm2015/ngx-auth-firebaseui.js 3687:29-49
"export 'FirebaseOptionsToken' was not found in '@angular/fire'

**Comment by Jeffery-M** [comment]
I am having the same issues. 
`Angular CLI: 8.3.25
Node: 12.16.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cdk                      8.2.3
@angular/cli                      8.3.25
@angular/fire                     6.0.0-rc.1
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2`

Package dot JSON
`{
  "name": "auth-test-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/fire": "^6.0.0-rc.1",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "firebase": "^7.8.0",
    "ngx-auth-firebaseui": "^3.5.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.23",
    "@angular/cli": "~8.3.23",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "@angular-devkit/architect": "^0.900.0-0 || ^0.900.0",
    "firebase-tools": "^7.12.1",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1"
  }
}
`

**Comment by runette** [comment]
Same here. It is a bit of pain since it took be a good hour to work out what was going on

**Comment by AnthonyNahas** [comment]
This ticket has been not set to my roadmap

**Comment by AnthonyNahas** [comment]
I am happy to tell you that this ticket is now ready for the next release

**Comment by runette** [comment]
Thanks :)

**Comment by Temechon** [comment]
Hello @AnthonyNahas, when do you think release this next version ? Thank you for your work :)

**Comment by kevin192291** [comment]
Any update on when this will be released

**Comment by carnes11** [comment]
Hello @AnthonyNahas, when do you plan to release the new version?

**Comment by AnthonyNahas** [comment]
I will try to make it tonight in few hours

**Comment by AnthonyNahas** [comment]
[v4.1.0](https://www.npmjs.com/package/ngx-auth-firebaseui) is now live


enjoy 🍻

**Comment by Temechon** [comment]
Still an error when using the last version : 
```
main.ts:12 Error: Token InjectionToken angularfire2.app.nameOrConfig is missing a ɵprov definition.
    at injectableDefOrInjectorDefFactory (core.js:17029)
    at providerToFactory (core.js:17136)
    at providerToRecord (core.js:17083)
    at R3Injector.processProvider (core.js:16899)
    at core.js:16860
    at core.js:1391
    at Array.forEach (<anonymous>)
    at deepForEach (core.js:1391)
    at R3Injector.processInjectorType (core.js:16856)
    at core.js:16619
```
Everything works fine when I'm not using ngx-auth-firebaseui
