### ISSUE TITLE
Google provider not populating user information

### ISSUE THREAD

**Issue by josephsong** [AnthonyNahas/ngx-auth-firebaseui#467]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
Angular CLI: 9.0.1
Node: 12.7.0
OS: darwin x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cdk                      9.0.1
@angular/cli                      9.0.1
@angular/fire                     5.4.2
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

### Repro steps
- From a new codebase, set up Google as a provider, including `enableFirestoreSync: true`
- Register with Google
- Email, displayName, phoneNumber, photoUrl are all null for new user, though providerId and uid are present.

### The log given by the failure
No logs.

### Desired functionality
I would like to get the missing user information

### Mention any other details that might be useful
I can see https://www.googleapis.com/identitytoolkit/v3/relyingparty/getAccountInfo?key=XXX coming back with the appropriate data in the response
`{
  "kind": "identitytoolkit#GetAccountInfoResponse",
  "users": [
    {
      "localId": "google:XXX",
      "providerUserInfo": [
        {
          "providerId": "google.com",
          "displayName": "My Name",
          "photoUrl": "https://lh3.googleusercontent.com/a-/XXX",
          "federatedId": "XXX",
          "rawId": "XXX"
        }
      ],
      "validSince": "1471876055",
      "lastLoginAt": "1582486617324",
      "createdAt": "1450754436000",
      "lastRefreshAt": "2020-02-23T19:36:57.324Z"
    }
  ]
}` 

but when the system tries sync the data to Firebase, the POST body data is null:
`{
  "streamToken": "XXX",
  "writes": [
    {
      "update": {
        "name": "projects/sheepscoreapp/databases/(default)/documents/users/google:XXX",
        "fields": {
          "displayName": {
            "nullValue": "NULL_VALUE"
          },
          "email": {
            "nullValue": "NULL_VALUE"
          },
          "phoneNumber": {
            "nullValue": "NULL_VALUE"
          },
          "photoURL": {
            "nullValue": "NULL_VALUE"
          },
          "providerId": {
            "stringValue": "google.com"
          },
          "uid": {
            "stringValue": "google:XXX"
          }
        }
      },
      "updateMask": {
        "fieldPaths": [
          "displayName",
          "email",
          "phoneNumber",
          "photoURL",
          "providerId",
          "uid"
        ]
      }
    }
  ]
}`

**Comment by AnthonyNahas** [comment]
@josephsong thanks for contributing! 

I am not able to reproduce this issue! 

The data provided from google are as well synced to the firestore...

tested with more than 5 productive projects + demo app...
