### ISSUE TITLE
Angular9 and i18n compatibility

### ISSUE THREAD

**Issue by Kamil7S** [AnthonyNahas/ngx-auth-firebaseui#470]
I am no longer able to generate i18n translation source file after migration to angular9. It is very simple to reproduce this issue with freshly created angular9 project (see repro steps section). This issue doesn't occurs with angular in version 8.I will be glad if you can take a look on this, thanks!

### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```
### OS and Version?
Windows10 1909 x64

### Versions
Angular CLI: 9.0.4
Node: 12.16.1
OS: win32 x64

Package                     Version
------------------------------------------------------
@angular-devkit/architect    0.900.4 (cli-only)
@angular-devkit/core         9.0.4 (cli-only)
@angular-devkit/schematics   9.0.4 (cli-only)
@schematics/angular          9.0.4 (cli-only)
@schematics/update           0.900.4 (cli-only)

"@angular-material-extensions/password-strength": "6.0.0",
"@angular/animations": "9.0.4",
"@angular/cdk": "9.1.0",
"@angular/common": "9.0.4",
"@angular/compiler": "9.0.4",
"@angular/core": "9.0.4",
"@angular/fire": "5.4.2",
"@angular/flex-layout": "9.0.0-beta.29",
"@angular/forms": "9.0.4",
"@angular/localize": "9.0.4",
"@angular/material": "9.1.0",
"@angular/platform-browser": "9.0.4",
"@angular/platform-browser-dynamic": "9.0.4",
"@angular/router": "9.0.4",
"firebase": "7.9.3",
"ngx-auth-firebaseui": "4.0.1",
"rxjs": "6.5.4",
"tslib": "1.11.1",
"zone.js": "0.10.2"

### Repro steps

1. Create new angualr project(ng new)
2. Install material (add @angular/material)
3. Install  ngx-auth-firebaseui (ng add ngx-auth-firebaseui)
4. Install  @angular-material-extensions/password-strength (npm install --save @angular-material-extensions/password-strength)
5. Configure Firebase API Key (PUT_YOUR_FIREBASE_API_KEY_HERE)5) Setup angular i18n (ng add @angular/localize)
6. Create a translation source file (ng xi18n)

### The log given by the failure
`
ERROR in ngx-auth-firebaseui/ngx-auth-firebaseui.ts(141,48): Error during template compile of 'AppModule'
  Function expressions are not supported in decorators
    Consider changing the function expression into an exported function.
Can't resolve all parameters for LoggedInGuard in .../aaa/node_modules/ngx-auth-firebaseui/ngx-auth-firebaseui.d.ts: ([object Object], [object Object], ?).
Can't resolve all parameters for UserComponent in .../aaa/node_modules/ngx-auth-firebaseui/ngx-auth-firebaseui.d.ts: ([object Object], ?, ?, [object Object]).
Can't resolve all parameters for AuthComponent in .../aaa/node_modules/ngx-auth-firebaseui/ngx-auth-firebaseui.d.ts: ([object Object], [object Object], [object Object], ?, [object Object], [object Object], [object Object]).
Can't resolve all parameters for AuthProvidersComponent in .../aaa/node_modules/ngx-auth-firebaseui/ngx-auth-firebaseui.d.ts: (?).
Can't resolve all parameters for NgxAuthFirebaseuiLoginComponent in .../aaa/node_modules/ngx-auth-firebaseui/ngx-auth-firebaseui.d.ts: ([object Object], ?, [object Object]).
Can't resolve all parameters for NgxAuthFirebaseuiRegisterComponent in .../aaa/node_modules/ngx-auth-firebaseui/ngx-auth-firebaseui.d.ts: ([object Object], [object Object], ?).
Can't resolve all parameters for ɵi in .../aaa/node_modules/ngx-auth-firebaseui/ngx-auth-firebaseui.d.ts: (?, [object Object], [object Object]).
ngx-auth-firebaseui/ngx-auth-firebaseui.ts(141,48): Error during template compile of 'AppModule'
  Function expressions are not supported in decorators
    Consider changing the function expression into an exported function.
`

### Desired functionality
ng xi18n command should create messages.xlf file in the project's root directory.

**Comment by AnthonyNahas** [comment]
ng xi18n is not supported for this library!

The main issue is that some text are binded via the component and decorators ...

**Comment by AnthonyNahas** [comment]
@Kamil7S is this issue similar to #492 ?
