### ISSUE TITLE
Cannot run project using Angular 9

### ISSUE THREAD

**Issue by martinreus** [AnthonyNahas/ngx-auth-firebaseui#477]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Linux (Ubuntu mate 18.04)
### Versions
Angular CLI: 9.0.6
Node: 12.16.1
OS: linux x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@angular/cdk                      9.1.2
@angular/fire                     5.4.2
@angular/flex-layout              8.0.0-beta.27
@angular/material                 9.1.2
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

### Repro steps
- Create new project
-- with SCSS and routing
- Add Angular material library (`ng add @angular/material`)
- Add ngx-auth-firebase (`ng add ngx-auth-firebaseui`)
- Add @angular-material-extensions/password-strength since otherwise when running, compiler complains (`npm install @angular-material-extensions/password-strength`)
- Add firebase configuration in app.module.ts -> `NgxAuthFirebaseUIModule.forRoot(environment.firebase),
` 

### The log given by the failure
chunk {main} main.js, main.js.map (main) 2.06 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 709 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 180 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2020-03-14T19:04:53.874Z - Hash: 03d8bb170a4a7b7126f4 - Time: 13966ms

ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts:9:19 - error TS2305: Module '"../../../../common/common"' has no exported member 'ɵNgClassImpl'.

9 import { NgClass, ɵNgClassImpl, ɵNgClassR2Impl } from '@angular/common';
                    ~~~~~~~~~~~~
node_modules/@angular/flex-layout/extended/typings/class/class.d.ts:9:33 - error TS2305: Module '"../../../../common/common"' has no exported member 'ɵNgClassR2Impl'.

9 import { NgClass, ɵNgClassImpl, ɵNgClassR2Impl } from '@angular/common';
                                  ~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts:9:19 - error TS2305: Module '"../../../../common/common"' has no exported member 'ɵNgStyleImpl'.

9 import { NgStyle, ɵNgStyleImpl, ɵNgStyleR2Impl } from '@angular/common';
                    ~~~~~~~~~~~~
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts:9:33 - error TS2305: Module '"../../../../common/common"' has no exported member 'ɵNgStyleR2Impl'.

9 import { NgStyle, ɵNgStyleImpl, ɵNgStyleR2Impl } from '@angular/common';
                                  ~~~~~~~~~~~~~~

### Desired functionality
That it compiles and runs

**Comment by AYGTX** [comment]
npm i @angular/flex-layout

**Comment by AnthonyNahas** [comment]
@martinreus are u still facing some problems ?
