### ISSUE TITLE
Unexpected confirm email dialog

### ISSUE THREAD

**Issue by n84ck** [AnthonyNahas/ngx-auth-firebaseui#478]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

> Windows 10

### Versions
`
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.2
@angular/cli                      9.0.5
@angular/fire                     5.4.2
@angular/flex-layout              9.0.0-beta.29
@angular/google-maps              9.1.2
@angular/material                 9.1.2
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
`

### Repro steps

1. Include <ngx-auth-firebaseui [guestEnabled]="true" [providers]="[ providers.Google]"></ngx-auth-firebaseui>
2. Try to login with google provider

### Desired functionality

I want to see the user profile like in examples

### Mention any other details that might be useful

- According of the <ngx-auth-firebaseui-avatar></ngx-auth-firebaseui-avatar> component, the user is not verificated
- Email was not sent

![2020-03-16_11h12_28](https://user-images.githubusercontent.com/43924278/76746000-150a7f00-6777-11ea-8aec-75c138653030.png)

**Comment by n84ck** [comment]
The root cause of the bug is allowing multiple accounts with the same email address.

![image](https://user-images.githubusercontent.com/43924278/76832812-61fb5d80-682a-11ea-9ee8-1c3fca638481.png)

**Comment by AnthonyNahas** [comment]
Since sending the email is provided directly from firebase, this issue has nothing to do with the library! 

Tip: did you check the spam directory ?

If you still have additional questions, please consider to post them here
