### ISSUE TITLE
Entry point 'ngx-auth-firebaseui' contains deep imports into rxjs/internal/operators and rxjs/internal/Subscription

### ISSUE THREAD

**Issue by tiloio** [AnthonyNahas/ngx-auth-firebaseui#488]
### Bug Report
```
- [x] bug report 
- [ ] feature request
```

### OS and Version?
Windows 10

### Versions
Node: 10.15.3
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/fire                     5.4.2
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0
firebase                            7.13.1
**ngx-auth-firebaseui         4.0.2**

### Repro steps
Setup project with angular 9, run `ng serve` or `ng build`

### The log given by the failure
`ng serve`
Warning: Entry point 'ngx-auth-firebaseui' contains deep imports into '../node_modules/rxjs/internal/operators', '../node_modules/rxjs/internal/Subscription'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point 'ngx-auth-firebaseui' contains deep imports into '../node_modules/rxjs/internal/operators', ../node_modules/rxjs/internal/Subscription'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

`ng build`
Warning: Entry point 'ngx-auth-firebaseui' contains deep imports into '../node_modules/rxjs/internal/operators', '../node_modules/rxjs/internal/Subscription'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by mukaschultze** [comment]
PR #513
