### ISSUE TITLE
Instruction for how to test, build and submit PR

### ISSUE THREAD

**Issue by jackie-d** [AnthonyNahas/ngx-auth-firebaseui#502]
Hi, thanks for the great work here!

In order to help community to develop this amazing libraries, it would be nice to be able to consult a guide on how to test, build and eventually submit PR.

Specifically because this repo contains a lot of stuff but during development and runtime we would usually just need the transpiled content of the projects sub-directory, and not everybody may be use to follow this workflow.

Testing:
- is there a way to isolate the runtime code?

**Building: (most important)**
- how to compile. mount in a project using npm / manually

PRs
- minimum requirements

I would take for granted basic github and dev ops procedures knowledge and concentrate con specificities.

Thanks,
Jackie

**Comment by AnthonyNahas** [comment]
Hi @jackie-d  

## Testing 

since the build migration from gulp to angular cli, the test are not working anymore and are outdated... 

I should find some time to fix and improve the test workflow 

I used `jest` to test the library, but as I've already said, jest is not working currently within the project 


## build

to build the library just run `npm run build` inside the project src code

1. `cd projects/ngx-auth-firebaseui/ `
2. `npm run build`

## Minimum requirements

what do you mean with that ?

**Comment by jackie-d** [comment]
Hi, thank you for the answer.

Ok, i gonna give a test on the building and let you.

So, once I made my edits and built, I'll be able to mount the builded folder directly on my project by:

```
cd <my_project>
npm install <my_local_ngx-auth-firebaseui_repo>
```

For the specifications, I understand there aren't any. Thanks.

**Comment by jackie-d** [comment]
Hi, I think I did it.

but for completeness:

required node 10 or node 12

```
npm install
cd projects/ngx-auth-firebaseui/
npm run build
```

**Comment by AnthonyNahas** [comment]
Can I close this ticket ?

**Comment by jackie-d** [comment]
Yes, it will be good to have specific instruction about this module if they are found beyond usual npm module development procedures and if you would need to you can easily close the issue. Thank you for your great work and I'm sure we're all waiting for a Ionic support or dedicated version to be distributed on!

Have a good day, I'll stay updated.

**Comment by DavidTheProgrammer** [comment]
@AnthonyNahas Please leave it open, I'll write up some docs and submit the PR sometime this week. Just managed to get a local version working and I think it'll help a few people who'd like to contribute but don't know how to.
