### ISSUE TITLE
ToS and Privacy Policy not working on ngx-auth-firebaseui-register

### ISSUE THREAD

**Issue by asithade** [AnthonyNahas/ngx-auth-firebaseui#508]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
4.0.4

### Repro steps
Use the following: 
```
<ngx-auth-firebaseui-register tosUrl="/terms-of-service" privacyPolicyUrl="/privacy" (onError)="failedRegister($event)"
  (onSuccess)="successRegister()">
</ngx-auth-firebaseui-register>
```

When you click "Create Account", it does not have the popup telling you to accept the terms or privacy policy. Looking at the code for this component, the ToS and Privacy Policy section is commented out.

### Desired functionality
Should display the popup asking the user to accept the tos and/or privacy policy

**Comment by jackie-d** [comment]
I'm waiting for this and meanwhile patched my code like your PR...
