### ISSUE TITLE
Getting Error when Installing ngx-auth-UI

### ISSUE THREAD

**Issue by Idaryss** [AnthonyNahas/ngx-auth-firebaseui#517]
Hi Team, 

I have an issue while installing it 

When I setup everything following the setup guide I am getting 

ERROR in ./node_modules/ngx-auth-firebaseui/__ivy_ngcc__/fesm2015/ngx-auth-firebaseui.js 3692:29-54
"export 'FirebaseNameOrConfigToken' was not found in '@angular/fire'
ERROR in ./node_modules/ngx-auth-firebaseui/__ivy_ngcc__/fesm2015/ngx-auth-firebaseui.js 3688:29-49
"export 'FirebaseOptionsToken' was not found in '@angular/fire'

The only thing I did not write is  '  () => 'your_app_name_factory','  under my firebase config as I dont know what should I put instead of 'your_app_name_factory'.

thank your clarification and thank you for your work.

**Comment by Blunderchips** [comment]
@Idaryss What version of `@angular/fire` are you using?

If you are using version 6 try version 5 (I am using 5.4.2). I don't believe this library has been updated to be compatible with the latest version of Angular Fire.

**Comment by Blunderchips** [comment]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### OS and Version?
> Pop!_OS 19.10 (linux)

### Versions
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.1
Node: 13.9.0
OS: linux x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.1
@angular/fire                     5.4.2
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.6.5
webpack                           4.42.0

```

### Repro steps

Install the library into a project using `@angular/fire` version 6.


### The log given by the failure
```
ERROR in ./node_modules/ngx-auth-firebaseui/ivy_ngcc/fesm2015/ngx-auth-firebaseui.js 3692:29-54
"export 'FirebaseNameOrConfigToken' was not found in '@angular/fire'
ERROR in ./node_modules/ngx-auth-firebaseui/ivy_ngcc/fesm2015/ngx-auth-firebaseui.js 3688:29-49
"export 'FirebaseOptionsToken' was not found in '@angular/fire'
```

### Mention any other details that might be useful
See my above comment.

**Comment by kevin192291** [comment]
This was resolved with the latest release

**Comment by Idaryss** [comment]
Hi Kevin, 
When was release the latest release ? 

Thank you

**Comment by AnthonyNahas** [comment]
v.4.1.0 has been released yesterday 🍻
