### ISSUE TITLE
Feature: update password or create new password

### ISSUE THREAD

**Issue by AnthonyNahas** [AnthonyNahas/ngx-auth-firebaseui#53]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions
angular v5
ngx-auth-firebaseui v7

### Desired functionality
an authenticated user should be able to update or create a new password for his account

### Mention any other details that might be useful
the new user should be validated with [ngx-material-password-strength](https://www.npmjs.com/package/ngx-material-password-strength)

**Comment by Blunderchips** [comment]
@AnthonyNahas has there been any progress on this issue?
