### ISSUE TITLE
firebaseui i18n assets override i18n assets from the original app

### ISSUE THREAD

**Issue by rangzen** [AnthonyNahas/ngx-auth-firebaseui#554]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Linux Ubuntu

### Versions

Angular CLI: 9.1.4
Node: 12.16.2
OS: linux x64

Angular: 9.1.4
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

### Repro steps

If you already have i18n assets and follow the part 7 of https://ngx-auth-firebaseui.firebaseapp.com/getting-started to add assets to angular. The i18n assets of ngx-auth-firebaseui override all mine so I lost all translations in the app.

### Desired functionality

Is there a better way to do that?

**Comment by AnthonyNahas** [comment]
are you sure? maybe you did something wrong ?

**Comment by francovp** [comment]
I think I have this exact same Issue before when using [ngx-translate/core](https://github.com/ngx-translate/core) with this library, so instead of define my i18n strings in the "assets/i18n/" folder I've defined them in a "assets/custom/i18n/" or on a service :/

**Comment by rangzen** [comment]
The 

> I think I have this exact same Issue before when using [ngx-translate/core](https://github.com/ngx-translate/core) with this library, so instead of define my i18n strings in the "assets/i18n/" folder I've defined them in a "assets/custom/i18n/" or on a service :/

I did the same but you need an extra loader wich know how to do multiple loading.

**Comment by rangzen** [comment]
Actually, I extract i18n keys, the ngx-auth-firebaseui are extracted with mine... I let them empty and the multiloader, thanksfully, drop the empty ones and make a fusion. But I need to keep mine in an other directory that i18n.

**Comment by FRANK-AND-FREE** [comment]
I observed the same problem with translation files being overwritten.
Maybe this library can ease the pain for you, too:
https://github.com/denniske/ngx-translate-multi-http-loader
