### ISSUE TITLE
ngx-auth-firebaseui-providers  -  is not a row when width is reduced

### ISSUE THREAD

**Issue by pauljohnleonard** [AnthonyNahas/ngx-auth-firebaseui#555]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### The log given by the failure

N/A

**Comment by AnthonyNahas** [comment]
which width do you mean? The host div or screen width ?

**Comment by pauljohnleonard** [comment]
It seems to depend on the screen width.   Here is a demo.  Just resize the window and see if you think this is how it should behave.

https://stackblitz.com/edit/firebase-login-examp?file=src/app/app.component.html
