### ISSUE TITLE
Angular Server Side rendering - broken?

### ISSUE THREAD

**Issue by martinreus** [AnthonyNahas/ngx-auth-firebaseui#560]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
5.3.0-55-generic #49-Ubuntu SMP Thu May 21 12:47:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Versions
```
Angular CLI: 9.1.7
Node: 12.17.0
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.4
@angular/cli                      9.1.7
@angular/fire                     5.4.2
@angular/flex-layout              9.0.0-beta.31
@angular/material                 9.2.4
@ngtools/webpack                  9.1.7
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
    
```

### Repro steps
- Create new project, add ssr support, add ngx-auth-firebase dependencies
  ```
  ng new ui
  cd ui
  ng add @angular/material
  ng add @nguniversal/express-engine --clientProject ui
  ng add @angular-material-extensions/password-strength
  ng add ngx-auth-firebaseui
  ```
- Add correct credentials for 
  `     NgxAuthFirebaseUIModule.forRoot(PUT_YOUR_FIREBASE_API_KEY_HERE),`
- Replace `app.component.html` with
```
<ngx-auth-firebaseui></ngx-auth-firebaseui> 
```
- Fix `Error: ENOENT: no such file or directory, open 'google/protobuf/api.proto'` error, applying this fix:
  https://stackoverflow.com/questions/61225733/error-enoent-no-such-file-or-directory-open-google-protobuf-api-proto

- Run  `npm run build:ssr && npm run serve:ssr`, enter website at localhost:4000

### The log given by the failure
```
Warning: Flex Layout loaded on the server without FlexLayoutServerModule
TypeError: _firebaseAppFactory(...).firestore is not a function
    at /home/martin/sources/projects/platafoda/ui/dist/ui/server/main.js:1:1955111
    at ZoneDelegate.invoke (/home/martin/sources/projects/platafoda/ui/dist/ui/server/main.js:1:1864371)
    at Zone.run (/home/martin/sources/projects/platafoda/ui/dist/ui/server/main.js:1:1856785)
    at NgZone.runOutsideAngular (/home/martin/sources/projects/platafoda/ui/dist/ui/server/main.js:1:3157995)
    at new firestore_AngularFirestore (/home/martin/sources/projects/platafoda/ui/dist/ui/server/main.js:1:1955025)
    at Object.AngularFirestore_Factory [as factory] (/home/martin/sources/projects/platafoda/ui/dist/ui/server/main.js:1:1956430)
    at R3Injector.hydrate (/home/martin/sources/projects/platafoda/ui/dist/ui/server/main.js:1:2931026)
    at R3Injector.get (/home/martin/sources/projects/platafoda/ui/dist/ui/server/main.js:1:2927756)
    at injectInjectorOnly (/home/martin/sources/projects/platafoda/ui/dist/ui/server/main.js:1:2812831)
    at Module.ɵɵinject (/home/martin/sources/projects/platafoda/ui/dist/ui/server/main.js:1:2812997)
```

### Desired functionality
That it works :)

**Comment by AnthonyNahas** [comment]
@martinreus this issue has nothing to do with the library! You need to import `FlexLayoutServerModule ` into the correct place --> server module

**Comment by martinreus** [comment]
@AnthonyNahas I feel sorry that you got offended. First of all, the error is not that FlexLayoutServerModule was not imported, this was just a warning (and frankly I shouldn't have left it in the error message). I figured out what was going out, and it is an error because firebase is not being compiled into the server version of my app. For now, adding it to the external libraries in my angular.json file kind of solved the issue, but this is not something I want to do, since then I would have to copy the whole node_modules folder to my docker container (which currently weighs in at about 600Mb).

I was kind of sad with this kind of response that came for you because I was really hoping to use your library and also try to fix this issue, because this is what open source is supposed to be; unfortunately simply closing the issue in this way makes me wonder if I should rely on this library in the future..

**Comment by AnthonyNahas** [comment]
@martinreus I am sorry as well, I was just checking the tickets during the break and I thought that this one is an easy one... 

I will try to investigate the problem and I promise to help you to get that fixed 🍻
