### ISSUE TITLE
Need Role Based Authentication

### ISSUE THREAD

**Issue by XLR8-07** [AnthonyNahas/ngx-auth-firebaseui#562]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### OS and Version?

Windows 10

### Versions

Angular CLI: 9.1.7

### Desired functionality

Need Role Based Authentication with ngx-auth. The default User collection and authentication doesnt have roles to customize user access.

**Comment by AnthonyNahas** [comment]
Do you have any idea how to proceed?
