### ISSUE TITLE
Message after E-mail login in chrome.

### ISSUE THREAD

**Issue by doczoidberg** [AnthonyNahas/ngx-auth-firebaseui#567]
I get a message after E-mail login in chrome (and only in chrome) that I should check and change my password because it was leaked. Why do I get this message and what can I do?

![image](https://user-images.githubusercontent.com/1972209/87359102-75fc6500-c567-11ea-9eb5-4bbbeec370bf.png)

this message isn't shown in incognito mode.

**Comment by hellseyfer** [comment]
That's not related to this, but there's a way they can check If some web you had account with your email has suffered a security leak

**Comment by AnthonyNahas** [comment]
@doczoidberg sorry but this issue is not related to the library 

thank you
