### ISSUE TITLE
Server Side Rendering: Module not found: Error: Can't resolve 'google-auth-library'

### ISSUE THREAD

**Issue by dileepyelleti** [AnthonyNahas/ngx-auth-firebaseui#568]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

macOS(Mojave)

### Versions

Angular CLI: 9.1.11
Node: 12.1.0
OS: darwin x64

Angular: 9.1.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.11
@angular-devkit/build-angular     0.901.11
@angular-devkit/build-optimizer   0.901.11
@angular-devkit/build-webpack     0.901.11
@angular-devkit/core              9.1.11
@angular-devkit/schematics        9.1.11
@angular/cdk                      9.2.4
@angular/cli                      9.1.11
@angular/fire                     5.4.2
@angular/flex-layout              9.0.0-beta.31
@angular/material                 9.2.4
@ngtools/webpack                  9.1.11
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.11
@schematics/update                0.901.11
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.42.0

### Repro steps

- ng add @angular/material
- ng add ngx-auth-firebaseui
- npm run dev:ssr

### The log given by the failure

ERROR in ./node_modules/@grpc/grpc-js/build/src/channel-credentials.js
Module not found: Error: Can't resolve 'google-auth-library' in '/Users/dyelleti/Desktop/test/delete/test2/newtest/node_modules/@grpc/grpc-js/build/src'
this.debug is not a function

### Desired functionality

SSR should work properly

**Comment by guanghui1987** [comment]
+1

**Comment by AnthonyNahas** [comment]
I am sorry but this issue is not related to the library 

I will close for the moment this ticket 

please consider reopening this if you have an accurate issue regarding ngx-auth-firebaseui
