### ISSUE TITLE
 The provider icon is not displayed

### ISSUE THREAD

**Issue by kenji-iiii** [AnthonyNahas/ngx-auth-firebaseui#570]
The provider icon is not displayed

"ngx-auth-firebaseui": "^4.4.0",
`
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.0.4
Node: 14.5.0
OS: darwin x64

Angular: 10.0.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.1000.4
@angular-devkit/build-optimizer    0.1000.4
@angular-devkit/build-webpack      0.1000.4
@angular-devkit/core               9.0.7
@angular-devkit/schematics         10.0.4
@angular/cdk                       10.1.1
@angular/cli                       10.0.4
@angular/fire                      6.0.2
@angular/flex-layout               10.0.0-beta.32
@angular/material                  10.1.1
@angular/material-moment-adapter   10.1.1
@ngtools/webpack                   10.0.4
@nguniversal/builders              9.1.1
@nguniversal/common                9.1.1
@nguniversal/express-engine        9.1.1
@schematics/angular                10.0.4
@schematics/update                 0.1000.4
rxjs                               6.5.5
typescript                         3.9.7
webpack                            4.43.0`
![image](https://user-images.githubusercontent.com/13961330/88914979-6f2b5d00-d29e-11ea-9306-93633c511a31.png)

**Comment by AnthonyNahas** [comment]
This is because you didn't import the assets

https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/master/docs/INSTRUCTIONS.md

```
{
          "glob": "**/*",
          "input": "node_modules/ngx-auth-firebaseui/assets/",
          "output": "./assets/"
}
```

**Comment by tabuckner** [comment]
@AnthonyNahas i'm running in to this same issue, however i _do_ have the `angular.json` file updated. 

I'm not seeing where the reporter confirmed this was the issue, but maybe you guys talked offline. 

Any tips?

**Comment by tabuckner** [comment]
Just fixed my issue. I didn't take into account the `"sourceRoot": "apps/idea-incubator/src",` property.
