### ISSUE TITLE
Question: How do I get a user from ngx-auth-firebaseui and use it in my app in other components?

### ISSUE THREAD

**Issue by hepaestus** [AnthonyNahas/ngx-auth-firebaseui#573]
#353 # Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request / question
```

### OS and Version?
Linux Ubuntu

### Versions
Angular CLI: 8.3.29
Node: 14.0.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.5
@angular-devkit/build-angular     0.803.29
@angular-devkit/build-optimizer   0.803.29
@angular-devkit/build-webpack     0.803.29
@angular-devkit/core              8.3.29
@angular-devkit/schematics        8.3.29
@angular/cdk                      8.2.3
@angular/cli                      8.3.29
@angular/fire                     6.0.2
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.29
@schematics/angular               8.3.29
@schematics/update                0.803.29
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

### Desired functionality / QUESTION
How can I get the current logged in user from the ngx-auth-firebaseui element and pass it into my other components?
Thanks,
P.

**Comment by AnthonyNahas** [comment]
```typescript
constructor(
    public afa: AngularFireAuth,)

this.afa.user.subscribe((user: firebase.User | null) => 

if(user) => that means the user is logged in


```


then you can pass the user obj to you target component
