### ISSUE TITLE
Schematic on Angular 10 has unmet peer dependencies and doesn't succeed

### ISSUE THREAD

**Issue by ammaarpatel99** [AnthonyNahas/ngx-auth-firebaseui#576]
# Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
macOS Catalina

### Versions
Output from ng --version:
Angular CLI: 10.0.7
Node: 12.18.3
OS: darwin x64

Angular: 10.0.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cli                      10.0.7
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

### Repro steps
Create new angular project using cli:
`ng new my-app`
It doesn't seem to matter what options you pick (i.e. routing etc)
`ng add @angular/material` (optional - I tried it without this line as well) - created theme and installed animations
`ng add ngx-auth-firebaseui@latest`
I also tried this in my own project which has pwa, routing etc. It produced the same result.

### The log given by the failure
Package has unmet peer dependencies. Adding the package may not succeed.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/project'
Require stack:
- /Users/ammaar/my-app/node_modules/ngx-auth-firebaseui/schematics/helpers/angular/project.js
- /Users/ammaar/my-app/node_modules/ngx-auth-firebaseui/schematics/helpers/angular/index.js
- /Users/ammaar/my-app/node_modules/ngx-auth-firebaseui/schematics/helpers/index.js
- /Users/ammaar/my-app/node_modules/ngx-auth-firebaseui/schematics/ng-add/index.js
- /Users/ammaar/my-app/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/ammaar/my-app/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/ammaar/my-app/node_modules/@angular/cli/utilities/json-schema.js
- /Users/ammaar/my-app/node_modules/@angular/cli/models/command-runner.js
- /Users/ammaar/my-app/node_modules/@angular/cli/lib/cli/index.js
- /Users/ammaar/.nvm/versions/node/v12.18.3/lib/node_modules/@angular/cli/lib/init.js
- /Users/ammaar/.nvm/versions/node/v12.18.3/lib/node_modules/@angular/cli/bin/ng
See "/private/var/folders/54/88xyfny94y7fwch8p8zb_n9c0000gn/T/ng-AlAwNr/angular-errors.log" for further details.

### Desired functionality
Complete the functionality that the schematic is suppose to.

**Comment by JuanJTorres11** [comment]
I have the same issue, did you find any solution?

**Comment by AnthonyNahas** [comment]
@JuanJTorres11 I will check your solution

**Comment by AnthonyNahas** [comment]
[v.5.0.0](https://www.npmjs.com/package/ngx-auth-firebaseui) has been just released
