### ISSUE TITLE
 'ngx-auth-firebaseui' is not a known element

### ISSUE THREAD

**Issue by JasonGoemaat** [AnthonyNahas/ngx-auth-firebaseui#577]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [*] feature request
```

### OS and Version?

Doesn't matter

### Versions

Doesn't matter

### Repro steps

Try to add to a project

### The log given by the failure

 'ngx-auth-firebaseui' is not a known element

### Desired functionality

Maybe a simple tutorial showing how to add it to your project, including adding angular material and the other two packages required, and how to add it to your app module so the component works...

**Comment by AnthonyNahas** [comment]
Can you post your code here, please? 

- import
- html usage

**Comment by AnthonyNahas** [comment]
Maybe a simple tutorial showing how to add it to your project, including adding angular material and the other two packages required, and how to add it to your app module so the component works...


--> this is a great youtube video
https://www.youtube.com/watch?v=KpfJCEvpS9g&t=159s&ab_channel=JsWiz
