### ISSUE TITLE
ngx-auth-firebaseui-avatar doesn't run onSignOut when clicking "SignOut" from Profile

### ISSUE THREAD

**Issue by magoarcano** [AnthonyNahas/ngx-auth-firebaseui#580]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
MacOs Catalina 10.5.5

### Versions

@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@angular/fire                     6.0.2
@angular/flex-layout              9.0.0-beta.31
@angular/material                 9.2.4
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

### Repro steps

Create a `logout()` function and a Component with
```
<ngx-auth-firebaseui-avatar
    (onSignOut)="logout()"
  >
  </ngx-auth-firebaseui-avatar>
```

1. Sign in
2. Click on Avatar
3. Click on Profile
4. Click on SignOut

### Desired functionality

It would run my `logout()`. I use it to redirect user to the Sign In page.
onSignOut works if I sign out from the avatar button, but not when I click on Sign Out in Profile.

### Mention any other details that might be useful

It would also be ok if I can hide the Sign out button from the profile (same like hiding 'Delete Account' with canDeleteAccount) but only for the button in the Profile screen

**Comment by AnthonyNahas** [comment]
I will check that
