### ISSUE TITLE
Still under development?

### ISSUE THREAD

**Issue by Blunderchips** [AnthonyNahas/ngx-auth-firebaseui#585]
Is this project still under active development and if so is there project roadmap/plan publicly available with what features are planned?

**Comment by ceckles** [comment]
my guess is no..

**Comment by AnthonyNahas** [comment]
Hi mates 

sorry for the late reply. 

I've been busy the past few months, I will try to put some more time in this library again. 

I would love to have someone on board with me as an active maintainer to keep this library in progress. 

I promise --> a new major release is planned

**Comment by Blunderchips** [comment]
@AnthonyNahas do we know what is planned for the next major release?

**Comment by AnthonyNahas** [comment]
sorry for the last response! I am very busy with my projects

I've just release v7 supporting angular v14

for more updated please consider opening PRs
