### ISSUE TITLE
Register Tab - Email pre-filled programmatically

### ISSUE THREAD

**Issue by santoshmondal** [AnthonyNahas/ngx-auth-firebaseui#586]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
I need a feature in register tab; Where Name and Email input fields are pre-filled programmatically

### Mention any other details that might be useful
This is use-case is, where we Invite member to register in application vial inbox email, And once the user click on the Join Link in the Email, the Name and Email field is pre-filled.

**Comment by AnthonyNahas** [comment]
Do you mean via url or via `input` ?

**Comment by santoshmondal** [comment]
i mean via url

**Comment by asithade** [comment]
Wouldn't just be able to target this via javascript?
