### ISSUE TITLE
Dialog width changes when pressing edit in user profile

### ISSUE THREAD

**Issue by hamza1311** [AnthonyNahas/ngx-auth-firebaseui#588]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Arch Linux.  
Kernal: `5.8.14-arch1-1`

### Versions
```
Angular CLI: 10.1.7
Node: 12.19.0
OS: linux x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.900.7
@angular-devkit/build-angular   0.1000.8
@angular-devkit/core            10.0.8
@angular-devkit/schematics      10.1.7
@angular/cdk                    10.2.5
@angular/cli                    10.1.7
@angular/fire                   6.0.3
@angular/flex-layout            10.0.0-beta.32
@angular/material               10.2.5
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.5.5
typescript                      3.9.7
```

`ngx-auth-firebaseui` version: `4.4.0`

### Repro steps
- use `ngx-auth-firebaseui-avatar` component
- click on user avatar icon
- go to profile
- press edit in profile
- notice how dialog width changes for no reason

### The log given by the failure
UI bug - No stacktrace

### Desired functionality
The width to not change and stay consistent across edit and non-edit state

#### Screenshots

![image](https://user-images.githubusercontent.com/47357913/96277758-1ee6b000-0fee-11eb-8561-b70b5426b4a1.png)

![image](https://user-images.githubusercontent.com/47357913/96277776-260dbe00-0fee-11eb-876f-db01706372f9.png)

These two should have the same width

#### Source
Repository: https://github.com/hamza1311/dear-diary-web
Hosted at: https://deardiary-app.web.app/

**Comment by AnthonyNahas** [comment]
@hamza1311  I would appreciate a PR for this ticket

**Comment by hamza1311** [comment]
@AnthonyNahas I'm sorry, I don't have the time to work on this PR. Neither am I familiar with the code base so I can't do this.
