### ISSUE TITLE
onAccountDeleted does not fire

### ISSUE THREAD

**Issue by DragosIlies** [AnthonyNahas/ngx-auth-firebaseui#589]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

> Windows 10 

### Versions

Angular CLI: 10.1.7
Node: 12.18.1
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.900.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cdk                    10.2.5
@angular/cli                    10.1.7
@angular/fire                   6.0.3
@angular/flex-layout            10.0.0-beta.32
@angular/material               10.2.5
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.5.5
typescript                      4.0.3

### Mention any other details that might be useful

In my dashboard component when I am trying to fire the onAcccountDeleted event nothing happens.

`<ngx-auth-firebaseui-user (onAccountDeleted)='deleteUserData()'></ngx-auth-firebaseui-user>`

In the component.ts 
`  deleteUserData(){
    console.log("Trigger")
  }
  `

It works with other events like 'onSignOut'.

**Comment by AnthonyNahas** [comment]
I will check that
