### ISSUE TITLE
Welcome snackbar on login?

### ISSUE THREAD

**Issue by grapevinegizmos** [AnthonyNahas/ngx-auth-firebaseui#591]
Quick question... Does ngx-auth-firebaseui surface a mat-snackbar on successful login which says "Hello [user full name]!" at the bottom of the page?

I didn't think so, but in this app I am working on I keep getting this snackbar even though I have searched the code base for it, I can't find either snackbar definition or even the word "Hello", or for that matter a string which ends with "!" 

Just checking to make sure it isn't coming ngx-auth-firebaseui.

Sorry for wasting your time if the answer is no, I'm just a little flummoxed.

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by Blunderchips** [comment]
Is it possible to turn the snackbar off?

**Comment by grapevinegizmos** [comment]
Not sure if you are asking me or Anthony -- I haven't tried to turn it off, mainly I'm just trying to figure out where its coming from.

**Comment by mcroker** [comment]
Easy to turn off in the UI config object when you set it up in app.module

```
@NgModule({
   ...
   imports: [
    ...
    NgxAuthFirebaseUIModule.forRoot(environment.firebase, undefined, {
        toastMessageOnAuthSuccess: false
    })
  ]
})
```

**Comment by AnthonyNahas** [comment]
@mcroker  thanks for answering! your answer is correct
