### ISSUE TITLE
ngx-auth-firebaseui-register does not support guest mode

### ISSUE THREAD

**Issue by stevenhatfield** [AnthonyNahas/ngx-auth-firebaseui#592]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### OS and Version?

All

### Versions

Angular CLI: 10.0.6
Node: 14.8.0
OS: darwin x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1000.6
@angular-devkit/core         10.0.6
@angular-devkit/schematics   10.0.6
@schematics/angular          10.0.6
@schematics/update           0.1000.6
rxjs                         6.5.5

### Repro steps

Create a page with the ngx-auth-firebaseui-register tag and you will see that guest mode is not supported like it is with the ngx-auth-firebaseui tag.

### Desired functionality

I would like to be able to specify the guestEnabled option in when using ngx-auth-firebaseui-register.

**Comment by AnthonyNahas** [comment]
I will take that in consideration for the the next release

**Comment by AnthonyNahas** [comment]
it's actually need it only in the sign in component
