### ISSUE TITLE
Is this component supposed to work with Angular v 10?

### ISSUE THREAD

**Issue by grapevinegizmos** [AnthonyNahas/ngx-auth-firebaseui#593]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by grapevinegizmos** [comment]
I get a very long list of confusing configuration errors when I try to install on top of Angular 10 and the end result is that the component isn't recognized.

Is this component (which I have used and works very nicely) still being maintained?

**Comment by schmorrison** [comment]
Current peer dependancies as listed in the README:

```
    "@angular/core": "^9.x",
    "@angular/animations": "^9.x",
    "@angular/cdk": "^9.x",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.x",
    "@angular/material": "^9.x",
    "@angular/fire": "5.4.x",
    "firebase": "7.x",
```

**Comment by flyingcodelabs** [comment]
I had it running on 10 but, now with 11 it's a whole mess... feel like there is no real maintenance and looking for another solution

**Comment by longcharmroeun** [comment]
@flyingcodelabs  => #595

**Comment by AnthonyNahas** [comment]
@grapevinegizmos the library works with angular v10 but still not compatible with the latest version of firebase. 

I am working now on a major release.

Can you post your deps and logs to help you ?

**Comment by AnthonyNahas** [comment]
[v.5.0.0](https://www.npmjs.com/package/ngx-auth-firebaseui) has been just released
