### ISSUE TITLE
feat: add support for `firebase` v8.0.0

### ISSUE THREAD

**Issue by gkalpak** [AnthonyNahas/ngx-auth-firebaseui#594]
FYI, the latest version of `ngx-auth-firebaseui` (currently v4.4.0) is not compatible with `firebase` v8.0.0. FWIW, we run into this on our [ngcc-validation][1] repo (see example [failing CI run][2]).

(In case it helps, the PR that added support for `firebase` v8.0.0 to `@angular/fire` is angular/angularfire#2624.)

[1]: https://github.com/angular/ngcc-validation
[2]: https://circleci.com/gh/angular/ngcc-validation/18631

**Comment by DavidTheProgrammer** [comment]
Unfortunately the Author says he no longer plans to maintain this application as he's overwhelmed. 

https://github.com/AnthonyNahas/ngx-auth-firebaseui/pull/572

We might need to create a separate package that we can maintain as a community. I also haven't had my PR merged for about a month now and the Author is currently looking for someone to maintain this package.

**Comment by AnthonyNahas** [comment]
I will continue developing this library in 01.2021

**Comment by AnthonyNahas** [comment]
[v5.0.0](https://www.npmjs.com/package/ngx-auth-firebaseui) has been just released
