### ISSUE TITLE
The target entry-point "ngx-auth-firebaseui" has missing dependencies:

### ISSUE THREAD

**Issue by tdkehoe** [AnthonyNahas/ngx-auth-firebaseui#598]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Catalina 10.15.7

### Versions
Angular CLI: 11.0.2
Node: 14.14.0
OS: darwin x64

### Repro steps
ng serve -o

### The log given by the failure
Error: The target entry-point "ngx-auth-firebaseui" has missing dependencies:
 - @angular-material-extensions/password-strength
 - @angular/flex-layout

### Desired functionality
It should open Angular without bugs.

### Mention any other details that might be useful
See previous issue.

**Comment by longcharmroeun** [comment]
you need to install that dependencies
`npm i @angular-material-extensions/password-strength`
`npm i @angular/flex-layout`

**Comment by AnthonyNahas** [comment]
@longcharmroeun  thanks for answering. 

If you are still facing the same problem please consider reopening this ticket

cheers 🍻
