### ISSUE TITLE
Cannot find module '@schematics/angular/utility/json-utils'

### ISSUE THREAD

**Issue by shansurat** [AnthonyNahas/ngx-auth-firebaseui#612]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

> Solus 4.2

### Versions
Angular CLI: 11.1.3
Node: 14.15.4
OS: linux x64

Angular: 11.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.3
@angular-devkit/build-angular   0.1101.3
@angular-devkit/core            11.1.3
@angular-devkit/schematics      11.1.3
@angular/cli                    11.1.3
@angular/fire                   6.1.4
@schematics/angular             11.1.3
@schematics/update              0.1101.3
rxjs                            6.6.3
typescript                      4.1.3

### Repro steps

ng add ngx-auth-firebaseui

### The log given by the failure
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/json-utils'
Require stack:
- /mnt/Cassie/Projects/starwall/node_modules/ngx-auth-firebaseui/schematics/helpers/angular/json-utils.js
- /mnt/Cassie/Projects/starwall/node_modules/ngx-auth-firebaseui/schematics/helpers/angular/index.js
- /mnt/Cassie/Projects/starwall/node_modules/ngx-auth-firebaseui/schematics/helpers/index.js
- /mnt/Cassie/Projects/starwall/node_modules/ngx-auth-firebaseui/schematics/ng-add/index.js
- /mnt/Cassie/Projects/starwall/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /mnt/Cassie/Projects/starwall/node_modules/@angular-devkit/schematics/tools/index.js
- /mnt/Cassie/Projects/starwall/node_modules/@angular/cli/utilities/json-schema.js
- /mnt/Cassie/Projects/starwall/node_modules/@angular/cli/models/command-runner.js
- /mnt/Cassie/Projects/starwall/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/share/.config/yarn/global/node_modules/@angular/cli/lib/init.js
- /usr/local/share/.config/yarn/global/node_modules/@angular/cli/bin/ng
See "/tmp/ng-7hw8bN/angular-errors.log" for further details.

### Desired functionality
Should work.

**Comment by ammaarpatel99** [comment]
I've got the same error

**Comment by ammaarpatel99** [comment]
I'm pretty sure this is a duplicate of #597

**Comment by shansurat** [comment]
Definitely. Thank you for the heads up! I'll close it now. :D
