### ISSUE TITLE
How to build forked repo?

### ISSUE THREAD

**Issue by sachi097** [AnthonyNahas/ngx-auth-firebaseui#617]
I have forked ngx-auth-firebase and created private repository and added phone authentication feature. Since, my code changes do not support i18n texts and also do not work for phone numbers outside India (+91) I cannot create a PR. 
I have tested it locally and everything seem to work fine. I am faced with couple of issues mentioned below.

1) How do I build/recompile these code changes (private repository project structure is exactly same to project structure of ngx-auth-firebaseui)?
2) Post step - 1, How do I install these changes on other project as dependency/node package?

@AnthonyNahas  Could you please help me with these. Since, I am very new to node_modules/packages.

Currently, I tried executing **npm install** inside ngx-auth-firebaseui/projects/ngx-auth-firebaseui/ but I am getting an error

> ../../node_modules/.bin/ng build ngx-firebaseui-auth --prod
>
> '..' is not recognized as an internal or external command,
operable program or batch file.

If you do not want to answer it over here please write to me at nieesachi.097@gmail.com

PS: I would like to install the changes directly via github for example: 
> npm install --save  git+https://[access-token]:x-oauth-basic@github.com/username/repo_name

**Comment by AnthonyNahas** [comment]
Hi, 

 run 

- npm install 


build the library 

- npm run build:lib

start the demo app 

- npm start
