### ISSUE TITLE
Recommended Peer dependencies not working for Angular 10. 

### ISSUE THREAD

**Issue by kuvaibhav** [AnthonyNahas/ngx-auth-firebaseui#625]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

> Windows 10. 

### Versions
Output from: `ng --version 10.1.6`, .
Otherwise, output from: `node --version v12.16.2` , `npm --version` and Angular version.

### Repro steps
Added following peer dependencies as recommended from `ngx-auth-firebase` readme file. 
"firebase": "^7.x",
    "ngx-auth-firebaseui": "^4.4.0",
    "@angular/fire": "^5.4.0",
    "@angular/flex-layout": "^9.0.0-beta.29"

This is the error/warning:
Warning:
\node_modules\@angular\fire\__ivy_ngcc__\es2015\firebase.app.module.js depends on 'firebase/app'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

### The log given by the failure
Warning:
auth-firebaseui\__ivy_ngcc__\fesm2015\ngx-auth-firebaseui.js depends on '@firebase/auth'. CommonJS or AMD dependencies can cause optimization bailouts.

### Desired functionality
What would like to see implemented?
I expected the recommended peer dependencies to have worked flawlessly on Angular 10. Instead noticed Angular v10 to be working fine with ngx-auth-firebaseui and peer dependencies for Angular v11. Requesting you to verify this and update the readme file or provide correct version of dependencies for angular version 10. 
What is the usecase?
Not applicable. 

### Mention any other details that might be useful
https://github.com/armory-uci/vital/pull/5/files/96b90682b3fd80c8e96ee02de3bd92adb50550c0

**Comment by AnthonyNahas** [comment]
please use the latest version of the library
