### ISSUE TITLE
ngx-auth-firebaseui-login after login display name is reset in firestore even when set

### ISSUE THREAD

**Issue by BlueDragon709** [AnthonyNahas/ngx-auth-firebaseui#629]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Linux (Manjaro)

### Versions

Angular CLI: 11.2.9
Node: 14.17.0
OS: linux x64

Angular: 11.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.9
@angular-devkit/build-angular   0.1102.9
@angular-devkit/core            11.2.9
@angular-devkit/schematics      11.2.9
@angular/cdk                    11.2.9
@angular/cli                    11.2.9
@angular/fire                   6.1.4
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.2.9
@schematics/angular             11.2.9
@schematics/update              0.1102.9
rxjs                            6.6.7
typescript                      4.1.5

### Repro steps

in the module:
```
NgxAuthFirebaseUIModule.forRoot(environment.firebase, () => 'project', {
      enableEmailVerification: false,
      guardProtectedRoutesUntilEmailIsVerified: false,
      toastMessageOnAuthSuccess: false,
      toastMessageOnAuthError: false,
      authGuardFallbackURL: '/auth/sign-in',
      authGuardLoggedInURL: 'project'
    })
```
    
in de page:
```
<ngx-auth-firebaseui-login [providers]="[providers.EmailAndPassword, providers.Google]" [resetPasswordEnabled]=false (onCreateAccountRequested)="goToRegisterPage()" (onSuccess)="this.router.navigate(['/project'])"></ngx-auth-firebaseui-login>
```

if the user logs in using email and password, the displayname is reset to null in firestore.
But when the user logs in using Google the displayName is not reset.
    

### The log given by the failure

Not applicable

### Desired functionality

That the users do not lose the displayName on log 

### Mention any other details that might be useful

Not applicable

**Comment by AnthonyNahas** [comment]
do you still facing any issue?
please do not hesitate to reopen this ticket
