### ISSUE TITLE
Failed to compile entry-point ngx-auth-firebaseui (`es2015` as esm2015) due to compilation errors:

### ISSUE THREAD

**Issue by chriscurnow** [AnthonyNahas/ngx-auth-firebaseui#633]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
MacOS BigSur 11.6

### Versions
Angular CLI: 12.1.0
Node: 14.17.1
Package Manager: npm 7.20.0
OS: darwin x64

Angular: 12.2.11
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.11
@angular-devkit/build-angular   12.2.11
@angular-devkit/core            12.2.11
@angular-devkit/schematics      12.2.11
@angular/fire                   7.1.1
@schematics/angular             12.2.11
rxjs                            6.6.7
typescript                      4.3.5

### Repro steps
1. Install `ngx-auth-firebaseui` as per instructions
2. npm run build

### The log given by the failure
Error: Failed to compile entry-point ngx-auth-firebaseui (`es2015` as esm2015) due to compilation errors:
node_modules/ngx-auth-firebaseui/fesm2015/ngx-auth-firebaseui.js:1634:26 - error NG1010: Value at position 22 in the NgModule.imports of NgxAuthFirebaseUIModule is not a reference
  Value could not be determined statically.

1634                 imports: [
                              ~
1635                     CommonModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ... 
1664                     AngularFirestoreModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1665                 ],
     ~~~~~~~~~~~~~~~~~

  node_modules/ngx-auth-firebaseui/fesm2015/ngx-auth-firebaseui.js:1663:21
    1663                     AngularFireAuthModule,
                             ~~~~~~~~~~~~~~~~~~~~~
    Unknown reference.

Compiling ngx-auth-firebaseui : es2015 as esm2015

An error occurred during the build:
Error: Failed to compile entry-point ngx-auth-firebaseui (`es2015` as esm2015) due to compilation errors:
node_modules/ngx-auth-firebaseui/fesm2015/ngx-auth-firebaseui.js:1634:26 - error NG1010: Value at position 22 in the NgModule.imports of NgxAuthFirebaseUIModule is not a reference
  Value could not be determined statically.

1634                 imports: [
                              ~
1635                     CommonModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ... 
1664                     AngularFirestoreModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1665                 ],
     ~~~~~~~~~~~~~~~~~

  node_modules/ngx-auth-firebaseui/fesm2015/ngx-auth-firebaseui.js:1663:21
    1663                     AngularFireAuthModule,
                             ~~~~~~~~~~~~~~~~~~~~~
    Unknown reference.

    at /Users/chriscurnow/Projects/4cast/workspace/node_modules/@angular/compiler-cli/ngcc/src/execution/tasks/completion.js:57:19
    at /Users/chriscurnow/Projects/4cast/workspace/node_modules/@angular/compiler-cli/ngcc/src/execution/tasks/completion.js:31:13
    at /Users/chriscurnow/Projects/4cast/workspace/node_modules/@angular/compiler-cli/ngcc/src/execution/create_compile_function.js:69:21
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (/Users/chriscurnow/Projects/4cast/workspace/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:36:17)
    at /Users/chriscurnow/Projects/4cast/workspace/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:59
    at SyncLocker.lock (/Users/chriscurnow/Projects/4cast/workspace/node_modules/@angular/compiler-cli/ngcc/src/locking/sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (/Users/chriscurnow/Projects/4cast/workspace/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:27)
    at Object.mainNgcc (/Users/chriscurnow/Projects/4cast/workspace/node_modules/@angular/compiler-cli/ngcc/src/main.js:74:25)
    at Object.process (/Users/chriscurnow/Projects/4cast/workspace/node_modules/@angular/compiler-cli/ngcc/index.js:29:23)
    at NgccProcessor.processModule (/Users/chriscurnow/Projects/4cast/workspace/node_modules/@ngtools/webpack/src/ngcc_processor.js:175:16)
    at /Users/chriscurnow/Projects/4cast/workspace/node_modules/@ngtools/webpack/src/ivy/host.js:146:18
    at /Users/chriscurnow/Projects/4cast/workspace/node_modules/@ngtools/webpack/src/ivy/host.js:76:24
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (/Users/chriscurnow/Projects/4cast/workspace/node_modules/@ngtools/webpack/src/ivy/host.js:74:32)
    at /Users/chriscurnow/Projects/4cast/workspace/node_modules/@ngtools/webpack/src/ivy/host.js:75:55
    at Array.map (<anonymous>)
Failed to compile entry-point ngx-auth-firebaseui (`es2015` as esm2015) due to compilation errors:
node_modules/ngx-auth-firebaseui/fesm2015/ngx-auth-firebaseui.js:1634:26 - error NG1010: Value at position 22 in the NgModule.imports of NgxAuthFirebaseUIModule is not a reference
  Value could not be determined statically.

1634                 imports: [
                              ~
1635                     CommonModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ... 
1664                     AngularFirestoreModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1665                 ],
     ~~~~~~~~~~~~~~~~~

  node_modules/ngx-auth-firebaseui/fesm2015/ngx-auth-firebaseui.js:1663:21
    1663                     AngularFireAuthModule,
                             ~~~~~~~~~~~~~~~~~~~~~
    Unknown reference.

### Desired functionality
It should build

### Mention any other details that might be useful
I am running this inside an nx workspace

**Comment by ShimshonMarketing66** [comment]
did you find any solution ?

**Comment by dominiknovicky** [comment]
> Oops, sorry. Didn't read the bit about @angular/fire . I'm guessing that's the source of my problem.

Have you found a solution to fix it? I have the same error during compiling...
