### ISSUE TITLE
Gulp and Demo problems

### ISSUE THREAD

**Issue by chriscurnow** [AnthonyNahas/ngx-auth-firebaseui#635]
Before I start the report I have to say this is an amazing package. You have done an enormous amount of work here and it will save a ot of time when I get it running.

### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
MacOS BigSur 11.3

### Versions
Angular CLI: 11.1.1
Node: 14.17.1
OS: darwin x64

Angular: 11.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.1
@angular/cli                    11.1.1
@angular/fire                   6.1.4
@angular/flex-layout            11.0.0-beta.33
@nguniversal/builders           11.1.0
@nguniversal/express-engine     11.1.0
@schematics/angular             11.2.6
@schematics/update              0.1101.1
ng-packagr                      11.1.2
rxjs                            6.6.3
typescript                      4.0.5

### Repro steps
% git clone https://github.com/AnthonyNahas/ngx-auth-firebaseui.git
% cd ngx-auth-firebaseui ==> not included in instructions but presume is necessary
% gulp setup
  [17:15:24] No gulpfile found <== ????
==> See if we can continue anyway
% cd demo <== THERE IS NO demo folder

==> Can't really go any further???

### The log given by the failure
No log

### Desired functionality
I'd just like to run the demo

**Comment by AnthonyNahas** [comment]
please pull the latest version

thank you
