### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by chriscurnow** [AnthonyNahas/ngx-auth-firebaseui#636]
Anthony has obviously put a lot of work into this project but not much is happening.

There was a very minor update 5 days ago.

Before that a bit happened 6 months ago.

I could well understand maintaining something like this could become a real pain.

It would just be good to know what the plans are for the future.

Should we be investing time trying to make this work?

**Comment by Blunderchips** [comment]
Hello @chriscurnow, there this is from Oct 2020: [Still under development?](https://github.com/AnthonyNahas/ngx-auth-firebaseui/issues/585)

**Comment by chriscurnow** [comment]
I have created PR #638 which seems to work if anyone is interested.
