### ISSUE TITLE
Environments: config typo that breaks build

### ISSUE THREAD

**Issue by ChadESmith42** [AnthonyNahas/ngx-auth-firebaseui#642]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Mac OS Big Sur, 11.6

### Versions
Angular CLI: 13.0.2
Node: 14.15.0
Package Manager: npm 6.14.8
OS: darwin x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core, fire
... flex-layout, forms, language-service, material
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            13.0.2 (cli-only)
@angular-devkit/schematics      13.0.2 (cli-only)
@angular/cli                    13.0.2 (cli-only)
@nguniversal/builders           <error>
@nguniversal/express-engine     <error>
@schematics/angular             13.0.2 (cli-only)
ng-packagr                      <error>
rxjs                            6.6.7 (cli-only)
typescript                      <error>

### Repro steps
Cloned `master` to local machine. Ran `npm install` to install packages. Ran `ng serve`. 

### The log given by the failure

```
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |      Size
vendor.js             | vendor        |   6.44 MB
main.js               | main          | 495.59 kB
polyfills.js          | polyfills     | 339.11 kB
styles.css, styles.js | styles        | 292.91 kB
scripts.js            | scripts       | 128.63 kB
runtime.js            | runtime       |   7.44 kB

                      | Initial Total |   7.67 MB

Build at: 2021-11-16T20:23:44.558Z - Hash: 086de6e5bf344c26 - Time: 10197ms

Error: src/app/app.module.ts:25:40 - error TS2339: Property 'firebaseConfig' does not exist on type '{ production: boolean; config: { apiKey: string; authDomain: string; projectId: string; storageBucket: string; messagingSenderId: string; appId: string; measurementId: string; }; }'.

25 export const firebaseKey = environment.firebaseConfig;
                                          ~~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
```

### Desired functionality
Repo build and run on local ng server.

### Mention any other details that might be useful

I did a [quick PR](https://github.com/AnthonyNahas/ngx-auth-firebaseui/pull/641) to fix this issue.

**Comment by AnthonyNahas** [comment]
fixed
