### ISSUE TITLE
Value at position 22 in the NgModule.imports of NgxAuthFirebaseUIModule is not a reference

### ISSUE THREAD

**Issue by dominiknovicky** [AnthonyNahas/ngx-auth-firebaseui#643]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
> Windows 10

### Versions
Angular CLI: 13.1.1
Node: 14.18.2
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.1
@angular-devkit/build-angular   13.1.1
@angular-devkit/core            13.1.1
@angular-devkit/schematics      13.1.1
@angular/cli                    13.1.1
@angular/fire                   7.2.0
@angular/flex-layout            13.0.0-beta.36
@schematics/angular             13.1.1
rxjs                            6.6.7
typescript                      4.5.3

### Repro steps
I am going step-by-step but always getting the same error during compiling an application.
(https://ngx-auth-firebaseui.firebaseapp.com/getting-started)

### The log given by the failure
(node:6668) UnhandledPromiseRejectionWarning: Error: Failed to compile entry-point ngx-auth-firebaseui (`es2015` as esm2015) due to compilation errors:
node_modules/ngx-auth-firebaseui/fesm2015/ngx-auth-firebaseui.js:1634:26 - error NG1010: Value at position 22 in the NgModule.imports of NgxAuthFirebaseUIModule is not a reference
  Value could not be determined statically.

1634                 imports: [
                              ~
1635                     CommonModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ...
1664                     AngularFirestoreModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1665                 ],
     ~~~~~~~~~~~~~~~~~

  node_modules/ngx-auth-firebaseui/fesm2015/ngx-auth-firebaseui.js:1663:21
    1663                     AngularFireAuthModule,
                             ~~~~~~~~~~~~~~~~~~~~~
    Unknown reference.

    at file:///C:/Users/dominik.novicky/Documents/Angular/doIt/node_modules/@angular/compiler-cli/bundles/chunk-UAY4RXGC.js:1630:11
    at file:///C:/Users/dominik.novicky/Documents/Angular/doIt/node_modules/@angular/compiler-cli/bundles/chunk-UAY4RXGC.js:1614:5
    at file:///C:/Users/dominik.novicky/Documents/Angular/doIt/node_modules/@angular/compiler-cli/bundles/chunk-BXWQHEIB.js:4616:9
    at SingleProcessExecutorSync.doExecute (file:///C:/Users/dominik.novicky/Documents/Angular/doIt/node_modules/@angular/compiler-cli/bundles/chunk-UAY4RXGC.js:1581:7)
    at file:///C:/Users/dominik.novicky/Documents/Angular/doIt/node_modules/@angular/compiler-cli/bundles/chunk-UAY4RXGC.js:1594:35
    at SyncLocker.lock (file:///C:/Users/dominik.novicky/Documents/Angular/doIt/node_modules/@angular/compiler-cli/bundles/chunk-UAY4RXGC.js:1765:14)
    at SingleProcessExecutorSync.execute (file:///C:/Users/dominik.novicky/Documents/Angular/doIt/node_modules/@angular/compiler-cli/bundles/chunk-UAY4RXGC.js:1594:19)
    at mainNgcc (file:///C:/Users/dominik.novicky/Documents/Angular/doIt/node_modules/@angular/compiler-cli/bundles/chunk-UAY4RXGC.js:2105:19)
    at Module.process (file:///C:/Users/dominik.novicky/Documents/Angular/doIt/node_modules/@angular/compiler-cli/bundles/ngcc/index.js:34:10)
    at NgccProcessor.processModule (C:\Users\dominik.novicky\Documents\Angular\doIt\node_modules\@ngtools\webpack\src\ngcc_processor.js:175:27)
    at C:\Users\dominik.novicky\Documents\Angular\doIt\node_modules\@ngtools\webpack\src\ivy\host.js:76:24
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (C:\Users\dominik.novicky\Documents\Angular\doIt\node_modules\@ngtools\webpack\src\ivy\host.js:74:32)
    at actualResolveModuleNamesWorker (C:\Users\dominik.novicky\Documents\Angular\doIt\node_modules\typescript\lib\typescript.js:113784:153)
    at resolveModuleNamesWorker (C:\Users\dominik.novicky\Documents\Angular\doIt\node_modules\typescript\lib\typescript.js:114053:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero 
exit code.

**Comment by asithade** [comment]
Same issue with Angular 12

**Comment by ryanismert** [comment]
Same with Angular 12. 

Note that the most recent release does not seem to be the Angular 13 build. That PR is merged into master, but it looks like the CircleCI pipeline encountered an error.  I'm not sure if that is causing some of my issues - it's entirely possible I have mismatched npm versions somewhere...

I'll try a local build of master and try linking that for my application. If that helps, I'll report back here.

**Comment by Auha** [comment]
@ryanismert Have you had any success? I tried, but had a lot of issues to the point I had to change to another project.

**Comment by mirateOfficial** [comment]
So this is not fixable?

**Comment by AnthonyNahas** [comment]
which version of the lib are you using ?

**Comment by mirateOfficial** [comment]
latest everything

**Comment by AnthonyNahas** [comment]
is someone interested to maintain this library! 

ngx-auth-firebaseui became big and I have really really too much to do since I am dedicated new startup at the moment! 

I need an experience developer to help me with that, unless I will come to the tickets late! 

I appreciate if someone can help <3

**Comment by AnthonyNahas** [comment]
https://www.npmjs.com/package/ngx-auth-firebaseui

v6 is now online

please may you test it?

**Comment by AnthonyNahas** [comment]
please update the lib to the latest version v7 supporting angular v14
