### ISSUE TITLE
Building Schematics is broken after Angular 13 upgrade

### ISSUE THREAD

**Issue by AndriiNeverov** [AnthonyNahas/ngx-auth-firebaseui#644]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Big Sur

### Versions

 ../../node_modules/.bin/ng --version

Angular CLI: 13.0.1
Node: 14.18.1
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 13.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1 (cli-only)
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      12.2.13
@angular/cli                    13.0.1
@angular/fire                   7.1.1
@angular/flex-layout            11.0.0-beta.33
@nguniversal/builders           11.1.0
@nguniversal/express-engine     11.1.0
@schematics/angular             12.2.13
ng-packagr                      13.0.3
rxjs                            6.6.3
typescript                      4.4.4

### Repro steps

git clone https://github.com/AnthonyNahas/ngx-auth-firebaseui
cd ngx-auth-firebaseui
npm install
cd projects/ngx-auth-firebaseui/
npm run build:schematics

```
../../node_modules/.bin/tsc -p tsconfig.schematics.json

schematics/helpers/angular/ast-utils.ts:4:3 - error TS2305: Module '"@schematics/angular/utility/ast-utils"' has no exported member 'addEntryComponentToModule'.

4   addEntryComponentToModule as originalAddEntryComponentToModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by vladimir-barsuchenko** [comment]
Can't run npm i ngx-auth-firebaseui even from cloned repository

```
Could not resolve dependency:
npm ERR! peer @angular/cdk@"^12.x" from @angular-material-extensions/password-strength@9.0.0
npm ERR! node_modules/@angular-material-extensions/password-strength
npm ERR!   @angular-material-extensions/password-strength@"^9.0.0" from the root project
npm ERR!   peer @angular-material-extensions/password-strength@"^9.0.0" from ngx-auth-firebaseui@6.0.0
npm ERR!   node_modules/ngx-auth-firebaseui
npm ERR!     ngx-auth-firebaseui@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by AndriiNeverov** [comment]
@vladimir-barsuchenko 

```
nvm use v14.18.1

git clone https://github.com/AnthonyNahas/ngx-auth-firebaseui
cd ngx-auth-firebaseui
npm install
cd projects/ngx-auth-firebaseui/
npm run build:schematics
```

works for me as is. Anyways, https://www.npmjs.com/package/ngx-auth-firebaseui v6 is now released.
