### ISSUE TITLE
Update @angular-material-extensions/password-strength to ^10.0.0

### ISSUE THREAD

**Issue by Mikael-Eliasson** [AnthonyNahas/ngx-auth-firebaseui#647]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Ubuntu 20.04

### Versions

Angular CLI: 13.2.2
Node: 16.13.2
Package Manager: npm 8.1.2
OS: linux x64

Angular: 13.2.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.2
@angular-devkit/build-angular   13.2.2
@angular-devkit/core            13.2.2
@angular-devkit/schematics      13.2.2
@angular/cli                    13.2.2
@angular/fire                   7.2.0
@schematics/angular             13.2.2
rxjs                            7.5.2
typescript                      4.5.5

### Repro steps

ng add ngx-auth-firebaseui

### The log given by the failure

 Using package manager: npm
✔ Found compatible package version: ngx-auth-firebaseui@6.0.0.
✔ Package information loaded.

The package ngx-auth-firebaseui@6.0.0 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: logmate-service@0.0.0
npm ERR! Found: @angular/cdk@13.2.4
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^13.2.1" from the root project
npm ERR!   peer @angular/cdk@"^13.0.0" from ngx-auth-firebaseui@6.0.0
npm ERR!   node_modules/ngx-auth-firebaseui
npm ERR!     ngx-auth-firebaseui@"6.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^12.x" from @angular-material-extensions/password-strength@9.0.0
npm ERR! node_modules/@angular-material-extensions/password-strength
npm ERR!   peer @angular-material-extensions/password-strength@"^9.0.0" from ngx-auth-firebaseui@6.0.0
npm ERR!   node_modules/ngx-auth-firebaseui
npm ERR!     ngx-auth-firebaseui@"6.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

### Desired functionality

Be able to install ngx-auth-firebaseui

### Mention any other details that might be useful

Seems that angular-material-extensions/password-strength needs to be updated to ^10.0.0. That version seems to be compatible with cdk@^13.0.0.

**Comment by yaroslavdraha** [comment]
Any updates? I cannot update my project to angular 13 due to that issue :(

**Comment by AnthonyNahas** [comment]
please you the latest version of this lib --> v14
and angular-material-extensions/password-strength v11

thank you
