### ISSUE TITLE
"Sign in" and "Register" tab buttons are not visible while using the Dark Theme

### ISSUE THREAD

**Issue by AndriiNeverov** [AnthonyNahas/ngx-auth-firebaseui#649]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions

All

### Repro steps

Force Material Dark Theme

![Screen Shot 2022-03-20 at 7 05 15 PM](https://user-images.githubusercontent.com/30669047/159196885-314bb478-efb1-4f26-8ada-74257cc0d1f6.png)

### Desired functionality

The Login Screen should properly support the Dark Theme.

**Comment by AnthonyNahas** [comment]
please consider using ngdeep to change lib css classes
