### ISSUE TITLE
Flex-layout dependency breaks install process

### ISSUE THREAD

**Issue by KariNarhi** [AnthonyNahas/ngx-auth-firebaseui#663]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
macOS Monterey 12.6

### Versions
Angular CLI: 14.2.6
Node: 16.17.1
Package Manager: npm 8.19.2 
OS: darwin x64

Angular: 14.2.7
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.6
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.3.7
@angular/cdk                    14.2.5
@angular/cli                    14.2.6
@angular/fire                   7.4.1
@angular/flex-layout            14.0.0-beta.41
@angular/material               14.2.5
@schematics/angular             13.3.7
rxjs                            7.5.7
typescript                      4.6.4

### Repro steps
Try to install ngx-auth-firebaseui with `ng add ngx-auth-firebaseui` or with `npm i ngx-auth-firebaseui`

### The log given by the failure
ℹ Using package manager: npm
✔ Found compatible package version: ngx-auth-firebaseui@7.0.0.
✔ Package information loaded.

The package ngx-auth-firebaseui@7.0.0 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tecmvp@1.0.0
npm ERR! Found: @angular/flex-layout@14.0.0-beta.41
npm ERR! node_modules/@angular/flex-layout
npm ERR!   @angular/flex-layout@"^14.0.0-beta.41" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/flex-layout@"^14.x" from ngx-auth-firebaseui@7.0.0
npm ERR! node_modules/ngx-auth-firebaseui
npm ERR!   ngx-auth-firebaseui@"7.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Desired functionality
Install should happen with no errors.

### Mention any other details that might be useful
Tried to get past this by installing older versions of @angular/flex-layout but no success.

ngx-auth-firebaseui seems to look for `^14.x` and I do have the latest `^14.0.0-beta.41` version installed, but it just keeps giving the same error.

**Comment by alonsogamez** [comment]
I'm using Windows 11 with the same packages versions and I'm having the same problem. Any thoughts?

**Comment by monstergaming800** [comment]
I am also having the same problem. 

Complete log:

0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@8.19.2
2 info using node@v16.18.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 5ms
6 timing config:load:builtin Completed in 6ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\mahsa\Desktop\git\ma922\firebase-app-3-url-shortner-2\url-shortner-2\.npmrc Completed in 0ms
10 timing config:load:project Completed in 12ms
11 timing config:load:file:C:\Users\mahsa\.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\mahsa\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 32ms
19 timing npm:load:configload Completed in 32ms
20 timing npm:load:mkdirpcache Completed in 2ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm install ngx-auth-firebaseui@7.0.0
23 verbose argv "install" "ngx-auth-firebaseui@7.0.0"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 7ms
26 timing npm:load:display Completed in 8ms
27 verbose logfile logs-max:10 dir:C:\Users\mahsa\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\mahsa\AppData\Local\npm-cache\_logs\2022-11-02T11_31_12_184Z-debug-0.log
29 timing npm:load:logFile Completed in 21ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 1ms
32 timing npm:load Completed in 71ms
33 timing arborist:ctor Completed in 2ms
34 silly logfile start cleaning logs, removing 4 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 1635ms
37 timing idealTree:userRequests Completed in 9ms
38 silly idealTree buildDeps
39 silly fetch manifest @angular-material-extensions/password-strength@^11.0.1
40 timing arborist:ctor Completed in 0ms
41 http fetch GET 200 https://registry.npmjs.org/@angular-material-extensions%2fpassword-strength 3289ms (cache revalidated)
42 silly fetch manifest @angular/cdk@^14.2.6
43 http fetch GET 200 https://registry.npmjs.org/@angular%2fcdk 126ms (cache revalidated)
44 silly fetch manifest @angular/common@^14.2.0
45 http fetch GET 200 https://registry.npmjs.org/@angular%2fcommon 130ms (cache revalidated)
46 silly fetch manifest @angular/core@^14.2.0
47 http fetch GET 200 https://registry.npmjs.org/@angular%2fcore 121ms (cache revalidated)
48 silly fetch manifest rxjs@~7.5.0
49 http fetch GET 200 https://registry.npmjs.org/rxjs 95ms (cache revalidated)
50 silly fetch manifest zone.js@~0.11.4
51 http fetch GET 200 https://registry.npmjs.org/zone.js 118ms (cache revalidated)
52 silly fetch manifest @angular/forms@^14.2.0
53 http fetch GET 200 https://registry.npmjs.org/@angular%2fforms 85ms (cache revalidated)
54 silly fetch manifest @angular/platform-browser@^14.2.0
55 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser 98ms (cache revalidated)
56 silly fetch manifest @angular/animations@^14.2.0
57 http fetch GET 200 https://registry.npmjs.org/@angular%2fanimations 126ms (cache revalidated)
58 silly fetch manifest @angular/material@^14.2.6
59 http fetch GET 200 https://registry.npmjs.org/@angular%2fmaterial 381ms (cache revalidated)
60 silly fetch manifest @angular/flex-layout@^14.0.0-beta.41
61 http fetch GET 200 https://registry.npmjs.org/@angular%2fflex-layout 328ms (cache revalidated)
62 silly fetch manifest ngx-auth-firebaseui@7.0.0
63 http fetch GET 200 https://registry.npmjs.org/ngx-auth-firebaseui 952ms (cache revalidated)
64 silly fetch manifest @angular/fire@^7.4.1
65 http fetch GET 200 https://registry.npmjs.org/@angular%2ffire 339ms (cache revalidated)
66 silly fetch manifest @angular/platform-browser-dynamic@^14.2.0
67 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser-dynamic 137ms (cache revalidated)
68 silly fetch manifest @angular/compiler@^14.2.0
69 http fetch GET 200 https://registry.npmjs.org/@angular%2fcompiler 96ms (cache revalidated)
70 silly fetch manifest firebase-tools@^9.9.0 || ^10.0.0 || ^11.0.0
71 http fetch GET 200 https://registry.npmjs.org/firebase-tools 195ms (cache revalidated)
72 silly fetch manifest @angular/flex-layout@^14.x
73 timing idealTree Completed in 8488ms
74 timing command:install Completed in 8508ms
75 verbose stack Error: unable to resolve dependency tree
75 verbose stack     at Arborist.[failPeerConflict] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1381:25)
75 verbose stack     at Arborist.[loadPeerSet] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1347:34)
75 verbose stack     at async Arborist.[buildDepStep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:930:11)
75 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:211:7)
75 verbose stack     at async Promise.all (index 1)
75 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:153:5)
75 verbose stack     at async Install.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\install.js:145:5)
75 verbose stack     at async module.exports (C:\Program Files\nodejs\node_modules\npm\lib\cli.js:78:5)
76 verbose cwd C:\Users\mahsa\Desktop\git\ma922\firebase-app-3-url-shortner-2\url-shortner-2
77 verbose Windows_NT 10.0.19044
78 verbose node v16.18.0
79 verbose npm  v8.19.2
80 error code ERESOLVE
81 error ERESOLVE unable to resolve dependency tree
82 error
83 error While resolving: url-shortner-2@0.0.0
83 error Found: @angular/flex-layout@14.0.0-beta.41
83 error node_modules/@angular/flex-layout
83 error   @angular/flex-layout@"^14.0.0-beta.41" from the root project
83 error
83 error Could not resolve dependency:
83 error peer @angular/flex-layout@"^14.x" from ngx-auth-firebaseui@7.0.0
83 error node_modules/ngx-auth-firebaseui
83 error   ngx-auth-firebaseui@"7.0.0" from the root project
83 error
83 error Fix the upstream dependency conflict, or retry
83 error this command with --force, or --legacy-peer-deps
83 error to accept an incorrect (and potentially broken) dependency resolution.
83 error
83 error See C:\Users\mahsa\AppData\Local\npm-cache\eresolve-report.txt for a full report.
84 verbose exit 1
85 timing npm Completed in 8948ms
86 verbose unfinished npm timer reify 1667388672612
87 verbose unfinished npm timer reify:loadTrees 1667388672623
88 verbose unfinished npm timer idealTree:buildDeps 1667388674270
89 verbose unfinished npm timer idealTree:#root 1667388674271
90 verbose code 1
91 error A complete log of this run can be found in:
91 error     C:\Users\mahsa\AppData\Local\npm-cache\_logs\2022-11-02T11_31_12_184Z-debug-0.log

**Comment by AnthonyNahas** [comment]
I've just updated the library to [v7.1.0](https://www.npmjs.com/package/ngx-auth-firebaseui) and should solve the problem
