### ISSUE TITLE
Add example of flat stacked UI login / register layout

### ISSUE THREAD

**Issue by abierbaum** [AnthonyNahas/ngx-auth-firebaseui#666]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report
- [x] feature request
```

### Desired functionality

This issue about flat auth design: https://github.com/AnthonyNahas/ngx-auth-firebaseui/issues/174 showed a potential new UI design here: https://github.com/AnthonyNahas/ngx-auth-firebaseui/issues/174#issuecomment-524487713

But I can't find any examples or documentation on how to get that type of layout.  Is this still possible and if so how?

**Comment by AnthonyNahas** [comment]
you want to change the mat form field appearance ?

**Comment by abierbaum** [comment]
I want to get the layout like the image on the right there where there is a email / password login with an OR and the vertical list of social logins.

The one on the right here:

![image](https://user-images.githubusercontent.com/397889/201493422-16873652-529d-4037-ad13-c1ef6bd6fb6e.png)

I am guessing it is supported but I didn't find an example so I didn't quite know how to do it.

**Comment by AnthonyNahas** [comment]
which component are you using ? 

the right one is `<ngx-auth-firebaesui-login></ngx-auth-firebaesui-login>`

like below

```html
<ngx-auth-firebaseui-login appearance="outline"
                                     logoUrl="assets/angular-material-extensions-logo.svg"
                                     (onCreateAccountRequested)="createAccount()">
          </ngx-auth-firebaseui-login>
```

**Comment by abierbaum** [comment]
Thanks.  I somehow missed that.  I was only seeing the options with the socials laid out horizontally.

Sorry to waste your time with this thread.  Thanks so much for all the hard work on this project!!!

**Comment by AnthonyNahas** [comment]
@abierbaum thank you<3
