### ISSUE TITLE
Feature: Localization support

### ISSUE THREAD

**Issue by ivanlucky22** [AnthonyNahas/ngx-auth-firebaseui#76]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions
ngx-auth-firebaseui v1.0.0

### Desired functionality
Interesting library, thank you, but are there any chances that localization would be provided like firebaseui-web provides?
 https://github.com/firebase/firebaseui-web#localized-widget

**Comment by AnthonyNahas** [comment]
@ivanlucky22 thanks for requesting this amazing feature! 

I'm still confusing between [ngx-translate](https://github.com/ngx-translate) and [angular i18n](https://angular.io/guide/i18n) ....

Both of them have some pro and contra... 

I will add this feature on `ngx-auth-firebaseui`'s roadmap

**Comment by AnthonyNahas** [comment]
I have some news:

I've asked the right person @ocombe, angular v7 will support Internationalization (i18n) for third party libraries! So this feature will be postponed

[check this post on twitter](https://twitter.com/ngAnthonyy/status/1005897922943311872)

**Comment by AnthonyNahas** [comment]
ngx-translate and angular_I18n are actually not the best choice for angular libraries... I am still waiting of the ivy renderer that supports many features related to i18n

**Comment by saturnino** [comment]
Hi,
so i there any way today to translate your components?
thank you

**Comment by saturnino** [comment]
I found a solution by extends AuthComponent

// override  ngx-auth-firebaseui template (ngx-auth-firebaseui.metadata)
@Component({
  selector: 'ngx-auth-firebaseui-i18n',
  templateUrl: './ngx-auth-firebase-ui-i18n.html',
})
export class AuthI18nComponent extends AuthComponent {
  readonly color: string;
}

**Comment by AnthonyNahas** [comment]
@ivanlucky22 @FabienDehopre @saturnino what do you think about the below gif ?#

![1](https://user-images.githubusercontent.com/20149774/57618058-ac64db80-7582-11e9-8462-1de43849959c.gif)

**Comment by AnthonyNahas** [comment]
[v.2.7.0](https://www.npmjs.com/package/ngx-auth-firebaseui) has been released

You can now combine ngx-translate with ngx-auth-firebaseui to support i18n !!

check the demo app [here](https://ngx-auth-firebaseui.firebaseapp.com/i18n)

thanks for contributing ❤️

**Comment by Ondrashisko** [comment]
Hi,
is there a way to translate other components as well?

**Comment by AnthonyNahas** [comment]
Can you open an issue for the target component pls!
