### ISSUE TITLE
Make 'continue as guest' optional

### ISSUE THREAD

**Issue by DomiDre** [AnthonyNahas/ngx-auth-firebaseui#79]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
I would like to have the users only register by E-mail+Password and nothing else at the moment. Right now the Anonymous Login button can not be removed from the UI. Therefore I would love if it was possible to make the 'continue as guest' optional and thus removable.

**Comment by AnthonyNahas** [comment]
done! [ngx-auth-firebaseui v1.1.0](https://www.npmjs.com/package/ngx-auth-firebaseui) is now out! 

continue as guest in now optional! Please use 
the `guestEnabled` input to enable/disable the anonymously sign in!

```html
<ngx-auth-firebaseui [guestEnabled]="false"
                     (onSuccess)="printUser($event)"
                     (onError)="printError($event)">
</ngx-auth-firebaseui>
```

take a look at the readme! I've just enhanced the documentation too!
