### ISSUE TITLE
Show Popup with Terms of Service before Registering

### ISSUE THREAD

**Issue by DomiDre** [AnthonyNahas/ngx-auth-firebaseui#80]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
To be compliant with GDPR and to inform users what they are getting into BEFORE they have their e-mail stored in the firebase database. So open a customizable popup on pressing Register would be a great function. This should of course however be optional.

**Comment by AnthonyNahas** [comment]
@DomiDre I think a dialog will be a bad UX! 

I believe a better UX would be a checkbox before/ on the top of the register button.
By checking the TOS (term of services), the user will be able to forward the authentication process!

What do you think ?

**Comment by DomiDre** [comment]
I googled a bit and think that would also be enough with GDPR if an user actively has to tick that he agrees with it. 

Could one implement altough that, if I wanted,  a dialog opens when one clicks on viewing the terms of service?

**Comment by AnthonyNahas** [comment]
<img width="513" alt="bildschirmfoto 2018-06-27 um 21 28 21" src="https://user-images.githubusercontent.com/20149774/41995341-a56375b2-7a51-11e8-9941-0432623412d7.png">

this is an example while creating a new project with firebase... 

check boxes are the right components
