### ISSUE TITLE
"Hallo" ... snackbar after registration by mail is not customizable

### ISSUE THREAD

**Issue by DomiDre** [AnthonyNahas/ngx-auth-firebaseui#83]
### Bug Report or Feature Request (mark with an `x`)
```
- [] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
After registration by e-mail the function signIn and signUp in auth-process.service.ts open a snack bar with "Hallo ${name}!". I think whether this should appear and what should be written there should be up to the implementer.

**Comment by AnthonyNahas** [comment]
Yes! you have right! However, I guess this feature should be removed as default and completely implemented by the developer using the following events:

```typescript
@Output()
  onSuccess: any;

  @Output()
  onError: any;
```

-->

```html
<ngx-auth-firebaseui (onSuccess)="printUser($event)"
                                 (onError)="printError($event)">
```

--> in your target component:

```typescript
printUser(event) {
  // show a snackbar
    console.log(event);
    this.error = false;
    this.index = 2;
  }

  printError(event) {
  // show a snackbar
    console.error(event);
    this.error = true;
  }
```

**Comment by DomiDre** [comment]
Sounds about right! :-) That would be the easiest solution

**Comment by AnthonyNahas** [comment]
@DomiDre snackbar message are now configurable via NgxAuthFirebaseUIConfig:

e.g: 

```typescript
 NgxAuthFirebaseUIModule.forRoot({
                    apiKey: 'your-firebase-apiKey',
                    authDomain: 'your-firebase-authDomain',
                    databaseURL: 'your-firebase-databaseURL',
                    projectId: 'your-firebase-projectId',
                    storageBucket: 'your-firebase-storageBucket',
                    messagingSenderId: 'your-firebase-messagingSenderId'
      }, null,
      {
        toastMessageOnAuthSuccess: false,
        toastMessageOnAuthError: false
      }),
```

default values are set to true:
see the src of code [here](https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/master/src/module/interfaces/config.interface.ts#L22-L23)
